// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsPeopleCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "people",
		Short: "Manage people",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAccountsPeopleDeleteAccountsAccountPersonCmd(flags))
	cmd.AddCommand(newAccountsPeopleGetAccountsAccountCmd(flags))
	cmd.AddCommand(newAccountsPeopleGetAccountsAccountPersonCmd(flags))
	cmd.AddCommand(newAccountsPeoplePostAccountsAccountCmd(flags))
	cmd.AddCommand(newAccountsPeoplePostAccountsAccountPersonCmd(flags))
	return cmd
}
