// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newChargesRefundsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "refunds",
		Short: "Manage refunds",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newChargesRefundsGetChargesChargeCmd(flags))
	cmd.AddCommand(newChargesRefundsGetChargesChargeChargesCmd(flags))
	cmd.AddCommand(newChargesRefundsPostChargesChargeCmd(flags))
	cmd.AddCommand(newChargesRefundsPostChargesChargeChargesCmd(flags))
	return cmd
}
