// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCustomersFundingInstructionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "funding-instructions",
		Short: "Manage funding instructions",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCustomersFundingInstructionsPostCustomersCustomerCmd(flags))
	return cmd
}
