// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newExchangeRatesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "exchange-rates",
		Short:  "Manage exchange rates",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newExchangeRatesGetCmd(flags))
	cmd.AddCommand(newExchangeRatesGetRateIdCmd(flags))
	return cmd
}
