// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newInvoiceitemsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "invoiceitems",
		Short:  "Manage invoiceitems",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newInvoiceitemsDeleteCmd(flags))
	cmd.AddCommand(newInvoiceitemsGetCmd(flags))
	cmd.AddCommand(newInvoiceitemsGetInvoiceitemCmd(flags))
	cmd.AddCommand(newInvoiceitemsPostCmd(flags))
	cmd.AddCommand(newInvoiceitemsPostInvoiceitemCmd(flags))
	return cmd
}
