// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSubscriptionsResumeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "resume",
		Short: "Manage resume",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSubscriptionsResumePostSubscriptionsSubscriptionCmd(flags))
	return cmd
}
