// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTransfersReversalsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "reversals",
		Short: "Manage reversals",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTransfersReversalsGetTransfersIdCmd(flags))
	cmd.AddCommand(newTransfersReversalsGetTransfersTransferIdCmd(flags))
	cmd.AddCommand(newTransfersReversalsPostTransfersIdCmd(flags))
	cmd.AddCommand(newTransfersReversalsPostTransfersTransferIdCmd(flags))
	return cmd
}
