// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package store

import (
	"context"
	"database/sql"
	"errors"
	"path/filepath"
	"sync"
	"testing"
	"time"

	_ "modernc.org/sqlite"
)

// TestSchemaVersion_StampedOnFreshDB verifies that opening a brand-new
// database stamps the current schema version. This is the contract that
// makes StoreSchemaVersion upgrades safe: every freshly-created DB
// records the version it was built under.
func TestSchemaVersion_StampedOnFreshDB(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open fresh db: %v", err)
	}
	defer s.Close()

	v, err := s.SchemaVersion()
	if err != nil {
		t.Fatalf("read schema version: %v", err)
	}
	if v != StoreSchemaVersion {
		t.Fatalf("fresh db version = %d, want %d", v, StoreSchemaVersion)
	}
}

// TestSchemaVersion_StampExistingZeroDB verifies the stamp-and-continue
// rule for existing deployed databases. A DB that predates the gate has
// user_version = 0; opening it with this binary should stamp the version
// to StoreSchemaVersion without touching any data.
func TestSchemaVersion_StampExistingZeroDB(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with user_version = 0 and no tables, simulating
	// a database created by a pre-gate version of the binary before any
	// migrations ran.
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`PRAGMA user_version = 0`); err != nil {
		t.Fatalf("stamp zero: %v", err)
	}
	raw.Close()

	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open pre-gate db: %v", err)
	}
	defer s.Close()

	v, err := s.SchemaVersion()
	if err != nil {
		t.Fatalf("read schema version: %v", err)
	}
	if v != StoreSchemaVersion {
		t.Fatalf("post-stamp version = %d, want %d", v, StoreSchemaVersion)
	}
}

// TestSchemaVersion_RefusesNewerDB verifies fail-fast when the on-disk
// schema is newer than the binary supports. Without this gate, a user
// who upgrades their library but not their binary would hit silent
// "no such column" errors instead of a clear version mismatch.
func TestSchemaVersion_RefusesNewerDB(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`PRAGMA user_version = 999`); err != nil {
		t.Fatalf("stamp future version: %v", err)
	}
	raw.Close()

	_, err = Open(dbPath)
	if err == nil {
		t.Fatalf("expected open to fail on newer schema, got nil")
	}
}

// TestMigrate_ConcurrentFreshDB exercises the BEGIN IMMEDIATE migration
// transaction. Without it, N goroutines opening the same fresh DB in
// parallel race per CREATE TABLE statement and trip SQLITE_BUSY despite
// the busy_timeout. With it, they serialize on the RESERVED lock
// acquired at BEGIN time and every Open succeeds.
func TestMigrate_ConcurrentFreshDB(t *testing.T) {
	if testing.Short() {
		t.Skip("concurrent migration test can take up to migrationLockTimeout under contention")
	}
	t.Parallel()

	dbPath := filepath.Join(t.TempDir(), "data.db")

	const n = 8
	errs := make(chan error, n)
	var wg sync.WaitGroup
	wg.Add(n)
	for i := 0; i < n; i++ {
		go func() {
			defer wg.Done()
			s, err := Open(dbPath)
			if err != nil {
				errs <- err
				return
			}
			s.Close()
		}()
	}
	wg.Wait()
	close(errs)

	for err := range errs {
		t.Fatalf("concurrent Open failed: %v", err)
	}
}

// holdWriteLock takes an exclusive write lock on dbPath that a peer's
// BEGIN IMMEDIATE cannot acquire until the returned cleanup runs. Used
// to construct contention scenarios in the migration tests.
func holdWriteLock(t *testing.T, dbPath string) (cleanup func()) {
	t.Helper()
	holder, err := sql.Open("sqlite", dbPath+"?_journal_mode=WAL&_busy_timeout=5000")
	if err != nil {
		t.Fatalf("open holder: %v", err)
	}
	htx, err := holder.Begin()
	if err != nil {
		_ = holder.Close()
		t.Fatalf("begin holder tx: %v", err)
	}
	if _, err := htx.Exec(`CREATE TABLE IF NOT EXISTS holder_lock (id INTEGER)`); err != nil {
		_ = htx.Rollback()
		_ = holder.Close()
		t.Fatalf("seed holder write: %v", err)
	}
	return func() {
		_ = htx.Rollback()
		_ = holder.Close()
	}
}

// TestOpenWithContext_RespectsCancellation verifies that a caller that
// cancels its context during a stalled migration sees the cancellation
// surface as the returned error within a short window, instead of
// having to wait out the full migrationLockTimeout. SIGINT in a Cobra
// command's context must interrupt store.Open, not just block on it.
func TestOpenWithContext_RespectsCancellation(t *testing.T) {
	t.Parallel()

	dbPath := filepath.Join(t.TempDir(), "data.db")
	defer holdWriteLock(t, dbPath)()

	// Pre-cancel the context. The migration's BEGIN IMMEDIATE will BUSY
	// against the holder; the very first iteration of retryOnBusy then
	// hits the ctx.Done() arm of its select and propagates ctx.Canceled.
	// A blocked-then-cancel pattern using time.Sleep would prove the
	// same property but cost the sleep interval on every CI run.
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	start := time.Now()
	_, err := OpenWithContext(ctx, dbPath)
	elapsed := time.Since(start)

	if err == nil {
		t.Fatalf("expected OpenWithContext to fail under contention with cancelled ctx")
	}
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("expected context.Canceled in error chain, got: %v", err)
	}
	// Without ctx threading this would block until migrationLockTimeout
	// (default 30s). 5s is generous headroom over the actual return
	// time (microseconds for a pre-cancelled ctx) without flaking CI.
	if elapsed > 5*time.Second {
		t.Fatalf("OpenWithContext returned after %s; pre-cancelled ctx should short-circuit immediately", elapsed)
	}
}

// TestMigrate_RejectsNewerDBImmediately verifies that an old binary
// opening a newer-schema DB rejects fast even when a peer migrator is
// still holding the write lock. The schema-version check runs on the
// pinned connection BEFORE BEGIN IMMEDIATE so the rejection path
// doesn't have to wait out the migration lock.
func TestMigrate_RejectsNewerDBImmediately(t *testing.T) {
	t.Parallel()

	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-stamp the DB at a version this binary doesn't support.
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`PRAGMA user_version = 999`); err != nil {
		t.Fatalf("stamp future version: %v", err)
	}
	raw.Close()

	defer holdWriteLock(t, dbPath)()

	start := time.Now()
	_, err = Open(dbPath)
	elapsed := time.Since(start)

	if err == nil {
		t.Fatalf("expected Open to refuse a newer-schema DB")
	}
	// The fast-path goal: rejection must arrive well under
	// migrationLockTimeout. 5s leaves headroom over the WAL init race
	// (a few ms in practice) without being so tight CI flakes.
	if elapsed > 5*time.Second {
		t.Fatalf("Open rejected after %s; fast-path should reject in well under migrationLockTimeout (30s)", elapsed)
	}
}

// TestSchemaVersion_ReopenIsIdempotent verifies that opening an already
// correctly-stamped DB is a no-op — the second open reads the version
// and the migrations are all idempotent (CREATE TABLE IF NOT EXISTS).
func TestSchemaVersion_ReopenIsIdempotent(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	s1, err := Open(dbPath)
	if err != nil {
		t.Fatalf("first open: %v", err)
	}
	s1.Close()

	s2, err := Open(dbPath)
	if err != nil {
		t.Fatalf("second open: %v", err)
	}
	defer s2.Close()

	v, err := s2.SchemaVersion()
	if err != nil {
		t.Fatalf("read schema version: %v", err)
	}
	if v != StoreSchemaVersion {
		t.Fatalf("reopened version = %d, want %d", v, StoreSchemaVersion)
	}
}

func TestResources_CompositeKeyPreservesOverlappingIDs(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	defer s.Close()

	if err := s.Upsert("biz", "shared", []byte(`{"kind":"biz","name":"Pinky restaurant"}`)); err != nil {
		t.Fatalf("upsert biz: %v", err)
	}
	if err := s.Upsert("bookmark", "shared", []byte(`{"kind":"bookmark","note":"anniversary"}`)); err != nil {
		t.Fatalf("upsert bookmark: %v", err)
	}

	biz, err := s.Get("biz", "shared")
	if err != nil {
		t.Fatalf("get biz: %v", err)
	}
	if string(biz) != `{"kind":"biz","name":"Pinky restaurant"}` {
		t.Fatalf("biz payload = %s", biz)
	}

	bookmark, err := s.Get("bookmark", "shared")
	if err != nil {
		t.Fatalf("get bookmark: %v", err)
	}
	if string(bookmark) != `{"kind":"bookmark","note":"anniversary"}` {
		t.Fatalf("bookmark payload = %s", bookmark)
	}

	var count int
	if err := s.DB().QueryRow(`SELECT COUNT(*) FROM resources WHERE id = 'shared'`).Scan(&count); err != nil {
		t.Fatalf("count overlapping rows: %v", err)
	}
	if count != 2 {
		t.Fatalf("overlapping row count = %d, want 2", count)
	}

	matches, err := s.Search("restaurant", 10)
	if err != nil {
		t.Fatalf("search restaurant: %v", err)
	}
	if len(matches) != 1 || string(matches[0]) != `{"kind":"biz","name":"Pinky restaurant"}` {
		t.Fatalf("restaurant search = %q, want only biz payload", matches)
	}
}

// Callers detect missing rows via errors.Is(err, sql.ErrNoRows); present
// rows return the JSON payload with a nil error.
func TestGet_MissingRowReturnsErrNoRows(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	data, err := s.Get("missing_type", "missing_id")
	if !errors.Is(err, sql.ErrNoRows) {
		t.Fatalf("Get missing row err = %v, want sql.ErrNoRows", err)
	}
	if data != nil {
		t.Fatalf("Get missing row data = %s, want nil", data)
	}

	if err := s.Upsert("present_type", "present_id", []byte(`{"ok":true}`)); err != nil {
		t.Fatalf("upsert: %v", err)
	}
	got, err := s.Get("present_type", "present_id")
	if err != nil {
		t.Fatalf("Get present row: %v", err)
	}
	if string(got) != `{"ok":true}` {
		t.Fatalf("Get present row data = %s, want {\"ok\":true}", got)
	}
}

func TestMigrate_ResourcesCompositeKeyUpgrade(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE resources (
		id TEXT PRIMARY KEY,
		resource_type TEXT NOT NULL,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP,
		updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create v1 resources: %v", err)
	}
	if _, err := raw.Exec(`CREATE VIRTUAL TABLE resources_fts USING fts5(
		id, resource_type, content, tokenize='porter unicode61'
	)`); err != nil {
		raw.Close()
		t.Fatalf("create v1 resources_fts: %v", err)
	}
	if _, err := raw.Exec(`INSERT INTO resources (id, resource_type, data) VALUES ('shared', 'biz', '{"kind":"biz","name":"legacy restaurant"}')`); err != nil {
		raw.Close()
		t.Fatalf("insert v1 resource: %v", err)
	}
	if _, err := raw.Exec(`INSERT INTO resources_fts (rowid, id, resource_type, content) VALUES (1, 'shared', 'biz', '{"kind":"biz","name":"legacy restaurant"}')`); err != nil {
		raw.Close()
		t.Fatalf("insert v1 fts row: %v", err)
	}
	if _, err := raw.Exec(`PRAGMA user_version = 1`); err != nil {
		raw.Close()
		t.Fatalf("stamp v1: %v", err)
	}
	raw.Close()

	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	v, err := s.SchemaVersion()
	if err != nil {
		t.Fatalf("read schema version: %v", err)
	}
	if v != StoreSchemaVersion {
		t.Fatalf("upgraded version = %d, want %d", v, StoreSchemaVersion)
	}

	rows, err := s.DB().Query(`PRAGMA table_info(resources)`)
	if err != nil {
		t.Fatalf("table_info resources: %v", err)
	}
	defer rows.Close()

	pk := map[string]int{}
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pkOrder int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pkOrder); err != nil {
			t.Fatalf("scan table_info: %v", err)
		}
		pk[name] = pkOrder
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("table_info rows: %v", err)
	}
	if pk["resource_type"] != 1 || pk["id"] != 2 {
		t.Fatalf("resources primary key order = resource_type:%d id:%d, want resource_type:1 id:2", pk["resource_type"], pk["id"])
	}

	if err := s.Upsert("bookmark", "shared", []byte(`{"kind":"bookmark","note":"after upgrade"}`)); err != nil {
		t.Fatalf("upsert overlapping resource after upgrade: %v", err)
	}

	biz, err := s.Get("biz", "shared")
	if err != nil {
		t.Fatalf("get migrated biz: %v", err)
	}
	if string(biz) != `{"kind":"biz","name":"legacy restaurant"}` {
		t.Fatalf("migrated biz payload = %s", biz)
	}

	bookmark, err := s.Get("bookmark", "shared")
	if err != nil {
		t.Fatalf("get upgraded bookmark: %v", err)
	}
	if string(bookmark) != `{"kind":"bookmark","note":"after upgrade"}` {
		t.Fatalf("upgraded bookmark payload = %s", bookmark)
	}

	matches, err := s.Search("legacy", 10)
	if err != nil {
		t.Fatalf("search migrated fts: %v", err)
	}
	if len(matches) != 1 || string(matches[0]) != `{"kind":"biz","name":"legacy restaurant"}` {
		t.Fatalf("legacy search = %q, want migrated biz payload", matches)
	}
}

// TestOpenReadOnly_RejectsWrites pins the contract: direct and CTE-wrapped
// writes against the main DB fail under mode=ro. Deliberately does not
// assert VACUUM INTO and ATTACH DATABASE — modernc.org/sqlite allows both
// under mode=ro, so those defenses live in the handleSQL keyword blocklist.
func TestOpenReadOnly_RejectsWrites(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	rw, err := Open(dbPath)
	if err != nil {
		t.Fatalf("seed open: %v", err)
	}
	if _, err := rw.DB().Exec(`INSERT INTO resources (id, resource_type, data) VALUES ('seed', 'thing', '{}')`); err != nil {
		t.Fatalf("seed insert: %v", err)
	}
	rw.Close()

	ro, err := OpenReadOnly(dbPath)
	if err != nil {
		t.Fatalf("open read-only: %v", err)
	}
	defer ro.Close()

	writes := []struct {
		name string
		stmt string
	}{
		{"insert", `INSERT INTO resources (id, resource_type, data) VALUES ('x', 'y', '{}')`},
		{"update", `UPDATE resources SET resource_type = 'hijacked' WHERE id = 'seed'`},
		{"delete", `DELETE FROM resources WHERE id = 'seed'`},
		{"replace", `REPLACE INTO resources (id, resource_type, data) VALUES ('seed', 'evil', '{}')`},
		// CTE-wrapped INSERT is load-bearing: it justifies leaving WITH
		// out of the handleSQL blocklist so SELECT-form CTEs work.
		{"cte_insert", `WITH stale AS (SELECT id FROM resources) INSERT INTO resources (id, resource_type, data) SELECT id || '-evil', 'thing', '{}' FROM stale`},
	}
	for _, w := range writes {
		if _, err := ro.DB().Exec(w.stmt); err == nil {
			t.Errorf("%s succeeded under mode=ro; expected rejection. stmt=%q", w.name, w.stmt)
		}
	}

	var count int
	if err := ro.DB().QueryRow(`SELECT COUNT(*) FROM resources`).Scan(&count); err != nil {
		t.Fatalf("read-only SELECT failed: %v", err)
	}
	if count != 1 {
		t.Fatalf("SELECT returned %d rows, want 1 (only the seed should remain)", count)
	}
	if err := ro.DB().QueryRow(`WITH r AS (SELECT id FROM resources WHERE id = 'seed') SELECT COUNT(*) FROM r`).Scan(&count); err != nil {
		t.Fatalf("read-only WITH...SELECT CTE failed: %v", err)
	}
	if count != 1 {
		t.Fatalf("CTE SELECT returned %d rows, want 1", count)
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Assistants verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Assistants(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "assistants" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("assistants")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created_at",
		"description",
		"instructions",
		"metadata",
		"model",
		"name",
		"object",
		"response_format",
		"temperature",
		"tool_resources",
		"top_p",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from assistants after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Audio verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Audio(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "audio" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("audio")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created_at",
		"language",
		"name",
		"object",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from audio after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Batches verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Batches(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "batches" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("batches")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"cancelled_at",
		"cancelling_at",
		"completed_at",
		"completion_window",
		"created_at",
		"endpoint",
		"error_file_id",
		"expired_at",
		"expires_at",
		"failed_at",
		"finalizing_at",
		"in_progress_at",
		"input_file_id",
		"metadata",
		"model",
		"object",
		"output_file_id",
		"status",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from batches after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_BatchesCancel verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_BatchesCancel(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "batches_cancel" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("batches_cancel")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"batches_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from batches_cancel after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Chat verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Chat(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "chat" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("chat")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created",
		"model",
		"object",
		"service_tier",
		"system_fingerprint",
		"audio",
		"content",
		"content_parts",
		"refusal",
		"role",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from chat after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Chatkit verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Chatkit(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "chatkit" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("chatkit")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created_at",
		"object",
		"status",
		"title",
		"user",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from chatkit after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Completions verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Completions(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "completions" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("completions")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created",
		"model",
		"object",
		"system_fingerprint",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from completions after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Containers verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Containers(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "containers" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("containers")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created_at",
		"last_active_at",
		"memory_limit",
		"name",
		"object",
		"status",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from containers after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_ContainersFiles verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_ContainersFiles(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "containers_files" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("containers_files")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"containers_id",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from containers_files after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Conversations verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Conversations(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "conversations" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("conversations")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created_at",
		"metadata",
		"object",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from conversations after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Items verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Items(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "items" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("items")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"conversations_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from items after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Evals verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Evals(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "evals" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("evals")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created_at",
		"metadata",
		"name",
		"object",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from evals after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_EvalsRuns verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_EvalsRuns(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "evals_runs" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("evals_runs")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"evals_id",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from evals_runs after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Files verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Files(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "files" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("files")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"deleted",
		"object",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from files after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_FilesContent verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_FilesContent(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "files_content" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("files_content")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"files_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from files_content after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_FineTuning verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_FineTuning(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "fine_tuning" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("fine_tuning")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created_at",
		"object",
		"project_id",
		"level",
		"message",
		"type",
		"fine_tuned_model_checkpoint",
		"fine_tuning_job_id",
		"step_number",
		"error",
		"estimated_finish",
		"fine_tuned_model",
		"finished_at",
		"integrations",
		"metadata",
		"model",
		"organization_id",
		"seed",
		"status",
		"trained_tokens",
		"training_file",
		"validation_file",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from fine_tuning after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Images verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Images(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "images" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("images")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"b64_json",
		"revised_prompt",
		"url",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from images after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Models verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Models(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "models" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("models")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created",
		"object",
		"owned_by",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from models after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Organization verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Organization(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "organization" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("organization")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created_at",
		"last_used_at",
		"name",
		"object",
		"redacted_value",
		"active",
		"actor",
		"effective_at",
		"type",
		"created_by",
		"created_by_user_obj",
		"description",
		"metadata",
		"predefined_role",
		"resource_type",
		"updated_at",
		"email",
		"group_type",
		"is_scim_managed",
		"accepted_at",
		"expires_at",
		"role",
		"status",
		"group_id",
		"group_name",
		"project_id",
		"batch_1_day_max_input_tokens",
		"max_audio_megabytes_per_1_minute",
		"max_images_per_1_minute",
		"max_requests_per_1_day",
		"max_requests_per_1_minute",
		"max_tokens_per_1_minute",
		"model",
		"added_at",
		"archived_at",
		"external_key_id",
		"api_key_last_used_at",
		"created",
		"developer_persona",
		"is_default",
		"is_scale_tier_authorized_purchaser",
		"is_service_account",
		"technical_level",
		"end_time",
		"start_time",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from organization after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Groups verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Groups(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "groups" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("groups")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"projects_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from groups after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Roles verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Roles(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "roles" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("roles")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"projects_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from roles after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Users verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Users(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "users" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("users")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"projects_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from users after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Realtime verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Realtime(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "realtime" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("realtime")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"expires_at",
		"session",
		"value",
		"instructions",
		"max_output_tokens",
		"model",
		"object",
		"output_modalities",
		"tool_choice",
		"tracing",
		"input_audio_format",
		"modalities",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from realtime after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Responses verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Responses(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "responses" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("responses")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"background",
		"completed_at",
		"conversation",
		"created_at",
		"error",
		"incomplete_details",
		"instructions",
		"max_output_tokens",
		"max_tool_calls",
		"metadata",
		"model",
		"object",
		"output_text",
		"parallel_tool_calls",
		"previous_response_id",
		"prompt",
		"prompt_cache_key",
		"prompt_cache_retention",
		"reasoning",
		"safety_identifier",
		"service_tier",
		"status",
		"temperature",
		"tool_choice",
		"top_logprobs",
		"top_p",
		"truncation",
		"user",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from responses after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_ResponsesCancel verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_ResponsesCancel(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "responses_cancel" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("responses_cancel")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"responses_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from responses_cancel after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_InputItems verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_InputItems(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "input_items" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("input_items")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"responses_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from input_items after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Skills verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Skills(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "skills" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("skills")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created_at",
		"default_version",
		"description",
		"latest_version",
		"name",
		"object",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from skills after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_SkillsContent verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_SkillsContent(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "skills_content" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("skills_content")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"skills_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from skills_content after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Versions verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Versions(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "versions" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("versions")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"skills_id",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from versions after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Threads verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Threads(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "threads" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("threads")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created_at",
		"metadata",
		"object",
		"tool_resources",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from threads after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Messages verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Messages(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "messages" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("messages")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"threads_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from messages after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_ThreadsRuns verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_ThreadsRuns(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "threads_runs" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("threads_runs")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"threads_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from threads_runs after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Uploads verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Uploads(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "uploads" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("uploads")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"bytes",
		"created_at",
		"expires_at",
		"file",
		"filename",
		"object",
		"purpose",
		"status",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from uploads after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_UploadsCancel verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_UploadsCancel(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "uploads_cancel" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("uploads_cancel")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"uploads_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from uploads_cancel after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Complete verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Complete(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "complete" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("complete")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"uploads_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from complete after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Parts verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Parts(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "parts" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("parts")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"uploads_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from parts after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_VectorStores verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_VectorStores(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "vector_stores" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("vector_stores")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"created_at",
		"expires_at",
		"last_active_at",
		"metadata",
		"name",
		"object",
		"status",
		"usage_bytes",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from vector_stores after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_FileBatches verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_FileBatches(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "file_batches" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("file_batches")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"vector_stores_id",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from file_batches after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_VectorStoresFiles verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_VectorStoresFiles(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "vector_stores_files" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("vector_stores_files")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"vector_stores_id",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from vector_stores_files after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Search verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Search(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "search" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("search")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"vector_stores_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from search after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Videos verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Videos(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "videos" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("videos")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"completed_at",
		"created_at",
		"error",
		"expires_at",
		"model",
		"object",
		"progress",
		"prompt",
		"remixed_from_video_id",
		"seconds",
		"size",
		"status",
		"name",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from videos after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_VideosContent verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_VideosContent(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "videos_content" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("videos_content")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"videos_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from videos_content after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Remix verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Remix(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "remix" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("remix")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"videos_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from remix after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_SyncState verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_SyncState(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE "sync_state" (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info("sync_state")`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"last_cursor",
		"last_synced_at",
		"total_count",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from sync_state after migrate", want)
		}
	}
}
