// Durable design-sync input generator.
// Regenerates apps/web/.ds-barrel.ts (gitignored build input) from the single
// source of truth: componentSrcMap in .design-sync/config.json.
// Run before a (re-)sync if the barrel is missing or the component set changed:
//   node .design-sync/gen-barrel.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const cfg = JSON.parse(readFileSync(new URL('./config.json', import.meta.url), 'utf8'));
const map = cfg.componentSrcMap ?? {};
// derive unique source files from the map values (src/components/ui/<file>.tsx)
const files = [...new Set(Object.values(map).map((p) => p.replace(/^src\/components\/ui\//, '').replace(/\.tsx$/, '')))].sort();

const barrel =
  '// AUTO-GENERATED by .design-sync/gen-barrel.mjs. Build input only — not part of the app.\n' +
  '// Re-exports the UI component library so the converter bundles it to window.NorthStarUI.\n' +
  files.map((f) => `export * from "./src/components/ui/${f}";`).join('\n') + '\n';

writeFileSync('apps/web/.ds-barrel.ts', barrel);
console.log(`wrote apps/web/.ds-barrel.ts — ${files.length} component files`);
