// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newOrganizationsIssuesBulkMutateAnOrganizationSCmd(flags *rootFlags) *cobra.Command {
	var flagEnvironment string
	var flagProject string
	var flagId string
	var flagQuery string
	var flagViewId string
	var flagSort string
	var flagLimit int
	var bodyAssignedTo string
	var bodyDiscard bool
	var bodyHasSeen bool
	var bodyInbox bool
	var bodyIsBookmarked bool
	var bodyIsPublic bool
	var bodyIsSubscribed bool
	var bodyMerge bool
	var bodyPriority string
	var bodyStatus string
	var bodyStatusDetailsIgnoreCount int
	var bodyStatusDetailsIgnoreDuration int
	var bodyStatusDetailsIgnoreUserCount int
	var bodyStatusDetailsIgnoreUserWindow int
	var bodyStatusDetailsIgnoreWindow int
	var bodyStatusDetailsInCommitCommit string
	var bodyStatusDetailsInCommitRepository string
	var bodyStatusDetailsInNextRelease bool
	var bodyStatusDetailsInRelease string
	var bodySubstatus string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "bulk-mutate-an-organization-s <organization_id_or_slug>",
		Aliases:     []string{"update"},
		Short:       "Bulk mutate various attributes on a maxmimum of 1000 issues. - For non-status updates, the `id` query parameter is...",
		Example:     "  sentry-pp-cli organizations issues bulk-mutate-an-organization-s example-value --assigned-to example-value",
		Annotations: map[string]string{"pp:endpoint": "issues.bulk-mutate-an-organization-s", "pp:method": "PUT", "pp:path": "/api/0/organizations/{organization_id_or_slug}/issues/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("sort") {
				allowedSort := []string{"date", "freq", "inbox", "new", "recommended", "trends", "user"}
				validSort := false
				for _, v := range allowedSort {
					if flagSort == v {
						validSort = true
						break
					}
				}
				if !validSort {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort", flagSort, allowedSort)
				}
			}
			if !stdinBody {
				if !cmd.Flags().Changed("assigned-to") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "assigned-to")
				}
				if !cmd.Flags().Changed("discard") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "discard")
				}
				if !cmd.Flags().Changed("has-seen") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "has-seen")
				}
				if !cmd.Flags().Changed("inbox") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "inbox")
				}
				if !cmd.Flags().Changed("is-bookmarked") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "is-bookmarked")
				}
				if !cmd.Flags().Changed("is-public") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "is-public")
				}
				if !cmd.Flags().Changed("is-subscribed") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "is-subscribed")
				}
				if !cmd.Flags().Changed("merge") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "merge")
				}
				if !cmd.Flags().Changed("priority") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "priority")
				}
				if !cmd.Flags().Changed("status") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "status")
				}
				if !cmd.Flags().Changed("status-details-ignore-count") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "status-details-ignore-count")
				}
				if !cmd.Flags().Changed("status-details-ignore-duration") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "status-details-ignore-duration")
				}
				if !cmd.Flags().Changed("status-details-ignore-user-count") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "status-details-ignore-user-count")
				}
				if !cmd.Flags().Changed("status-details-ignore-user-window") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "status-details-ignore-user-window")
				}
				if !cmd.Flags().Changed("status-details-ignore-window") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "status-details-ignore-window")
				}
				if !cmd.Flags().Changed("status-details-in-commit-commit") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "status-details-in-commit-commit")
				}
				if !cmd.Flags().Changed("status-details-in-commit-repository") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "status-details-in-commit-repository")
				}
				if !cmd.Flags().Changed("status-details-in-next-release") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "status-details-in-next-release")
				}
				if !cmd.Flags().Changed("status-details-in-release") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "status-details-in-release")
				}
				if !cmd.Flags().Changed("substatus") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "substatus")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/0/organizations/{organization_id_or_slug}/issues/"
			path = replacePathParam(path, "organization_id_or_slug", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAssignedTo != "" {
					body["assignedTo"] = bodyAssignedTo
				}
				if bodyDiscard != false {
					body["discard"] = bodyDiscard
				}
				if bodyHasSeen != false {
					body["hasSeen"] = bodyHasSeen
				}
				if bodyInbox != false {
					body["inbox"] = bodyInbox
				}
				if bodyIsBookmarked != false {
					body["isBookmarked"] = bodyIsBookmarked
				}
				if bodyIsPublic != false {
					body["isPublic"] = bodyIsPublic
				}
				if bodyIsSubscribed != false {
					body["isSubscribed"] = bodyIsSubscribed
				}
				if bodyMerge != false {
					body["merge"] = bodyMerge
				}
				if bodyPriority != "" {
					body["priority"] = bodyPriority
				}
				if bodyStatus != "" {
					body["status"] = bodyStatus
				}
				{
					nestedStatusDetails := map[string]any{}
					if bodyStatusDetailsIgnoreCount != 0 {
						nestedStatusDetails["ignoreCount"] = bodyStatusDetailsIgnoreCount
					}
					if bodyStatusDetailsIgnoreDuration != 0 {
						nestedStatusDetails["ignoreDuration"] = bodyStatusDetailsIgnoreDuration
					}
					if bodyStatusDetailsIgnoreUserCount != 0 {
						nestedStatusDetails["ignoreUserCount"] = bodyStatusDetailsIgnoreUserCount
					}
					if bodyStatusDetailsIgnoreUserWindow != 0 {
						nestedStatusDetails["ignoreUserWindow"] = bodyStatusDetailsIgnoreUserWindow
					}
					if bodyStatusDetailsIgnoreWindow != 0 {
						nestedStatusDetails["ignoreWindow"] = bodyStatusDetailsIgnoreWindow
					}
					{
						nestedStatusDetailsInCommit := map[string]any{}
						if bodyStatusDetailsInCommitCommit != "" {
							nestedStatusDetailsInCommit["commit"] = bodyStatusDetailsInCommitCommit
						}
						if bodyStatusDetailsInCommitRepository != "" {
							nestedStatusDetailsInCommit["repository"] = bodyStatusDetailsInCommitRepository
						}
						if len(nestedStatusDetailsInCommit) > 0 {
							nestedStatusDetails["inCommit"] = nestedStatusDetailsInCommit
						}
					}
					if bodyStatusDetailsInNextRelease != false {
						nestedStatusDetails["inNextRelease"] = bodyStatusDetailsInNextRelease
					}
					if bodyStatusDetailsInRelease != "" {
						nestedStatusDetails["inRelease"] = bodyStatusDetailsInRelease
					}
					if len(nestedStatusDetails) > 0 {
						body["statusDetails"] = nestedStatusDetails
					}
				}
				if bodySubstatus != "" {
					body["substatus"] = bodySubstatus
				}
			}
			params := map[string]string{}
			if flagEnvironment != "" {
				params["environment"] = fmt.Sprintf("%v", flagEnvironment)
			}
			if flagProject != "" {
				params["project"] = fmt.Sprintf("%v", flagProject)
			}
			if flagId != "" {
				params["id"] = fmt.Sprintf("%v", flagId)
			}
			if flagQuery != "" {
				params["query"] = fmt.Sprintf("%v", flagQuery)
			}
			if flagViewId != "" {
				params["viewId"] = fmt.Sprintf("%v", flagViewId)
			}
			if flagSort != "" {
				params["sort"] = fmt.Sprintf("%v", flagSort)
			}
			if flagLimit != 0 {
				params["limit"] = fmt.Sprintf("%v", flagLimit)
			}
			data, statusCode, err := c.PutWithParams(path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "issues",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagEnvironment, "environment", "", "The name of environments to filter by.")
	cmd.Flags().StringVar(&flagProject, "project", "", "The IDs of projects to filter by. `-1` means all available projects. For example, the following are valid...")
	cmd.Flags().StringVar(&flagId, "id", "", "The list of issue IDs to mutate. It is optional for status updates, in which an implicit `update all` is assumed.")
	cmd.Flags().StringVar(&flagQuery, "query", "is:unresolved", "An optional search query for filtering issues. A default query will apply if no view/query is set. For all results...")
	cmd.Flags().StringVar(&flagViewId, "view-id", "", "The ID of the view to use. If no query is present, the view's query and filters will be applied.")
	cmd.Flags().StringVar(&flagSort, "sort", "date", "The sort order of the view. Options include 'Last Seen' (`date`), 'First Seen' (`new`), 'Trends' (`trends`),... (one of: date, freq, inbox, new, recommended, trends, user)")
	cmd.Flags().IntVar(&flagLimit, "limit", 100, "The maximum number of issues to affect. The maximum is 100.")
	cmd.Flags().StringVar(&bodyAssignedTo, "assigned-to", "", "The user or team that should be assigned to the issues. Values take the form of `<user_id>`, `user:<user_id>`,...")
	cmd.Flags().BoolVar(&bodyDiscard, "discard", false, "If true, discards the issues instead of updating them.")
	cmd.Flags().BoolVar(&bodyHasSeen, "has-seen", false, "If true, marks the issue as seen by the requestor.")
	cmd.Flags().BoolVar(&bodyInbox, "inbox", false, "If true, marks the issue as reviewed by the requestor.")
	cmd.Flags().BoolVar(&bodyIsBookmarked, "is-bookmarked", false, "If true, bookmarks the issue for the requestor.")
	cmd.Flags().BoolVar(&bodyIsPublic, "is-public", false, "If true, publishes the issue.")
	cmd.Flags().BoolVar(&bodyIsSubscribed, "is-subscribed", false, "If true, subscribes the requestor to the issue.")
	cmd.Flags().BoolVar(&bodyMerge, "merge", false, "If true, merges the issues together.")
	cmd.Flags().StringVar(&bodyPriority, "priority", "", "The priority that should be set for the issues * `low` * `medium` * `high`")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "Limit mutations to only issues with the given status. * `resolved` * `unresolved` * `ignored` *...")
	cmd.Flags().IntVar(&bodyStatusDetailsIgnoreCount, "status-details-ignore-count", 0, "Ignore the issue until it has occurred this many times in `ignoreWindow` minutes.")
	cmd.Flags().IntVar(&bodyStatusDetailsIgnoreDuration, "status-details-ignore-duration", 0, "Ignore the issue until for this many minutes.")
	cmd.Flags().IntVar(&bodyStatusDetailsIgnoreUserCount, "status-details-ignore-user-count", 0, "Ignore the issue until it has affected this many users in `ignoreUserWindow` minutes.")
	cmd.Flags().IntVar(&bodyStatusDetailsIgnoreUserWindow, "status-details-ignore-user-window", 0, "Ignore the issue until it has affected `ignoreUserCount` users in this many minutes. (Max: 1 week)")
	cmd.Flags().IntVar(&bodyStatusDetailsIgnoreWindow, "status-details-ignore-window", 0, "Ignore the issue until it has occurred `ignoreCount` times in this many minutes. (Max: 1 week)")
	cmd.Flags().StringVar(&bodyStatusDetailsInCommitCommit, "status-details-in-commit-commit", "", "The SHA of the resolving commit.")
	cmd.Flags().StringVar(&bodyStatusDetailsInCommitRepository, "status-details-in-commit-repository", "", "The name of the repository (as it appears in Sentry).")
	cmd.Flags().BoolVar(&bodyStatusDetailsInNextRelease, "status-details-in-next-release", false, "If true, marks the issue as resolved in the next release.")
	cmd.Flags().StringVar(&bodyStatusDetailsInRelease, "status-details-in-release", "", "The version of the release that the issue should be resolved in.If set to `latest`, the latest release will be used.")
	cmd.Flags().StringVar(&bodySubstatus, "substatus", "", "The new substatus of the issue. * `archived_until_escalating` * `archived_until_condition_met` * `archived_forever`...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
