// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newOrganizationsDetectorsUpdateAMonitorByIdCmd(flags *rootFlags) *cobra.Command {
	var bodyConditionGroupConditions string
	var bodyConditionGroupId string
	var bodyConditionGroupLogicType string
	var bodyConfig string
	var bodyDataSources string
	var bodyDescription string
	var bodyEnabled bool
	var bodyName string
	var bodyOwner string
	var bodyType string
	var bodyWorkflowIds string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update-a-monitor-by-id <organization_id_or_slug> <detector_id>",
		Short:       "Update an existing monitor",
		Example:     "  sentry-pp-cli organizations detectors update-a-monitor-by-id example-value 550e8400-e29b-41d4-a716-446655440000 --name example-resource",
		Annotations: map[string]string{"pp:endpoint": "detectors.update-a-monitor-by-id", "pp:method": "PUT", "pp:path": "/api/0/organizations/{organization_id_or_slug}/detectors/{detector_id}/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("condition-group-logic-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "condition-group-logic-type")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "type")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/0/organizations/{organization_id_or_slug}/detectors/{detector_id}/"
			path = replacePathParam(path, "organization_id_or_slug", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("detector_id is required\nUsage: %s <%s>", cmd.CommandPath(), "detector_id"))
			}
			path = replacePathParam(path, "detector_id", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedConditionGroup := map[string]any{}
					if bodyConditionGroupConditions != "" {
						var parsedConditionGroupConditions any
						if err := json.Unmarshal([]byte(bodyConditionGroupConditions), &parsedConditionGroupConditions); err != nil {
							return fmt.Errorf("parsing --condition-group-conditions JSON: %w", err)
						}
						nestedConditionGroup["conditions"] = parsedConditionGroupConditions
					}
					if bodyConditionGroupId != "" {
						nestedConditionGroup["id"] = bodyConditionGroupId
					}
					if bodyConditionGroupLogicType != "" {
						nestedConditionGroup["logic_type"] = bodyConditionGroupLogicType
					}
					if len(nestedConditionGroup) > 0 {
						body["condition_group"] = nestedConditionGroup
					}
				}
				if bodyConfig != "" {
					var parsedConfig any
					if err := json.Unmarshal([]byte(bodyConfig), &parsedConfig); err != nil {
						return fmt.Errorf("parsing --config JSON: %w", err)
					}
					body["config"] = parsedConfig
				}
				if bodyDataSources != "" {
					var parsedDataSources any
					if err := json.Unmarshal([]byte(bodyDataSources), &parsedDataSources); err != nil {
						return fmt.Errorf("parsing --data-sources JSON: %w", err)
					}
					body["data_sources"] = parsedDataSources
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyEnabled != false {
					body["enabled"] = bodyEnabled
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyOwner != "" {
					body["owner"] = bodyOwner
				}
				if bodyType != "" {
					body["type"] = bodyType
				}
				if bodyWorkflowIds != "" {
					var parsedWorkflowIds any
					if err := json.Unmarshal([]byte(bodyWorkflowIds), &parsedWorkflowIds); err != nil {
						return fmt.Errorf("parsing --workflow-ids JSON: %w", err)
					}
					body["workflow_ids"] = parsedWorkflowIds
				}
			}
			data, statusCode, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "detectors",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyConditionGroupConditions, "condition-group-conditions", "", "Conditions")
	cmd.Flags().StringVar(&bodyConditionGroupId, "condition-group-id", "", "Id")
	cmd.Flags().StringVar(&bodyConditionGroupLogicType, "condition-group-logic-type", "", "* `any` * `any-short` * `all` * `none`")
	cmd.Flags().StringVar(&bodyConfig, "config", "", "The issue detection type configuration. - `detectionType` - `static`: Threshold based monitor - `percent`: Change...")
	cmd.Flags().StringVar(&bodyDataSources, "data-sources", "", "The data sources for the monitor to use based on what you want to measure. **Number of Errors Metric Monitor** -...")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "A description of the monitor. Will be used in the resulting issue.")
	cmd.Flags().BoolVar(&bodyEnabled, "enabled", false, "Set to False if you want to disable the monitor.")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name of the monitor.")
	cmd.Flags().StringVar(&bodyOwner, "owner", "", "The ID user or team who owns the monitor or alert prefaced by the string 'user' or 'team'. **User** ```json...")
	cmd.Flags().StringVar(&bodyType, "type", "", "The type of monitor - `metric_issue`.")
	cmd.Flags().StringVar(&bodyWorkflowIds, "workflow-ids", "", "The IDs of the alerts to connect this monitor to. Use the 'Fetch Alerts' endpoint to find the IDs.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
