// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrganizationsSpikeProtectionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "spike-protections",
		Short: "Endpoints for Spike Protection Notifications",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOrganizationsSpikeProtectionsDisableCmd(flags))
	cmd.AddCommand(newOrganizationsSpikeProtectionsEnableCmd(flags))
	return cmd
}
