// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrganizationsForwardingCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "forwarding",
		Short: "Manage forwarding",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOrganizationsForwardingCreateADataForwarderForAnOrganizationCmd(flags))
	cmd.AddCommand(newOrganizationsForwardingDeleteADataForwarderForAnOrganizationCmd(flags))
	cmd.AddCommand(newOrganizationsForwardingRetrieveDataForwardersForAnOrganizationCmd(flags))
	cmd.AddCommand(newOrganizationsForwardingUpdateADataForwarderForAnOrganizationCmd(flags))
	return cmd
}
