// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newOrganizationsMonitorsUpdateACmd(flags *rootFlags) *cobra.Command {
	var bodyConfigCheckinMargin int
	var bodyConfigFailureIssueThreshold int
	var bodyConfigMaxRuntime int
	var bodyConfigRecoveryThreshold int
	var bodyConfigSchedule string
	var bodyConfigScheduleType string
	var bodyConfigTimezone string
	var bodyIsMuted bool
	var bodyName string
	var bodyOwner string
	var bodyProject string
	var bodySlug string
	var bodyStatus string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update-a <organization_id_or_slug> <monitor_id_or_slug>",
		Aliases:     []string{"update"},
		Short:       "Update a monitor.",
		Example:     "  sentry-pp-cli organizations monitors update-a example-value example-value --name example-resource",
		Annotations: map[string]string{"pp:endpoint": "monitors.update-a", "pp:method": "PUT", "pp:path": "/api/0/organizations/{organization_id_or_slug}/monitors/{monitor_id_or_slug}/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("config-schedule") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "config-schedule")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("project") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "project")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/0/organizations/{organization_id_or_slug}/monitors/{monitor_id_or_slug}/"
			path = replacePathParam(path, "organization_id_or_slug", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("monitor_id_or_slug is required\nUsage: %s <%s>", cmd.CommandPath(), "monitor_id_or_slug"))
			}
			path = replacePathParam(path, "monitor_id_or_slug", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedConfig := map[string]any{}
					if bodyConfigCheckinMargin != 0 {
						nestedConfig["checkin_margin"] = bodyConfigCheckinMargin
					}
					if bodyConfigFailureIssueThreshold != 0 {
						nestedConfig["failure_issue_threshold"] = bodyConfigFailureIssueThreshold
					}
					if bodyConfigMaxRuntime != 0 {
						nestedConfig["max_runtime"] = bodyConfigMaxRuntime
					}
					if bodyConfigRecoveryThreshold != 0 {
						nestedConfig["recovery_threshold"] = bodyConfigRecoveryThreshold
					}
					if bodyConfigSchedule != "" {
						nestedConfig["schedule"] = bodyConfigSchedule
					}
					if bodyConfigScheduleType != "" {
						nestedConfig["schedule_type"] = bodyConfigScheduleType
					}
					if bodyConfigTimezone != "" {
						nestedConfig["timezone"] = bodyConfigTimezone
					}
					if len(nestedConfig) > 0 {
						body["config"] = nestedConfig
					}
				}
				if bodyIsMuted != false {
					body["is_muted"] = bodyIsMuted
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyOwner != "" {
					body["owner"] = bodyOwner
				}
				if bodyProject != "" {
					body["project"] = bodyProject
				}
				if bodySlug != "" {
					body["slug"] = bodySlug
				}
				if bodyStatus != "" {
					body["status"] = bodyStatus
				}
			}
			data, statusCode, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "monitors",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&bodyConfigCheckinMargin, "config-checkin-margin", 0, "How long (in minutes) after the expected checkin time will we wait until we consider the checkin to have been missed.")
	cmd.Flags().IntVar(&bodyConfigFailureIssueThreshold, "config-failure-issue-threshold", 0, "How many consecutive missed or failed check-ins in a row before creating a new issue.")
	cmd.Flags().IntVar(&bodyConfigMaxRuntime, "config-max-runtime", 0, "How long (in minutes) is the checkin allowed to run for in CheckInStatus.IN_PROGRESS before it is considered failed.")
	cmd.Flags().IntVar(&bodyConfigRecoveryThreshold, "config-recovery-threshold", 0, "How many successful check-ins in a row before resolving an issue.")
	cmd.Flags().StringVar(&bodyConfigSchedule, "config-schedule", "", "Varies depending on the schedule_type. Is either a crontab string, or a 2 element tuple for intervals (e.g. [1, 'day'])")
	cmd.Flags().StringVar(&bodyConfigScheduleType, "config-schedule-type", "", "Currently supports 'crontab' or 'interval' * `crontab` * `interval`")
	cmd.Flags().StringVar(&bodyConfigTimezone, "config-timezone", "", "tz database style timezone string * `Africa/Abidjan` * `Africa/Accra` * `Africa/Addis_Ababa` * `Africa/Algiers` *...")
	cmd.Flags().BoolVar(&bodyIsMuted, "is-muted", false, "Disable creation of monitor incidents")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name of the monitor. Used for notifications. If not set the slug will be derived from your monitor name.")
	cmd.Flags().StringVar(&bodyOwner, "owner", "", "The ID of the team or user that owns the monitor. (eg. user:51 or team:6)")
	cmd.Flags().StringVar(&bodyProject, "project", "", "The project slug to associate the monitor to.")
	cmd.Flags().StringVar(&bodySlug, "slug", "", "Uniquely identifies your monitor within your organization. Changing this slug will require updates to any...")
	cmd.Flags().StringVar(&bodyStatus, "status", "active", "Status of the monitor. Disabled monitors will not accept events and will not count towards the monitor quota. *...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
