// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newOrganizationsStatsSummaryRetrieveAnOrganizationSEventsCountByProjectCmd(flags *rootFlags) *cobra.Command {
	var flagField string
	var flagStatsPeriod string
	var flagInterval string
	var flagStart string
	var flagEnd string
	var flagProject string
	var flagCategory string
	var flagOutcome string
	var flagReason string
	var flagDownload bool

	cmd := &cobra.Command{
		Use:         "retrieve-an-organization-s-events-count-by-project <organization_id_or_slug>",
		Aliases:     []string{"get"},
		Short:       "Query summarized event counts by project for your Organization. Also see...",
		Example:     "  sentry-pp-cli organizations stats-summary retrieve-an-organization-s-events-count-by-project example-value --field example-value",
		Annotations: map[string]string{"pp:endpoint": "stats-summary.retrieve-an-organization-s-events-count-by-project", "pp:method": "GET", "pp:path": "/api/0/organizations/{organization_id_or_slug}/stats-summary/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("field") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "field")
			}
			if cmd.Flags().Changed("field") {
				allowedField := []string{"sum(quantity)", "sum(times_seen)"}
				validField := false
				for _, v := range allowedField {
					if flagField == v {
						validField = true
						break
					}
				}
				if !validField {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "field", flagField, allowedField)
				}
			}
			if cmd.Flags().Changed("category") {
				allowedCategory := []string{"error", "transaction", "attachment", "replays", "profiles"}
				validCategory := false
				for _, v := range allowedCategory {
					if flagCategory == v {
						validCategory = true
						break
					}
				}
				if !validCategory {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "category", flagCategory, allowedCategory)
				}
			}
			if cmd.Flags().Changed("outcome") {
				allowedOutcome := []string{"accepted", "filtered", "rate_limited", "invalid", "abuse", "client_discard", "cardinality_limited"}
				validOutcome := false
				for _, v := range allowedOutcome {
					if flagOutcome == v {
						validOutcome = true
						break
					}
				}
				if !validOutcome {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "outcome", flagOutcome, allowedOutcome)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/0/organizations/{organization_id_or_slug}/stats-summary/"
			path = replacePathParam(path, "organization_id_or_slug", args[0])
			params := map[string]string{}
			if flagField != "" {
				params["field"] = fmt.Sprintf("%v", flagField)
			}
			if flagStatsPeriod != "" {
				params["statsPeriod"] = fmt.Sprintf("%v", flagStatsPeriod)
			}
			if flagInterval != "" {
				params["interval"] = fmt.Sprintf("%v", flagInterval)
			}
			if flagStart != "" {
				params["start"] = fmt.Sprintf("%v", flagStart)
			}
			if flagEnd != "" {
				params["end"] = fmt.Sprintf("%v", flagEnd)
			}
			if flagProject != "" {
				params["project"] = fmt.Sprintf("%v", flagProject)
			}
			if flagCategory != "" {
				params["category"] = fmt.Sprintf("%v", flagCategory)
			}
			if flagOutcome != "" {
				params["outcome"] = fmt.Sprintf("%v", flagOutcome)
			}
			if flagReason != "" {
				params["reason"] = fmt.Sprintf("%v", flagReason)
			}
			if flagDownload != false {
				params["download"] = fmt.Sprintf("%v", flagDownload)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "stats-summary", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagField, "field", "", "the `sum(quantity)` field is bytes for attachments, and all others the 'event' count for those types of events.... (one of: sum(quantity), sum(times_seen))")
	cmd.Flags().StringVar(&flagStatsPeriod, "stats-period", "", "This defines the range of the time series, relative to now. The range is given in a `<number><unit>` format. For...")
	cmd.Flags().StringVar(&flagInterval, "interval", "", "This is the resolution of the time series, given in the same format as `statsPeriod`. The default resolution is `1h`...")
	cmd.Flags().StringVar(&flagStart, "start", "", "This defines the start of the time series range as an explicit datetime, either in UTC ISO8601 or epoch seconds. Use...")
	cmd.Flags().StringVar(&flagEnd, "end", "", "This defines the inclusive end of the time series range as an explicit datetime, either in UTC ISO8601 or epoch...")
	cmd.Flags().StringVar(&flagProject, "project", "", "The ID of the projects to filter by.")
	cmd.Flags().StringVar(&flagCategory, "category", "", "If filtering by attachments, you cannot filter by any other category due to quantity values becoming nonsensical... (one of: error, transaction, attachment, replays, profiles)")
	cmd.Flags().StringVar(&flagOutcome, "outcome", "", "See https://docs.sentry.io/product/stats/ for more information on outcome statuses. * `accepted` * `filtered` *... (one of: accepted, filtered, rate_limited, invalid, abuse, client_discard, cardinality_limited)")
	cmd.Flags().StringVar(&flagReason, "reason", "", "The reason field will contain why an event was filtered/dropped.")
	cmd.Flags().BoolVar(&flagDownload, "download", false, "Download the API response in as a csv file")

	return cmd
}
