// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newOrganizationsReleasesUploadANewOrganizationFileCmd(flags *rootFlags) *cobra.Command {
	var bodyDist string
	var bodyFile string
	var bodyHeader string
	var bodyName string

	cmd := &cobra.Command{
		Use:         "upload-a-new-organization-file <organization_id_or_slug> <version>",
		Short:       "Upload a new file for the given release. Unlike other API requests, files must be uploaded using the traditional...",
		Example:     "  sentry-pp-cli organizations releases upload-a-new-organization-file example-value example-value --file example-value",
		Annotations: map[string]string{"pp:endpoint": "releases.upload-a-new-organization-file", "pp:method": "POST", "pp:path": "https://.sentry.io/api/0/organizations/{organization_id_or_slug}/releases/{version}/files/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("file") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "file")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://.sentry.io/api/0/organizations/{organization_id_or_slug}/releases/{version}/files/"
			path = replacePathParam(path, "organization_id_or_slug", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("version is required\nUsage: %s <%s>", cmd.CommandPath(), "version"))
			}
			path = replacePathParam(path, "version", args[1])
			fields := map[string]string{}
			fileFields := map[string]string{}
			if bodyDist != "" {
				fields["dist"] = bodyDist
			}
			if bodyFile != "" {
				fileFields["file"] = bodyFile
			}
			if bodyHeader != "" {
				fields["header"] = bodyHeader
			}
			if bodyName != "" {
				fields["name"] = bodyName
			}

			data, statusCode, err := c.PostMultipart(path, fields, fileFields)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "releases",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyDist, "dist", "", "The name of the dist.")
	cmd.Flags().StringVar(&bodyFile, "file", "", "The multipart encoded file.")
	cmd.Flags().StringVar(&bodyHeader, "header", "", "This parameter can be supplied multiple times to attach headers to the file. Each header is a string in the format...")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name (full path) of the file.")

	return cmd
}
