// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectsEventsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "events",
		Short: "Endpoints for events and issues",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectsEventsDebugIssuesRelatedToSourceMapsForAGivenCmd(flags))
	cmd.AddCommand(newProjectsEventsListAProjectSErrorCmd(flags))
	cmd.AddCommand(newProjectsEventsRetrieveAnForAProjectCmd(flags))
	return cmd
}
