// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectsEnvironmentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "environments",
		Short: "Endpoints for Environments",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectsEnvironmentsListAProjectSCmd(flags))
	cmd.AddCommand(newProjectsEnvironmentsRetrieveAProjectCmd(flags))
	cmd.AddCommand(newProjectsEnvironmentsUpdateAProjectCmd(flags))
	return cmd
}
