// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newProjectsIssuesBulkMutateAListOfCmd(flags *rootFlags) *cobra.Command {
	var flagId string
	var flagStatus string
	var bodyAssignedTo string
	var bodyHasSeen bool
	var bodyIgnoreDuration int
	var bodyIsBookmarked bool
	var bodyIsPublic bool
	var bodyMerge bool
	var bodyStatusDetailsIgnoreCount int
	var bodyStatusDetailsIgnoreDuration int
	var bodyStatusDetailsIgnoreUserCount int
	var bodyStatusDetailsIgnoreUserWindow int
	var bodyStatusDetailsIgnoreWindow int
	var bodyStatusDetailsInCommit string
	var bodyStatusDetailsInNextRelease bool
	var bodyStatusDetailsInRelease string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "bulk-mutate-a-list-of <organization_id_or_slug> <project_id_or_slug>",
		Aliases:     []string{"update"},
		Short:       "Bulk mutate various attributes on issues. The list of issues to modify is given through the `id` query parameter. It...",
		Example:     "  sentry-pp-cli projects issues bulk-mutate-a-list-of example-value example-value",
		Annotations: map[string]string{"pp:endpoint": "issues.bulk-mutate-a-list-of", "pp:method": "PUT", "pp:path": "/api/0/projects/{organization_id_or_slug}/{project_id_or_slug}/issues/"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/0/projects/{organization_id_or_slug}/{project_id_or_slug}/issues/"
			path = replacePathParam(path, "organization_id_or_slug", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("project_id_or_slug is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id_or_slug"))
			}
			path = replacePathParam(path, "project_id_or_slug", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAssignedTo != "" {
					body["assignedTo"] = bodyAssignedTo
				}
				if bodyHasSeen != false {
					body["hasSeen"] = bodyHasSeen
				}
				if bodyIgnoreDuration != 0 {
					body["ignoreDuration"] = bodyIgnoreDuration
				}
				if bodyIsBookmarked != false {
					body["isBookmarked"] = bodyIsBookmarked
				}
				if bodyIsPublic != false {
					body["isPublic"] = bodyIsPublic
				}
				if bodyMerge != false {
					body["merge"] = bodyMerge
				}
				{
					nestedStatusDetails := map[string]any{}
					if bodyStatusDetailsIgnoreCount != 0 {
						nestedStatusDetails["ignoreCount"] = bodyStatusDetailsIgnoreCount
					}
					if bodyStatusDetailsIgnoreDuration != 0 {
						nestedStatusDetails["ignoreDuration"] = bodyStatusDetailsIgnoreDuration
					}
					if bodyStatusDetailsIgnoreUserCount != 0 {
						nestedStatusDetails["ignoreUserCount"] = bodyStatusDetailsIgnoreUserCount
					}
					if bodyStatusDetailsIgnoreUserWindow != 0 {
						nestedStatusDetails["ignoreUserWindow"] = bodyStatusDetailsIgnoreUserWindow
					}
					if bodyStatusDetailsIgnoreWindow != 0 {
						nestedStatusDetails["ignoreWindow"] = bodyStatusDetailsIgnoreWindow
					}
					if bodyStatusDetailsInCommit != "" {
						nestedStatusDetails["inCommit"] = bodyStatusDetailsInCommit
					}
					if bodyStatusDetailsInNextRelease != false {
						nestedStatusDetails["inNextRelease"] = bodyStatusDetailsInNextRelease
					}
					if bodyStatusDetailsInRelease != "" {
						nestedStatusDetails["inRelease"] = bodyStatusDetailsInRelease
					}
					if len(nestedStatusDetails) > 0 {
						body["statusDetails"] = nestedStatusDetails
					}
				}
			}
			params := map[string]string{}
			if flagId != "" {
				params["id"] = fmt.Sprintf("%v", flagId)
			}
			if flagStatus != "" {
				params["status"] = fmt.Sprintf("%v", flagStatus)
			}
			data, statusCode, err := c.PutWithParams(path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "issues",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagId, "id", "", "A list of IDs of the issues to be mutated. This parameter shall be repeated for each issue. It is optional only if a...")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Optionally limits the query to issues of the specified status. Valid values are `'resolved'`, `'reprocessing'`,...")
	cmd.Flags().StringVar(&bodyAssignedTo, "assigned-to", "", "The actor ID (or username) of the user or team that should be assigned to this issue.")
	cmd.Flags().BoolVar(&bodyHasSeen, "has-seen", false, "In case this API call is invoked with a user context this allows changing of the flag that indicates if the user has...")
	cmd.Flags().IntVar(&bodyIgnoreDuration, "ignore-duration", 0, "The number of minutes to ignore this issue.")
	cmd.Flags().BoolVar(&bodyIsBookmarked, "is-bookmarked", false, "In case this API call is invoked with a user context this allows changing of the bookmark flag.")
	cmd.Flags().BoolVar(&bodyIsPublic, "is-public", false, "Sets the issue to public or private.")
	cmd.Flags().BoolVar(&bodyMerge, "merge", false, "Allows to merge or unmerge different issues.")
	cmd.Flags().IntVar(&bodyStatusDetailsIgnoreCount, "status-details-ignore-count", 0, "Ignore count")
	cmd.Flags().IntVar(&bodyStatusDetailsIgnoreDuration, "status-details-ignore-duration", 0, "Ignore duration")
	cmd.Flags().IntVar(&bodyStatusDetailsIgnoreUserCount, "status-details-ignore-user-count", 0, "Ignore user count")
	cmd.Flags().IntVar(&bodyStatusDetailsIgnoreUserWindow, "status-details-ignore-user-window", 0, "Ignore user window")
	cmd.Flags().IntVar(&bodyStatusDetailsIgnoreWindow, "status-details-ignore-window", 0, "Ignore window")
	cmd.Flags().StringVar(&bodyStatusDetailsInCommit, "status-details-in-commit", "", "In commit")
	cmd.Flags().BoolVar(&bodyStatusDetailsInNextRelease, "status-details-in-next-release", false, "In next release")
	cmd.Flags().StringVar(&bodyStatusDetailsInRelease, "status-details-in-release", "", "In release")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
