// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectsIssuesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "issues",
		Short: "Manage issues",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectsIssuesBulkMutateAListOfCmd(flags))
	cmd.AddCommand(newProjectsIssuesBulkRemoveAListOfCmd(flags))
	cmd.AddCommand(newProjectsIssuesListAProjectSCmd(flags))
	return cmd
}
