// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSentryAppsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "sentry-apps",
		Short:  "Manage sentry apps",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSentryAppsDeleteACustomIntegrationCmd(flags))
	cmd.AddCommand(newSentryAppsRetrieveACustomIntegrationByIdOrSlugCmd(flags))
	cmd.AddCommand(newSentryAppsUpdateAnExistingCustomIntegrationCmd(flags))
	return cmd
}
