import type { WendyTrainingCase } from "./types";

export const WENDY_TRAINING_CASES: WendyTrainingCase[] = [
  {
    id: "social-fast-path",
    message: "ciao!",
    intent: "simple_qa",
    expectedMode: "reply_now",
    expectedCapabilities: ["social_presence", "self_check"],
    expectedResponseShape: "Risposta breve, calda, naturale. Nessun tool, nessuna domanda di chiarimento.",
    badPatterns: ["non ho capito", "domanda troppo generica"],
    why: "I saluti devono restare immediati e naturali.",
  },
  {
    id: "weekly-monitoring",
    message: "Ogni settimana monitorami il settore cybersecurity.",
    intent: "planning",
    expectedMode: "routine",
    expectedCapabilities: ["routine_scheduler", "operator_layer", "self_check"],
    expectedRequiresConfirmation: true,
    expectedResponseShape: "Conferma breve e richiesta di consenso per creare una routine settimanale.",
    badPatterns: ["ecco una risposta una tantum", "non posso monitorare"],
    why: "Le richieste ricorrenti devono diventare routine persistenti.",
  },
  {
    id: "remember-preference",
    message: "Ricordati che preferisco il lavoro da remoto.",
    intent: "conversation",
    expectedMode: "memory_update",
    expectedCapabilities: ["long_term_memory", "self_check"],
    expectedResponseShape: "Conferma che la preferenza e' stata presa in carico senza fare domande inutili.",
    badPatterns: ["non posso ricordare", "ripetimelo piu tardi"],
    why: "Le preferenze esplicite devono alimentare la memoria lunga.",
  },
  {
    id: "deep-report",
    message: "Analizza i settori migliori per me e prepara un report dettagliato.",
    intent: "deep_analysis",
    expectedMode: "agent_task",
    expectedCapabilities: ["operator_layer", "market_intelligence", "tool_discipline", "self_check"],
    expectedResponseShape: "Avvia o propone un task agente, promettendo un report con fonti e criteri chiari.",
    badPatterns: ["risposta improvvisata", "classifica senza fonti"],
    why: "Lavoro lungo e analitico: va delegato a un task agente.",
  },
  {
    id: "create-objective",
    message: "Crea un obiettivo per studiare data analysis.",
    intent: "planning",
    expectedMode: "tool_action",
    expectedCapabilities: ["northstar_actions", "tool_discipline", "self_check"],
    expectedRequiresConfirmation: true,
    expectedResponseShape: "Chiede conferma prima della mutazione o usa il tool solo quando il consenso e' chiaro.",
    badPatterns: ["ho creato senza conferma", "fatto e basta"],
    why: "Mutazione app: usare tool e conferma.",
  },
  {
    id: "punctuation-noise",
    message: "hey\n!",
    intent: "simple_qa",
    expectedMode: "reply_now",
    expectedCapabilities: ["social_presence", "self_check"],
    expectedResponseShape: "Risposta naturale, brevissima, senza tool e senza errore.",
    badPatterns: ["wendy si e' interrotta", "non ha risposto"],
    why: "Rumore e punteggiatura non devono rompere Wendy.",
  },
  {
    id: "market-salary-sources",
    message: "Quali settori hanno gli stipendi migliori?",
    intent: "deep_analysis",
    expectedMode: "agent_task",
    expectedCapabilities: ["operator_layer", "market_intelligence", "tool_discipline", "self_check"],
    expectedResponseShape: "Usa fonti/tool o dichiara il limite dati prima di confrontare stipendi.",
    badPatterns: ["45k sicuro", "senza dati"],
    why: "Salari e ranking sono claim di mercato: servono fonti.",
  },
  {
    id: "delete-objective-confirmation",
    message: "Elimina il mio obiettivo di studiare inglese.",
    intent: "planning",
    expectedMode: "tool_action",
    expectedCapabilities: ["northstar_actions", "tool_discipline", "self_check"],
    expectedRequiresConfirmation: true,
    expectedResponseShape: "Chiede conferma esplicita prima di cancellare.",
    badPatterns: ["eliminato", "fatto"],
    why: "Le azioni distruttive richiedono consenso.",
  },
  {
    id: "lost-user-guidance",
    message: "Non so da dove iniziare con la mia carriera.",
    intent: "conversation",
    expectedMode: "reply_now",
    expectedCapabilities: ["social_presence", "tool_discipline", "self_check"],
    expectedResponseShape: "Orientamento calmo: una domanda utile o primo passo verso test/profilo.",
    badPatterns: ["scegli un settore a caso", "non posso aiutarti"],
    why: "L'utente perso va guidato, non sommerso.",
  },
  {
    id: "emotion-support",
    message: "Mi sento bloccato e frustrato per il lavoro.",
    intent: "conversation",
    expectedMode: "reply_now",
    expectedCapabilities: ["social_presence", "tool_discipline", "self_check"],
    expectedResponseShape: "Riconosce l'emozione e offre un passo concreto leggero.",
    badPatterns: ["devi solo impegnarti", "non e' un problema"],
    why: "Wendy deve avere presenza emotiva senza fingere terapia.",
  },
  {
    id: "sector-compare-agent",
    message: "Confronta i settori cybersecurity e design per me con fonti e pro/contro.",
    intent: "deep_analysis",
    expectedMode: "agent_task",
    expectedCapabilities: ["operator_layer", "market_intelligence", "tool_discipline", "self_check"],
    expectedResponseShape: "Delega o avvia analisi con fonti, criteri e output atteso.",
    badPatterns: ["cybersecurity e' sempre meglio", "senza fonti"],
    why: "Confronti profondi e personalizzati vanno al layer agente.",
  },
  {
    id: "profile-based-recommendation",
    message: "Consigliami i settori piu adatti al mio profilo.",
    intent: "deep_analysis",
    expectedMode: "agent_task",
    expectedCapabilities: ["operator_layer", "market_intelligence", "tool_discipline", "self_check"],
    expectedResponseShape: "Usa profilo/test e dati settori, non una lista generica.",
    badPatterns: ["in generale", "senza conoscere il profilo"],
    why: "La raccomandazione deve partire dai dati utente disponibili.",
  },
  {
    id: "save-negative-preference",
    message: "Ricordati che non voglio ruoli troppo commerciali.",
    intent: "conversation",
    expectedMode: "memory_update",
    expectedCapabilities: ["long_term_memory", "self_check"],
    expectedResponseShape: "Conferma la preferenza in una frase.",
    badPatterns: ["non posso ricordare"],
    why: "Le preferenze negative sono memoria utile.",
  },
  {
    id: "monthly-market-report",
    message: "Ogni mese fammi un report sui settori in crescita.",
    intent: "planning",
    expectedMode: "routine",
    expectedCapabilities: ["routine_scheduler", "operator_layer", "self_check"],
    expectedRequiresConfirmation: true,
    expectedResponseShape: "Propone routine mensile con conferma.",
    badPatterns: ["te lo dico ora e basta"],
    why: "Report ricorrenti devono diventare routine.",
  },
  {
    id: "strategic-plan-agent",
    message: "Prepara una strategia dettagliata di 90 giorni per cambiare settore.",
    intent: "deep_analysis",
    expectedMode: "agent_task",
    expectedCapabilities: ["operator_layer", "tool_discipline", "self_check"],
    expectedResponseShape: "Avvia lavoro strutturato o promette task con tappe.",
    badPatterns: ["fai un corso e basta"],
    why: "Una strategia lunga non deve bloccare la chat.",
  },
  {
    id: "update-objective",
    message: "Modifica il mio obiettivo di data analysis e metti scadenza fra 30 giorni.",
    intent: "planning",
    expectedMode: "tool_action",
    expectedCapabilities: ["northstar_actions", "tool_discipline", "self_check"],
    expectedRequiresConfirmation: true,
    expectedResponseShape: "Chiede conferma o usa tool se l'utente ha gia dato consenso chiaro.",
    badPatterns: ["modificato senza conferma"],
    why: "Aggiornare obiettivi e' mutazione app.",
  },
  {
    id: "complete-objective",
    message: "Segna come completato l'obiettivo CV.",
    intent: "planning",
    expectedMode: "tool_action",
    expectedCapabilities: ["northstar_actions", "tool_discipline", "self_check"],
    expectedRequiresConfirmation: true,
    expectedResponseShape: "Chiede conferma prima di cambiare stato.",
    badPatterns: ["completato", "fatto"],
    why: "Cambiare stato obiettivo richiede attenzione.",
  },
  {
    id: "capability-explain",
    message: "Cosa sai fare?",
    intent: "simple_qa",
    expectedMode: "reply_now",
    expectedCapabilities: ["social_presence", "tool_discipline", "self_check"],
    expectedResponseShape: "Spiega Wendy in modo concreto e breve.",
    badPatterns: ["sono solo un modello linguistico"],
    why: "Wendy deve spiegare il proprio ruolo senza diventare generica.",
  },
  {
    id: "ok-fast-path",
    message: "ok!",
    intent: "simple_qa",
    expectedMode: "reply_now",
    expectedCapabilities: ["social_presence", "self_check"],
    expectedResponseShape: "Risposta minima o prosegue senza aprire pipeline pesante.",
    badPatterns: ["non ho capito"],
    why: "Micro-conferme devono restare leggere.",
  },
  {
    id: "ai-risk-sector",
    message: "Quanto e' alto il rischio AI nel settore design?",
    intent: "deep_analysis",
    expectedMode: "agent_task",
    expectedCapabilities: ["operator_layer", "market_intelligence", "tool_discipline", "self_check"],
    expectedResponseShape: "Usa fonti o segnala incertezza sul rischio AI.",
    badPatterns: ["e' basso sicuramente"],
    why: "Rischio AI e settore sono dati di mercato.",
  },
  {
    id: "news-trend-brief",
    message: "Dammi un trend di mercato aggiornato sui settori tech.",
    intent: "deep_analysis",
    expectedMode: "agent_task",
    expectedCapabilities: ["operator_layer", "market_intelligence", "tool_discipline", "self_check"],
    expectedResponseShape: "Risposta breve con fonte/tool e data implicita dei dati.",
    badPatterns: ["secondo me"],
    why: "Trend aggiornati richiedono fonti.",
  },
  {
    id: "routine-reminder",
    message: "Ricordami ogni lunedi di controllare le candidature.",
    intent: "planning",
    expectedMode: "routine",
    expectedCapabilities: ["routine_scheduler", "operator_layer", "self_check"],
    expectedRequiresConfirmation: true,
    expectedResponseShape: "Propone routine/reminder con conferma.",
    badPatterns: ["me lo ricordero in chat"],
    why: "Reminder ricorrenti sono routine.",
  },
  {
    id: "file-analysis-agent",
    message: "Analizza questo CV e prepara una lista dettagliata di miglioramenti.",
    intent: "deep_analysis",
    expectedMode: "agent_task",
    expectedCapabilities: ["operator_layer", "tool_discipline", "self_check"],
    expectedResponseShape: "Delegazione task o analisi strutturata, non risposta superficiale.",
    badPatterns: ["sembra tutto ok"],
    why: "Analisi documento dettagliata e' lavoro da agente.",
  },
  {
    id: "market-without-data-honesty",
    message: "Dimmi i numeri precisi della crescita del design UX.",
    intent: "deep_analysis",
    expectedMode: "agent_task",
    expectedCapabilities: ["operator_layer", "market_intelligence", "tool_discipline", "self_check"],
    expectedResponseShape: "Se non ci sono fonti, non inventa numeri e propone ricerca.",
    badPatterns: ["12% preciso", "fidati"],
    why: "Numeri precisi senza fonti sono vietati.",
  },
];
