// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCalendarCreateEventCmd(flags *rootFlags) *cobra.Command {
	var bodyAllDay bool
	var bodyCategory string
	var bodyColor string
	var bodyDescription string
	var bodyEndAt string
	var bodyIsRecurring bool
	var bodyLinkedContentIds string
	var bodyLinkedGoal string
	var bodyLinkedSectorId int
	var bodyPriority string
	var bodyRecurrenceRule string
	var bodyReminders string
	var bodyStartAt string
	var bodyStatus string
	var bodyTags string
	var bodyTitle string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-event",
		Short:       "Create a new calendar event",
		Example:     "  northstar-pp-cli calendar create-event --end-at 2026-01-15T09:00:00Z",
		Annotations: map[string]string{"pp:endpoint": "calendar.create-event", "pp:method": "POST", "pp:path": "/calendar/events"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("end-at") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "end-at")
				}
				if !cmd.Flags().Changed("start-at") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "start-at")
				}
				if !cmd.Flags().Changed("title") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "title")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/calendar/events"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAllDay != false {
					body["allDay"] = bodyAllDay
				}
				if bodyCategory != "" {
					body["category"] = bodyCategory
				}
				if bodyColor != "" {
					body["color"] = bodyColor
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyEndAt != "" {
					body["endAt"] = bodyEndAt
				}
				if bodyIsRecurring != false {
					body["isRecurring"] = bodyIsRecurring
				}
				if bodyLinkedContentIds != "" {
					var parsedLinkedContentIds any
					if err := json.Unmarshal([]byte(bodyLinkedContentIds), &parsedLinkedContentIds); err != nil {
						return fmt.Errorf("parsing --linked-content-ids JSON: %w", err)
					}
					body["linkedContentIds"] = parsedLinkedContentIds
				}
				if bodyLinkedGoal != "" {
					body["linkedGoal"] = bodyLinkedGoal
				}
				if bodyLinkedSectorId != 0 {
					body["linkedSectorId"] = bodyLinkedSectorId
				}
				if bodyPriority != "" {
					body["priority"] = bodyPriority
				}
				if bodyRecurrenceRule != "" {
					body["recurrenceRule"] = bodyRecurrenceRule
				}
				if bodyReminders != "" {
					var parsedReminders any
					if err := json.Unmarshal([]byte(bodyReminders), &parsedReminders); err != nil {
						return fmt.Errorf("parsing --reminders JSON: %w", err)
					}
					body["reminders"] = parsedReminders
				}
				if bodyStartAt != "" {
					body["startAt"] = bodyStartAt
				}
				if bodyStatus != "" {
					body["status"] = bodyStatus
				}
				if bodyTags != "" {
					var parsedTags any
					if err := json.Unmarshal([]byte(bodyTags), &parsedTags); err != nil {
						return fmt.Errorf("parsing --tags JSON: %w", err)
					}
					body["tags"] = parsedTags
				}
				if bodyTitle != "" {
					body["title"] = bodyTitle
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "calendar",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().BoolVar(&bodyAllDay, "all-day", false, "All day")
	cmd.Flags().StringVar(&bodyCategory, "category", "task", "Category")
	cmd.Flags().StringVar(&bodyColor, "color", "", "Color")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Description")
	cmd.Flags().StringVar(&bodyEndAt, "end-at", "", "End at")
	cmd.Flags().BoolVar(&bodyIsRecurring, "is-recurring", false, "Is recurring")
	cmd.Flags().StringVar(&bodyLinkedContentIds, "linked-content-ids", "", "Linked content ids")
	cmd.Flags().StringVar(&bodyLinkedGoal, "linked-goal", "", "Linked goal")
	cmd.Flags().IntVar(&bodyLinkedSectorId, "linked-sector-id", 0, "Linked sector id")
	cmd.Flags().StringVar(&bodyPriority, "priority", "medium", "Priority")
	cmd.Flags().StringVar(&bodyRecurrenceRule, "recurrence-rule", "", "Recurrence rule")
	cmd.Flags().StringVar(&bodyReminders, "reminders", "", "Reminders")
	cmd.Flags().StringVar(&bodyStartAt, "start-at", "", "Start at")
	cmd.Flags().StringVar(&bodyStatus, "status", "todo", "Status")
	cmd.Flags().StringVar(&bodyTags, "tags", "", "Tags")
	cmd.Flags().StringVar(&bodyTitle, "title", "", "Title")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
