// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCalendarCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "calendar",
		Short:  "Calendar events and reminders",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCalendarAddEventReminderCmd(flags))
	cmd.AddCommand(newCalendarCreateEventCmd(flags))
	cmd.AddCommand(newCalendarDeleteEventCmd(flags))
	cmd.AddCommand(newCalendarDeleteEventReminderCmd(flags))
	cmd.AddCommand(newCalendarGetEventCmd(flags))
	cmd.AddCommand(newCalendarGetQuotaCmd(flags))
	cmd.AddCommand(newCalendarGetUpcomingEventsCmd(flags))
	cmd.AddCommand(newCalendarListEventsCmd(flags))
	cmd.AddCommand(newCalendarUpdateEventCmd(flags))
	cmd.AddCommand(newCalendarUpdateEventReminderCmd(flags))
	return cmd
}
