// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPushCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "push",
		Short:  "Browser push notification subscriptions",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPushSubscribeCmd(flags))
	cmd.AddCommand(newPushUnsubscribeCmd(flags))
	return cmd
}
