// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTestSessionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "test-sessions",
		Short:  "Manage test sessions",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTestSessionsGetCmd(flags))
	cmd.AddCommand(newTestSessionsSubmitTestCmd(flags))
	cmd.AddCommand(newTestSessionsConfirmCmd(flags))
	return cmd
}
