import { Router } from "express";
import { requireAdminAccess } from "../middleware/auth";
import adminAgentsRouter from "./admin/agents";
import adminBusinessRouter from "./admin/business";
import adminCatalogsRouter from "./admin/catalogs";
import adminErrorReportRouter from "./admin/error-report";
import adminGrowthQueueRouter from "./admin/growth-queue";
import adminMemoryGraphRouter from "./admin/memory-graph";
import adminOpsRouter from "./admin/ops";
import adminPipelineRunsRouter from "./admin/pipeline-runs";
import adminPipelinesRouter from "./admin/pipelines";
import adminPluginsRouter from "./admin/plugins";
import adminPromptsRouter from "./admin/prompts";
import adminQualityRouter from "./admin/quality";
import adminResearchRouter from "./admin/research";
import adminReviewRouter from "./admin/review";
import adminSubscriptionsRouter from "./admin/subscriptions";
import adminWendyBrainRouter from "./admin/wendy-brain";
import adminWendyRouter from "./admin/wendy";

const router = Router();

router.use(requireAdminAccess);
router.use(adminReviewRouter);
router.use(adminAgentsRouter);
router.use(adminPipelineRunsRouter);
router.use(adminPipelinesRouter);
router.use(adminSubscriptionsRouter);
router.use(adminOpsRouter);
router.use(adminBusinessRouter);
router.use(adminCatalogsRouter);
router.use(adminGrowthQueueRouter);
router.use(adminPromptsRouter);
router.use(adminQualityRouter);
router.use(adminMemoryGraphRouter);
router.use(adminPluginsRouter);
router.use(adminErrorReportRouter);
router.use(adminResearchRouter);
router.use(adminWendyBrainRouter);
router.use(adminWendyRouter);

export default router;
