import { db, sectorsTable } from "@workspace/db";

const SECTORS = [
  {
    name: "Tecnologia & Digitale",
    description:
      "Sviluppo software, piattaforme digitali, cloud, automazione e prodotti digitali. Un settore in costante evoluzione che offre opportunità globali e alta scalabilità.",
    riasecTypes: ["I", "R", "C"],
    skills: ["Programmazione", "Problem solving", "Pensiero logico", "Apprendimento continuo", "Architettura software"],
    avgSalaryMin: 35000,
    avgSalaryMax: 120000,
    growthRate: 28,
    automationRisk: "low" as const,
    scalability: "high" as const,
    trend: "booming" as const,
    timeToAutonomy: "12-24 mesi con formazione intensiva",
    advantages: [
      "Altissima domanda globale",
      "Possibilità di lavorare da remoto",
      "Stipendi competitivi",
      "Crescita rapida di carriera",
    ],
    disadvantages: [
      "Aggiornamento continuo necessario",
      "Alta competitività",
      "Rischio saturazione entry-level",
    ],
    opportunities: ["AI Engineer", "Full Stack Developer", "Product Manager", "DevOps Engineer", "No-code Specialist"],
    icon: "code",
    color: "#6366f1",
  },
  {
    name: "Cybersecurity",
    description:
      "Protezione di sistemi, reti, dati e infrastrutture digitali. Settore in crescita costante con forte domanda di professionisti affidabili e alta utilità strategica.",
    riasecTypes: ["I", "C", "R"],
    skills: ["Analisi delle minacce", "Penetration testing", "Risk management", "Compliance", "Precisione"],
    avgSalaryMin: 40000,
    avgSalaryMax: 130000,
    growthRate: 32,
    automationRisk: "low" as const,
    scalability: "high" as const,
    trend: "booming" as const,
    timeToAutonomy: "12-18 mesi con certificazioni OSCP/CompTIA",
    advantages: [
      "Domanda in forte crescita",
      "Stipendi molto elevati",
      "Alta importanza strategica",
      "Possibilità remote work",
    ],
    disadvantages: [
      "Stress elevato",
      "Certificazioni spesso costose",
      "Responsabilità alta",
    ],
    opportunities: ["SOC Analyst", "Ethical Hacker", "Penetration Tester", "Security Architect", "Incident Response Specialist"],
    icon: "shield",
    color: "#ef4444",
  },
  {
    name: "Data & Analytics",
    description:
      "Analisi dati, business intelligence, data science e data engineering. Settore utile per decisioni basate sui numeri, in crescita con la trasformazione digitale.",
    riasecTypes: ["I", "C", "R"],
    skills: ["SQL", "Python", "Statistica", "Visualizzazione dati", "Machine learning"],
    avgSalaryMin: 32000,
    avgSalaryMax: 110000,
    growthRate: 25,
    automationRisk: "low" as const,
    scalability: "high" as const,
    trend: "booming" as const,
    timeToAutonomy: "12-24 mesi con portfolio dati",
    advantages: [
      "Alta domanda trasversale",
      "Base per ruoli AI avanzati",
      "Buona retribuzione",
      "Applicabile in tutti i settori",
    ],
    disadvantages: [
      "Rischio di ruoli ripetitivi",
      "Necessità di forte precisione",
      "Formazione tecnica richiesta",
    ],
    opportunities: ["Data Analyst", "Data Scientist", "BI Analyst", "Data Engineer", "Analytics Consultant"],
    icon: "bar-chart-2",
    color: "#0ea5e9",
  },
  {
    name: "Fintech",
    description:
      "Finanza digitale, pagamenti innovativi, banking tecnologico e wealth tech. Unisce tecnologia e finanza con forte potenziale di scalabilità e prodotto ad alto valore.",
    riasecTypes: ["E", "I", "C"],
    skills: ["Analisi finanziaria", "Conoscenza prodotti finanziari", "UX per finanza", "Blockchain", "Risk analysis"],
    avgSalaryMin: 38000,
    avgSalaryMax: 140000,
    growthRate: 22,
    automationRisk: "medium" as const,
    scalability: "high" as const,
    trend: "booming" as const,
    timeToAutonomy: "12-24 mesi con esperienza banking/tech",
    advantages: [
      "Settore ad alto valore",
      "Forte innovazione",
      "Stipendi competitivi",
      "Scalabilità dei prodotti",
    ],
    disadvantages: [
      "Regolamentazione forte",
      "Mercato sensibile a cicli economici",
      "Richiede precisione elevata",
    ],
    opportunities: ["Fintech Product Manager", "Blockchain Developer", "Risk Analyst", "ESG Finance Specialist", "Robo-advisor Specialist"],
    icon: "credit-card",
    color: "#8b5cf6",
  },
  {
    name: "Green Economy & Sostenibilità",
    description:
      "Rinnovabili, efficienza energetica, ESG, economia circolare e transizione ecologica. Settore strategico nel medio-lungo periodo con forte attenzione agli investimenti pubblici.",
    riasecTypes: ["R", "I", "S"],
    skills: ["Analisi energetica", "Normativa ESG", "Gestione progetti", "Sostenibilità", "Reporting ambientale"],
    avgSalaryMin: 30000,
    avgSalaryMax: 95000,
    growthRate: 20,
    automationRisk: "low" as const,
    scalability: "medium" as const,
    trend: "booming" as const,
    timeToAutonomy: "12-24 mesi con certificazioni green",
    advantages: [
      "Impatto reale e misurabile",
      "Supporto politico e finanziario",
      "Crescita di lungo periodo",
      "Alta coerenza etica",
    ],
    disadvantages: [
      "Dipendenza da incentivi e normative",
      "Mercato ancora disomogeneo",
      "Lunghi cicli decisionali",
    ],
    opportunities: ["Sustainability Manager", "ESG Consultant", "Energy Analyst", "Renewables Engineer", "Carbon Analyst"],
    icon: "leaf",
    color: "#22c55e",
  },
  {
    name: "Sanità & Healthcare Digitale",
    description:
      "Telemedicina, salute digitale, biotecnologie e servizi per il benessere. Settore ad alta rilevanza sociale con forte domanda e impatto su una società che invecchia.",
    riasecTypes: ["S", "I", "R"],
    skills: ["Empatia", "Conoscenze mediche", "Analisi clinica", "Comunicazione", "Gestione dati sanitari"],
    avgSalaryMin: 30000,
    avgSalaryMax: 150000,
    growthRate: 18,
    automationRisk: "low" as const,
    scalability: "medium" as const,
    trend: "growing" as const,
    timeToAutonomy: "3-6 anni (percorso formativo incluso)",
    advantages: [
      "Impatto sociale enorme",
      "Sicurezza occupazionale",
      "Varietà di specializzazioni",
      "Crescita costante",
    ],
    disadvantages: [
      "Formazione lunga e costosa",
      "Alto stress emotivo",
      "Regole forti e responsabilità",
    ],
    opportunities: ["Digital Health Specialist", "Telemedicine Coordinator", "Health Data Analyst", "Biotech PM", "Wellness Coach"],
    icon: "heart",
    color: "#ec4899",
  },
  {
    name: "Istruzione & Formazione",
    description:
      "Scuole, piattaforme educative, orientamento, tutoraggio e formazione aziendale. Per chi vuole trasmettere conoscenza e aiutare gli altri a crescere, anche in formato digitale e scalabile.",
    riasecTypes: ["S", "A", "E"],
    skills: ["Comunicazione", "Empatia", "Progettazione didattica", "Creatività", "Facilitazione"],
    avgSalaryMin: 22000,
    avgSalaryMax: 80000,
    growthRate: 14,
    automationRisk: "low" as const,
    scalability: "medium" as const,
    trend: "growing" as const,
    timeToAutonomy: "1-2 anni con certificazioni",
    advantages: [
      "Impatto duraturo sulle persone",
      "Alta stabilità lavorativa",
      "Varietà di contesti operativi",
      "Mercato edtech in espansione",
    ],
    disadvantages: [
      "Stipendi pubblici spesso bassi",
      "Alto investimento emotivo",
      "Budget spesso limitati",
    ],
    opportunities: ["Instructional Designer", "EdTech Specialist", "Career Advisor", "Training Manager", "Learning Experience Designer"],
    icon: "book-open",
    color: "#3b82f6",
  },
  {
    name: "Marketing & Growth",
    description:
      "Branding, advertising, crescita utenti, contenuti, social e performance marketing. Settore dinamico e creativo, altamente scalabile se collegato a prodotti digitali.",
    riasecTypes: ["A", "E", "S"],
    skills: ["Creatività", "Analisi dati", "Copywriting", "SEO/SEM", "Strategia di crescita"],
    avgSalaryMin: 25000,
    avgSalaryMax: 100000,
    growthRate: 16,
    automationRisk: "medium" as const,
    scalability: "high" as const,
    trend: "growing" as const,
    timeToAutonomy: "6-12 mesi con portfolio",
    advantages: [
      "Alta soddisfazione creativa",
      "Velocità di impatto",
      "Forte domanda nei prodotti digitali",
      "Possibilità freelance",
    ],
    disadvantages: [
      "Forte competizione",
      "Metriche in continuo cambiamento",
      "Rischio saturazione in alcuni ruoli",
    ],
    opportunities: ["Growth Marketer", "Brand Strategist", "Content Strategist", "Performance Marketer", "Demand Gen Specialist"],
    icon: "trending-up",
    color: "#f59e0b",
  },
  {
    name: "E-commerce & Retail Digitale",
    description:
      "Vendita online, marketplace, D2C, operations digitali e customer journey. Collega marketing, prodotto, logistica e dati in un ecosistema scalabile e misurabile.",
    riasecTypes: ["E", "A", "C"],
    skills: ["Gestione catalogo", "CRM", "Analytics e-commerce", "UX commerciale", "Logistica digitale"],
    avgSalaryMin: 25000,
    avgSalaryMax: 90000,
    growthRate: 15,
    automationRisk: "medium" as const,
    scalability: "high" as const,
    trend: "growing" as const,
    timeToAutonomy: "6-18 mesi con esperienza pratica",
    advantages: [
      "Settore comprensibile e concreto",
      "Alta scalabilità con automazione",
      "Misurabilità immediata dei risultati",
      "Accesso globale al mercato",
    ],
    disadvantages: [
      "Margini sotto pressione",
      "Dipendenza dalle piattaforme",
      "Forte competizione sui prezzi",
    ],
    opportunities: ["E-commerce Manager", "Marketplace Specialist", "CRO Specialist", "D2C Brand Manager", "Growth Operator"],
    icon: "shopping-bag",
    color: "#f97316",
  },
  {
    name: "Logistica & Supply Chain",
    description:
      "Magazzino evoluto, trasporti, operations e pianificazione. Settore centrale per l'economia reale, sempre più digitale e data-driven con l'industria 4.0.",
    riasecTypes: ["C", "R", "E"],
    skills: ["Pianificazione operativa", "Gestione scorte", "ERP", "Procurement", "Analisi costi"],
    avgSalaryMin: 28000,
    avgSalaryMax: 90000,
    growthRate: 12,
    automationRisk: "medium" as const,
    scalability: "medium" as const,
    trend: "growing" as const,
    timeToAutonomy: "1-2 anni con esperienza ops",
    advantages: [
      "Alta domanda nelle aziende manifatturiere",
      "Digitalizzazione rapida del settore",
      "Ruoli concreti e misurabili",
      "Trasversale a tutti i settori",
    ],
    disadvantages: [
      "Stress operativo elevato",
      "Coordinamento costante",
      "Margini ridotti in alcuni contesti",
    ],
    opportunities: ["Supply Chain Analyst", "Logistics Manager", "Operations Manager", "Warehouse Automation Specialist", "Demand Planner"],
    icon: "truck",
    color: "#64748b",
  },
  {
    name: "Ingegneria & Sistemi Tecnici",
    description:
      "Meccanica, elettrica, impiantistica, automazione e progettazione tecnica. Settore solido e tradizionalmente stabile, in evoluzione verso industria 4.0 e automazione avanzata.",
    riasecTypes: ["R", "I", "C"],
    skills: ["CAD/CAE", "Matematica applicata", "Analisi strutturale", "Problem solving tecnico", "Automazione"],
    avgSalaryMin: 32000,
    avgSalaryMax: 110000,
    growthRate: 11,
    automationRisk: "low" as const,
    scalability: "medium" as const,
    trend: "stable" as const,
    timeToAutonomy: "2-4 anni con laurea ingegneristica",
    advantages: [
      "Alta stabilità occupazionale",
      "Ruoli concreti e rispettati",
      "Export e internazionalizzazione",
      "Base per ruoli manageriali",
    ],
    disadvantages: [
      "Cicli lenti in alcuni comparti",
      "Richiede basi tecniche solide",
      "Aggiornamento costante",
    ],
    opportunities: ["Mechanical Engineer", "Automation Engineer", "Plant Engineer", "Systems Engineer", "Industrial Designer"],
    icon: "settings",
    color: "#78716c",
  },
  {
    name: "Turismo & Hospitality",
    description:
      "Ospitalità, viaggi, esperienze, luxury service e travel tech. Settore umano e relazionale con forte potenziale esperienziale, ma sensibile alla stagionalità.",
    riasecTypes: ["S", "A", "E"],
    skills: ["Customer service", "Lingue straniere", "Organizzazione eventi", "Revenue management", "Relazioni interpersonali"],
    avgSalaryMin: 22000,
    avgSalaryMax: 75000,
    growthRate: 13,
    automationRisk: "medium" as const,
    scalability: "medium" as const,
    trend: "growing" as const,
    timeToAutonomy: "6-12 mesi con esperienza diretta",
    advantages: [
      "Alta soddisfazione relazionale",
      "Varietà di contesti internazionali",
      "Settore in ripresa post-pandemia",
      "Esperienza e cultura",
    ],
    disadvantages: [
      "Forte stagionalità",
      "Dipendenza da geopolitica",
      "Orari spesso intensi",
    ],
    opportunities: ["Hospitality Manager", "Travel Designer", "Luxury Experience Curator", "Event Planner", "Tourism Consultant"],
    icon: "map-pin",
    color: "#06b6d4",
  },
  {
    name: "Consulenza & Strategia",
    description:
      "Consulenza direzionale, trasformazione aziendale, business strategy e operations. Palestra per carriera ad alto livello, richiede pensiero analitico e comunicazione forte.",
    riasecTypes: ["E", "I", "C"],
    skills: ["Pensiero analitico", "Comunicazione executive", "Problem solving strutturato", "Presentazioni", "Project management"],
    avgSalaryMin: 35000,
    avgSalaryMax: 200000,
    growthRate: 14,
    automationRisk: "low" as const,
    scalability: "high" as const,
    trend: "growing" as const,
    timeToAutonomy: "2-4 anni con esperienza Big4 o boutique",
    advantages: [
      "Alta visibilità strategica",
      "Network di alto livello",
      "Stipendi molto elevati",
      "Acceleratore di carriera",
    ],
    disadvantages: [
      "Pressione e orari intensi",
      "Alta competitività",
      "Frequenti trasferte",
    ],
    opportunities: ["Strategy Consultant", "Business Analyst", "Transformation Consultant", "Management Consultant", "Operations Consultant"],
    icon: "briefcase",
    color: "#1e293b",
  },
  {
    name: "Risorse Umane & People Operations",
    description:
      "Recruiting, talent acquisition, sviluppo persone e HR analytics. Settore in trasformazione digitale che richiede equilibrio tra dati e relazioni umane.",
    riasecTypes: ["S", "C", "E"],
    skills: ["Intervista e selezione", "Employer branding", "HR analytics", "Formazione interna", "Comunicazione empatica"],
    avgSalaryMin: 25000,
    avgSalaryMax: 85000,
    growthRate: 13,
    automationRisk: "medium" as const,
    scalability: "medium" as const,
    trend: "growing" as const,
    timeToAutonomy: "1-2 anni con esperienza recruiting",
    advantages: [
      "Lavoro con le persone",
      "Impatto diretto sulla cultura aziendale",
      "Sempre più data-driven",
      "Trasversale a tutti i settori",
    ],
    disadvantages: [
      "A volte sottovalutato",
      "Richiede alta sensibilità relazionale",
      "Equilibrio difficile tra empatia e KPI",
    ],
    opportunities: ["Recruiter", "Talent Acquisition Specialist", "HR Business Partner", "People Ops Specialist", "L&D Specialist"],
    icon: "users",
    color: "#a855f7",
  },
  {
    name: "Design & Creatività Digitale",
    description:
      "UX/UI, product design, brand, motion e contenuti digitali. Settore molto creativo che diventa scalabile se collegato a prodotto e tecnologia.",
    riasecTypes: ["A", "E", "I"],
    skills: ["Figma/Adobe", "UX Research", "Pensiero visivo", "Prototipazione", "Storytelling visivo"],
    avgSalaryMin: 25000,
    avgSalaryMax: 90000,
    growthRate: 15,
    automationRisk: "medium" as const,
    scalability: "high" as const,
    trend: "growing" as const,
    timeToAutonomy: "6-18 mesi con portfolio solido",
    advantages: [
      "Alta soddisfazione espressiva",
      "Possibilità freelance globale",
      "Settore in espansione digitale",
      "Creatività valorizzata",
    ],
    disadvantages: [
      "Forte competizione",
      "Rischio di svalutazione del lavoro",
      "Portfolio essenziale",
    ],
    opportunities: ["UX/UI Designer", "Product Designer", "Motion Designer", "Brand Designer", "Creative Strategist"],
    icon: "palette",
    color: "#f59e0b",
  },
  {
    name: "Immobiliare & Property",
    description:
      "Compravendita, gestione asset, proptech e investimenti immobiliari. Interessante per chi ama il mondo tangibile con competenze commerciali e patrimoniali.",
    riasecTypes: ["E", "C", "R"],
    skills: ["Negoziazione", "Valutazione immobiliare", "Diritto immobiliare", "Analisi mercato", "CRM commerciale"],
    avgSalaryMin: 25000,
    avgSalaryMax: 120000,
    growthRate: 9,
    automationRisk: "medium" as const,
    scalability: "medium" as const,
    trend: "stable" as const,
    timeToAutonomy: "1-2 anni con rete commerciale",
    advantages: [
      "Alta remunerazione su risultati",
      "Asset tangibili e comprensibili",
      "Buona autonomia professionale",
      "Mercato sempre attivo",
    ],
    disadvantages: [
      "Mercato ciclico",
      "Barriere economiche alte",
      "Dipendenza dai tassi di interesse",
    ],
    opportunities: ["Real Estate Advisor", "Property Manager", "Investment Analyst", "Leasing Specialist", "Proptech Specialist"],
    icon: "home",
    color: "#d97706",
  },
  {
    name: "Agroalimentare & Food Industry",
    description:
      "Produzione, qualità, export e innovazione alimentare. Settore centrale per l'Italia con stabilità, connessione all'identità territoriale e potenziale di internazionalizzazione.",
    riasecTypes: ["R", "C", "S"],
    skills: ["Controllo qualità", "Normativa alimentare", "Export management", "Supply chain food", "Innovazione di prodotto"],
    avgSalaryMin: 24000,
    avgSalaryMax: 80000,
    growthRate: 10,
    automationRisk: "medium" as const,
    scalability: "medium" as const,
    trend: "stable" as const,
    timeToAutonomy: "1-2 anni con specializzazione",
    advantages: [
      "Settore strategico per l'Italia",
      "Stabilità occupazionale",
      "Export in crescita",
      "Connessione con identità culturale",
    ],
    disadvantages: [
      "Filiera complessa",
      "Margini variabili",
      "Stagionalità in alcune funzioni",
    ],
    opportunities: ["Quality Manager", "Food Technologist", "Export Manager", "AgriTech Specialist", "Product Development Specialist"],
    icon: "wheat",
    color: "#84cc16",
  },
  {
    name: "Gaming & Esports",
    description:
      "Giochi digitali, community, competizioni, prodotti interattivi e intrattenimento. Settore creativo collegato a design, marketing e tecnologia con audience globale.",
    riasecTypes: ["A", "E", "I"],
    skills: ["Game design", "Programmazione Unity/Unreal", "Community management", "Monetizzazione", "Narrazione"],
    avgSalaryMin: 22000,
    avgSalaryMax: 90000,
    growthRate: 17,
    automationRisk: "low" as const,
    scalability: "high" as const,
    trend: "growing" as const,
    timeToAutonomy: "12-24 mesi con portfolio giochi",
    advantages: [
      "Settore appassionante",
      "Audience globale enorme",
      "Alta creatività richiesta",
      "Possibilità di indie e startup",
    ],
    disadvantages: [
      "Settore volatile",
      "Dipendenza da trend e pubblico",
      "Competizione internazionale alta",
    ],
    opportunities: ["Game Designer", "Game Developer", "Community Manager", "Esports Manager", "Monetization Specialist"],
    icon: "gamepad-2",
    color: "#7c3aed",
  },
  {
    name: "Legal Tech & Servizi Legali Digitali",
    description:
      "Automazione legale, documenti digitali, compliance e contract tech. Interessante per chi vuole combinare precisione normativa e tecnologia con grande efficienza.",
    riasecTypes: ["C", "I", "E"],
    skills: ["Diritto applicato", "Contract management", "Compliance", "Automazione documentale", "Privacy GDPR"],
    avgSalaryMin: 30000,
    avgSalaryMax: 110000,
    growthRate: 16,
    automationRisk: "medium" as const,
    scalability: "high" as const,
    trend: "growing" as const,
    timeToAutonomy: "2-3 anni con specializzazione legale/tech",
    advantages: [
      "Alta precisione valorizzata",
      "Automazione ad alto impatto",
      "Settore con pochi concorrenti",
      "Stipendi sopra la media legale",
    ],
    disadvantages: [
      "Complessità normativa",
      "Cambiamento lento in alcuni contesti",
      "Richiede doppia competenza",
    ],
    opportunities: ["Legal Operations Specialist", "Legal Tech Consultant", "Compliance Analyst", "Contract Manager", "Privacy Specialist"],
    icon: "scale",
    color: "#0f172a",
  },
  {
    name: "Biotech & Life Sciences",
    description:
      "Ricerca biologica, farmaceutica, genetica e diagnostica avanzata. Settore ad alta intensità di conoscenza con ottimo potenziale di lungo periodo per chi ama la ricerca.",
    riasecTypes: ["I", "C", "R"],
    skills: ["Biologia molecolare", "Analisi dati scientifici", "Gestione trial clinici", "Regulatory affairs", "Laboratorio"],
    avgSalaryMin: 30000,
    avgSalaryMax: 130000,
    growthRate: 19,
    automationRisk: "low" as const,
    scalability: "medium" as const,
    trend: "booming" as const,
    timeToAutonomy: "4-6 anni con laurea e specializzazione",
    advantages: [
      "Impatto sulla salute globale",
      "Alta specializzazione riconosciuta",
      "Settore in forte investimento",
      "Internazionalizzazione facile",
    ],
    disadvantages: [
      "Percorso formativo lungo",
      "Richiede rigore scientifico alto",
      "Cicli di ricerca molto lenti",
    ],
    opportunities: ["Biotech Researcher", "Lab Specialist", "Pharma Project Manager", "Clinical Data Specialist", "Genomics Analyst"],
    icon: "flask-conical",
    color: "#14b8a6",
  },
  {
    name: "Finanza & Investimenti",
    description:
      "Banca, finanza personale, trading, private equity e gestione patrimoniale. Per chi vuole operare nel mondo dei numeri e delle strategie finanziarie con alto potenziale di guadagno.",
    riasecTypes: ["C", "E", "I"],
    skills: ["Analisi quantitativa", "Gestione del rischio", "Excel e Bloomberg", "Comunicazione executive", "Disciplina"],
    avgSalaryMin: 35000,
    avgSalaryMax: 250000,
    growthRate: 10,
    automationRisk: "medium" as const,
    scalability: "high" as const,
    trend: "stable" as const,
    timeToAutonomy: "2-4 anni con certificazioni CFA/CFP",
    advantages: [
      "Stipendi molto elevati",
      "Trasferibilità internazionale",
      "Network esclusivi",
      "Sviluppo analitico avanzato",
    ],
    disadvantages: [
      "Alta pressione e lunghi orari",
      "Competizione per posizioni top",
      "Cultura aziendale spesso rigida",
    ],
    opportunities: ["Financial Analyst", "Investment Manager", "Portfolio Manager", "Fintech Advisor", "ESG Finance Specialist"],
    icon: "bar-chart",
    color: "#1d4ed8",
  },
];

const EXPECTED_COUNT = SECTORS.length;

export async function seedSectors() {
  const existing = await db.select().from(sectorsTable);

  if (existing.length >= EXPECTED_COUNT) return;

  if (existing.length > 0) {
    await db.delete(sectorsTable);
  }

  await db.insert(sectorsTable).values(SECTORS);
}
