import { Router, type IRouter } from "express";
import healthRouter from "./health";
import sectorsRouter from "./sectors";
import testSessionsRouter from "./testSessions";
import usersRouter from "./users";
import stripeRouter from "./stripe";
import newsRouter from "./news";
import authRouter from "./auth";
import authGoogleRouter from "./auth-google";
import profileRouter from "./profile";
import favoritesRouter from "./favorites";
import objectivesRouter from "./objectives";
import wikiRouter from "./wiki";
import roadmapRouter from "./roadmap";
import grafoRouter from "./grafo";
import knowledgeRouter from "./knowledge";
import sitemapRouter from "./sitemap";
import contactRouter from "./contact";
import ogRouter from "./og";
import ogImageRouter from "./og-image";
import affiliazioneRouter from "./affiliazione";
import crescitaRouter from "./crescita";
import cvRouter from "./cv";
import applicationsRouter from "./applications";
import remindersRouter from "./reminders";
import friendsRouter from "./friends";
import calendarRouter from "./calendar";
import notificationsRouter from "./notifications";
import pushRouter from "./push";
import meRouter from "./me";
import agentRouter from "./agent";
import aiAgentsRouter from "./ai-agents";
import catalogRouter from "./catalog";
import researchRouter from "./research";
import rolesRouter from "./roles";
import adminReviewRouter from "./admin-review";
import interviewRouter from "./interview";
import skillsGapRouter from "./skills-gap";
import coachRouter from "./coach";
import adminMetricsRouter from "./admin-metrics";
import adminPromptsRouter from "./admin-prompts";
import coverLetterRouter from "./cover-letter";
import completionRouter from "./completion";

const router: IRouter = Router();

router.use(authRouter);
router.use(authGoogleRouter);
router.use(profileRouter);
router.use(favoritesRouter);
router.use(objectivesRouter);
router.use(healthRouter);
router.use(sectorsRouter);
router.use(rolesRouter);
router.use(adminReviewRouter);
router.use(adminPromptsRouter);
router.use(testSessionsRouter);
router.use(usersRouter);
router.use(stripeRouter);
router.use(newsRouter);
router.use(wikiRouter);
router.use(roadmapRouter);
router.use(grafoRouter);
router.use(knowledgeRouter);
router.use(sitemapRouter);
router.use(contactRouter);
router.use(ogRouter);
router.use(ogImageRouter);
router.use(affiliazioneRouter);
router.use(crescitaRouter);
router.use(cvRouter);
router.use(applicationsRouter);
router.use(agentRouter);
router.use(aiAgentsRouter);
router.use(remindersRouter);
router.use(friendsRouter);
router.use(calendarRouter);
router.use(notificationsRouter);
router.use(pushRouter);
router.use(meRouter);
router.use(catalogRouter);
router.use(researchRouter);
router.use(interviewRouter);
router.use(skillsGapRouter);
router.use(coachRouter);
router.use(adminMetricsRouter);
router.use(coverLetterRouter);
router.use(completionRouter);

export default router;
