// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type CalendarAddEventReminderResponse struct {
	Reminder json.RawMessage `json:"reminder"`
}

type CalendarCreateEventResponse struct {
	Event json.RawMessage `json:"event"`
}

type CalendarDeleteEventResponse struct {
	Success bool `json:"success"`
}

type CalendarEvent struct {
	AllDay           bool            `json:"allDay"`
	Category         string          `json:"category"`
	Color            string          `json:"color"`
	CreatedAt        string          `json:"createdAt"`
	Description      string          `json:"description"`
	EndAt            string          `json:"endAt"`
	Id               int             `json:"id"`
	IsRecurring      bool            `json:"isRecurring"`
	LinkedContentIds json.RawMessage `json:"linkedContentIds"`
	LinkedGoal       string          `json:"linkedGoal"`
	LinkedSectorId   int             `json:"linkedSectorId"`
	Priority         string          `json:"priority"`
	RecurrenceRule   string          `json:"recurrenceRule"`
	Reminders        json.RawMessage `json:"reminders"`
	StartAt          string          `json:"startAt"`
	Status           string          `json:"status"`
	Tags             json.RawMessage `json:"tags"`
	Title            string          `json:"title"`
	UpdatedAt        string          `json:"updatedAt"`
	UserId           int             `json:"userId"`
}

type CalendarGetEventResponse struct {
	Event json.RawMessage `json:"event"`
}

type CalendarGetUpcomingEventsResponse struct {
	Events json.RawMessage `json:"events"`
}

type CalendarListEventsResponse struct {
	Events json.RawMessage `json:"events"`
}

type CalendarQuota struct {
	EventCount int  `json:"eventCount"`
	EventLimit int  `json:"eventLimit"`
	IsPremium  bool `json:"isPremium"`
}

type CalendarUpdateEventResponse struct {
	Event json.RawMessage `json:"event"`
}

type ConfirmSectorBody struct {
	SectorId int `json:"sectorId"`
}

type CreateCalendarEventBody struct {
	AllDay           bool            `json:"allDay"`
	Category         string          `json:"category"`
	Color            string          `json:"color"`
	Description      string          `json:"description"`
	EndAt            string          `json:"endAt"`
	IsRecurring      bool            `json:"isRecurring"`
	LinkedContentIds json.RawMessage `json:"linkedContentIds"`
	LinkedGoal       string          `json:"linkedGoal"`
	LinkedSectorId   int             `json:"linkedSectorId"`
	Priority         string          `json:"priority"`
	RecurrenceRule   string          `json:"recurrenceRule"`
	Reminders        json.RawMessage `json:"reminders"`
	StartAt          string          `json:"startAt"`
	Status           string          `json:"status"`
	Tags             json.RawMessage `json:"tags"`
	Title            string          `json:"title"`
}

type EducationPathSummary struct {
	CareerOutcomes json.RawMessage `json:"careerOutcomes"`
	Cost           string          `json:"cost"`
	Duration       string          `json:"duration"`
	Id             int             `json:"id"`
	Path           string          `json:"path"`
	Steps          json.RawMessage `json:"steps"`
	Type           string          `json:"type"`
}

type ErrorResponse struct {
	Code    string `json:"code"`
	Error   string `json:"error"`
	Message string `json:"message"`
}

type EventReminder struct {
	CreatedAt     string `json:"createdAt"`
	Enabled       bool   `json:"enabled"`
	EventId       int    `json:"eventId"`
	Id            int    `json:"id"`
	MinutesBefore int    `json:"minutesBefore"`
	SentAt        string `json:"sentAt"`
}

type HealthStatus struct {
	Status string `json:"status"`
}

type NotificationLog struct {
	Body     string `json:"body"`
	Channel  string `json:"channel"`
	EventId  int    `json:"eventId"`
	Id       int    `json:"id"`
	IsRead   bool   `json:"isRead"`
	OpenedAt string `json:"openedAt"`
	SentAt   string `json:"sentAt"`
	Title    string `json:"title"`
	UserId   int    `json:"userId"`
}

type NotificationsListResponse struct {
	Notifications json.RawMessage `json:"notifications"`
	UnreadCount   int             `json:"unreadCount"`
}

type PushSubscribeResponse struct {
	Success bool `json:"success"`
}

type PushUnsubscribeResponse struct {
	Success bool `json:"success"`
}

type RegisterUserBody struct {
	Email         string `json:"email"`
	Name          string `json:"name"`
	TestSessionId int    `json:"testSessionId"`
}

type RoleDetail struct {
	AutonomyScore  int             `json:"autonomyScore"`
	Description    string          `json:"description"`
	EducationPaths json.RawMessage `json:"educationPaths"`
	GrowthOutlook  string          `json:"growthOutlook"`
	Id             int             `json:"id"`
	RiasecFit      json.RawMessage `json:"riasecFit"`
	SalaryRange    string          `json:"salaryRange"`
	Sector         string          `json:"sector"`
	SectorId       int             `json:"sectorId"`
	SectorInfo     string          `json:"sectorInfo"`
	Skills         json.RawMessage `json:"skills"`
	StabilityScore int             `json:"stabilityScore"`
	Title          string          `json:"title"`
	WorkModes      json.RawMessage `json:"workModes"`
}

type RoleSummary struct {
	AutonomyScore  int             `json:"autonomyScore"`
	Description    string          `json:"description"`
	GrowthOutlook  string          `json:"growthOutlook"`
	Id             int             `json:"id"`
	RiasecFit      json.RawMessage `json:"riasecFit"`
	SalaryRange    string          `json:"salaryRange"`
	Skills         json.RawMessage `json:"skills"`
	StabilityScore int             `json:"stabilityScore"`
	Title          string          `json:"title"`
	WorkModes      json.RawMessage `json:"workModes"`
}

type Sector struct {
	Advantages     json.RawMessage `json:"advantages"`
	AutomationRisk string          `json:"automationRisk"`
	AvgSalaryMax   int             `json:"avgSalaryMax"`
	AvgSalaryMin   int             `json:"avgSalaryMin"`
	Color          string          `json:"color"`
	CreatedAt      string          `json:"createdAt"`
	Description    string          `json:"description"`
	Disadvantages  json.RawMessage `json:"disadvantages"`
	GrowthRate     float64         `json:"growthRate"`
	Icon           string          `json:"icon"`
	Id             int             `json:"id"`
	Name           string          `json:"name"`
	Opportunities  json.RawMessage `json:"opportunities"`
	RiasecTypes    json.RawMessage `json:"riasecTypes"`
	Scalability    string          `json:"scalability"`
	Skills         json.RawMessage `json:"skills"`
	TimeToAutonomy string          `json:"timeToAutonomy"`
	Trend          string          `json:"trend"`
}

type SectorInfo struct {
	Color string `json:"color"`
	Icon  string `json:"icon"`
	Id    int    `json:"id"`
	Name  string `json:"name"`
}

type SectorRecommendation struct {
	MatchReason string          `json:"matchReason"`
	MatchScore  float64         `json:"matchScore"`
	Sector      json.RawMessage `json:"sector"`
	SectorId    int             `json:"sectorId"`
	SectorName  string          `json:"sectorName"`
}

type SectorStats struct {
	AvgMatchScore    float64         `json:"avgMatchScore"`
	GrowthProjection json.RawMessage `json:"growthProjection"`
	SalaryRange      string          `json:"salaryRange"`
	SectorId         int             `json:"sectorId"`
	TimesPicked      int             `json:"timesPicked"`
}

type StatsSummary struct {
	AvgGrowthRate   float64         `json:"avgGrowthRate"`
	TopSectors      json.RawMessage `json:"topSectors"`
	TotalSectors    int             `json:"totalSectors"`
	TotalTestsTaken int             `json:"totalTestsTaken"`
}

type SubmitTestBody struct {
	Answers json.RawMessage `json:"answers"`
	Name    string          `json:"name"`
}

type TestSession struct {
	Answers           json.RawMessage `json:"answers"`
	ConfirmedSectorId int             `json:"confirmedSectorId"`
	CreatedAt         string          `json:"createdAt"`
	Id                int             `json:"id"`
	PrimaryTypes      json.RawMessage `json:"primaryTypes"`
	ProfileSummary    string          `json:"profileSummary"`
	Recommendations   json.RawMessage `json:"recommendations"`
	RiasecScores      json.RawMessage `json:"riasecScores"`
	UserId            int             `json:"userId"`
}

type UpdateCalendarEventBody struct {
	AllDay           bool            `json:"allDay"`
	Category         string          `json:"category"`
	Color            string          `json:"color"`
	Description      string          `json:"description"`
	EndAt            string          `json:"endAt"`
	LinkedContentIds json.RawMessage `json:"linkedContentIds"`
	LinkedGoal       string          `json:"linkedGoal"`
	LinkedSectorId   int             `json:"linkedSectorId"`
	Priority         string          `json:"priority"`
	Reminders        json.RawMessage `json:"reminders"`
	StartAt          string          `json:"startAt"`
	Status           string          `json:"status"`
	Tags             json.RawMessage `json:"tags"`
	Title            string          `json:"title"`
}

type User struct {
	CreatedAt     string `json:"createdAt"`
	Email         string `json:"email"`
	Id            int    `json:"id"`
	Name          string `json:"name"`
	TestSessionId int    `json:"testSessionId"`
}
