/**
 * wendy_optimizer_proposals
 * ─────────────────────────
 * Stores improvement proposals generated by the quality optimizer job.
 *
 * Each proposal has:
 *   type     — what kind of improvement is being proposed
 *   payload  — the actual change (new platitude pattern, threshold delta, etc.)
 *   status   — pending | approved | rejected
 *   evidence — metrics that triggered this proposal (JSON)
 *
 * Flow:
 *   1. quality-optimizer.ts runs daily and writes proposals here.
 *   2. Admin reviews via /admin/optimizer-proposals.
 *   3. On approve: the payload is applied (e.g. config override, pattern added).
 *   4. On reject: status updated, reason recorded.
 *
 * PRIVACY: no user content — only aggregate metrics and config values.
 */
import {
  pgTable, serial, text, jsonb, timestamp, integer, index,
} from "drizzle-orm/pg-core";
import { usersTable } from "./users";

export type OptimizerProposalType =
  | "platitude_pattern"      // add a new phrase to PLATITUDE_PATTERNS
  | "threshold_adjust"       // raise/lower router confidence threshold
  | "model_escalation"       // escalate to higher-tier model for a domain
  | "weight_adjust";         // adjust supervisor dimension weights

export type OptimizerProposalStatus = "pending" | "approved" | "rejected";

export const wendyOptimizerProposalsTable = pgTable(
  "wendy_optimizer_proposals",
  {
    id:          serial("id").primaryKey(),

    type:        text("type", {
                   enum: ["platitude_pattern", "threshold_adjust", "model_escalation", "weight_adjust"],
                 }).notNull(),

    // The proposed change — structure varies by type:
    // platitude_pattern: { pattern: string, examplePhrases: string[] }
    // threshold_adjust:  { domain: string, intent: string, delta: number, newValue: number }
    // model_escalation:  { domain: string, intent: string, currentTier: string, proposedTier: string }
    // weight_adjust:     { intent: string, dimension: string, delta: number }
    payload:     jsonb("payload").notNull(),

    // Aggregate metrics that triggered this proposal (read-only evidence)
    evidence:    jsonb("evidence"),

    status:      text("status", { enum: ["pending", "approved", "rejected"] })
                   .notNull()
                   .default("pending"),

    rejectionReason: text("rejection_reason"),

    proposedAt:  timestamp("proposed_at", { withTimezone: true }).notNull().defaultNow(),
    approvedAt:  timestamp("approved_at", { withTimezone: true }),
    approvedBy:  integer("approved_by")
                   .references(() => usersTable.id, { onDelete: "set null" }),
  },
  (t) => ({
    statusIdx:    index("wendy_optimizer_status_idx").on(t.status, t.proposedAt),
    typeIdx:      index("wendy_optimizer_type_idx").on(t.type),
  }),
);

export type WendyOptimizerProposal    = typeof wendyOptimizerProposalsTable.$inferSelect;
export type NewWendyOptimizerProposal = typeof wendyOptimizerProposalsTable.$inferInsert;
