// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAssistantsModifyCmd(flags *rootFlags) *cobra.Command {
	var bodyDescription string
	var bodyInstructions string
	var bodyMetadata string
	var bodyModel string
	var bodyName string
	var bodyReasoningEffort string
	var bodyResponseFormat string
	var bodyTemperature string
	var bodyToolResources string
	var bodyTools string
	var bodyTopP string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "modify <assistant_id>",
		Short:       "Modifies an assistant.",
		Example:     "  openai-pp-cli assistants modify 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "assistants.modify", "pp:method": "POST", "pp:path": "/assistants/{assistant_id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/assistants/{assistant_id}"
			path = replacePathParam(path, "assistant_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyInstructions != "" {
					body["instructions"] = bodyInstructions
				}
				if bodyMetadata != "" {
					body["metadata"] = bodyMetadata
				}
				if bodyModel != "" {
					body["model"] = bodyModel
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyReasoningEffort != "" {
					body["reasoning_effort"] = bodyReasoningEffort
				}
				if bodyResponseFormat != "" {
					body["response_format"] = bodyResponseFormat
				}
				if bodyTemperature != "" {
					body["temperature"] = bodyTemperature
				}
				if bodyToolResources != "" {
					body["tool_resources"] = bodyToolResources
				}
				if bodyTools != "" {
					var parsedTools any
					if err := json.Unmarshal([]byte(bodyTools), &parsedTools); err != nil {
						return fmt.Errorf("parsing --tools JSON: %w", err)
					}
					body["tools"] = parsedTools
				}
				if bodyTopP != "" {
					body["top_p"] = bodyTopP
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "assistants",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Description")
	cmd.Flags().StringVar(&bodyInstructions, "instructions", "", "Instructions")
	cmd.Flags().StringVar(&bodyMetadata, "metadata", "", "Metadata")
	cmd.Flags().StringVar(&bodyModel, "model", "", "ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your...")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name")
	cmd.Flags().StringVar(&bodyReasoningEffort, "reasoning-effort", "", "Reasoning effort")
	cmd.Flags().StringVar(&bodyResponseFormat, "response-format", "", "Response format")
	cmd.Flags().StringVar(&bodyTemperature, "temperature", "", "Temperature")
	cmd.Flags().StringVar(&bodyToolResources, "tool-resources", "", "Tool resources")
	cmd.Flags().StringVar(&bodyTools, "tools", "[]", "A list of tool enabled on the assistant. There can be a maximum of 128 tools per assistant. Tools can be of types...")
	cmd.Flags().StringVar(&bodyTopP, "top-p", "", "Top p")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
