// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAssistantsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "assistants",
		Short:  "Build Assistants that can call models and use tools.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAssistantsCreateCmd(flags))
	cmd.AddCommand(newAssistantsDeleteCmd(flags))
	cmd.AddCommand(newAssistantsGetCmd(flags))
	cmd.AddCommand(newAssistantsListCmd(flags))
	cmd.AddCommand(newAssistantsModifyCmd(flags))
	return cmd
}
