// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAudioCreateTranscriptionCmd(flags *rootFlags) *cobra.Command {
	var bodyChunkingStrategy string
	var bodyFile string
	var bodyInclude string
	var bodyKnownSpeakerNames string
	var bodyKnownSpeakerReferences string
	var bodyLanguage string
	var bodyModel string
	var bodyPrompt string
	var bodyResponseFormat string
	var bodyStream string
	var bodyTemperature float64
	var bodyTimestampGranularities string

	cmd := &cobra.Command{
		Use:         "create-transcription",
		Short:       "Transcribes audio into the input language. Returns a transcription object in `json`, `diarized_json`, or...",
		Example:     "  openai-pp-cli audio create-transcription --file example-value",
		Annotations: map[string]string{"pp:endpoint": "audio.create-transcription", "pp:method": "POST", "pp:path": "/audio/transcriptions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("file") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "file")
			}
			if !cmd.Flags().Changed("model") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "model")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/audio/transcriptions"
			fields := map[string]string{}
			fileFields := map[string]string{}
			if bodyChunkingStrategy != "" {
				fields["chunking_strategy"] = bodyChunkingStrategy
			}
			if bodyFile != "" {
				fileFields["file"] = bodyFile
			}
			if bodyInclude != "" {
				if !json.Valid([]byte(bodyInclude)) {
					return fmt.Errorf("parsing --include JSON: invalid JSON")
				}
				fields["include"] = bodyInclude
			}
			if bodyKnownSpeakerNames != "" {
				if !json.Valid([]byte(bodyKnownSpeakerNames)) {
					return fmt.Errorf("parsing --known-speaker-names JSON: invalid JSON")
				}
				fields["known_speaker_names"] = bodyKnownSpeakerNames
			}
			if bodyKnownSpeakerReferences != "" {
				if !json.Valid([]byte(bodyKnownSpeakerReferences)) {
					return fmt.Errorf("parsing --known-speaker-references JSON: invalid JSON")
				}
				fields["known_speaker_references"] = bodyKnownSpeakerReferences
			}
			if bodyLanguage != "" {
				fields["language"] = bodyLanguage
			}
			if bodyModel != "" {
				fields["model"] = bodyModel
			}
			if bodyPrompt != "" {
				fields["prompt"] = bodyPrompt
			}
			if bodyResponseFormat != "" {
				fields["response_format"] = bodyResponseFormat
			}
			if bodyStream != "" {
				fields["stream"] = bodyStream
			}
			if bodyTemperature != 0.0 {
				fields["temperature"] = fmt.Sprintf("%v", bodyTemperature)
			}
			if bodyTimestampGranularities != "" {
				if !json.Valid([]byte(bodyTimestampGranularities)) {
					return fmt.Errorf("parsing --timestamp-granularities JSON: invalid JSON")
				}
				fields["timestamp_granularities"] = bodyTimestampGranularities
			}

			data, statusCode, err := c.PostMultipart(path, fields, fileFields)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "audio",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyChunkingStrategy, "chunking-strategy", "", "Chunking strategy")
	cmd.Flags().StringVar(&bodyFile, "file", "", "The audio file object (not file name) to transcribe, in one of these formats: flac, mp3, mp4, mpeg, mpga, m4a, ogg,...")
	cmd.Flags().StringVar(&bodyInclude, "include", "", "Additional information to include in the transcription response. `logprobs` will return the log probabilities of the...")
	cmd.Flags().StringVar(&bodyKnownSpeakerNames, "known-speaker-names", "", "Optional list of speaker names that correspond to the audio samples provided in `known_speaker_references[]`. Each...")
	cmd.Flags().StringVar(&bodyKnownSpeakerReferences, "known-speaker-references", "", "Optional list of audio samples (as [data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_...")
	cmd.Flags().StringVar(&bodyLanguage, "language", "", "The language of the input audio. Supplying the input language in...")
	cmd.Flags().StringVar(&bodyModel, "model", "", "ID of the model to use. The options are `gpt-4o-transcribe`, `gpt-4o-mini-transcribe`,...")
	cmd.Flags().StringVar(&bodyPrompt, "prompt", "", "An optional text to guide the model's style or continue a previous audio segment. The...")
	cmd.Flags().StringVar(&bodyResponseFormat, "response-format", "json", "The format of the output, in one of these options: `json`, `text`, `srt`, `verbose_json`, `vtt`, or `diarized_json`....")
	cmd.Flags().StringVar(&bodyStream, "stream", "", "Stream")
	cmd.Flags().Float64Var(&bodyTemperature, "temperature", 0.000000, "The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower...")
	cmd.Flags().StringVar(&bodyTimestampGranularities, "timestamp-granularities", "[\"segment\"]", "The timestamp granularities to populate for this transcription. `response_format` must be set `verbose_json` to use...")

	return cmd
}
