// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAudioCreateSpeechCmd(flags *rootFlags) *cobra.Command {
	var bodyInput string
	var bodyInstructions string
	var bodyModel string
	var bodyResponseFormat string
	var bodySpeed float64
	var bodyStreamFormat string
	var bodyVoice string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-speech",
		Aliases:     []string{"create"},
		Short:       "Generates audio from the input text. Returns the audio file content, or a stream of audio events.",
		Example:     "  openai-pp-cli audio create-speech --input example-value",
		Annotations: map[string]string{"pp:endpoint": "audio.create-speech", "pp:method": "POST", "pp:path": "/audio/speech"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("input") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "input")
				}
				if !cmd.Flags().Changed("model") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "model")
				}
				if !cmd.Flags().Changed("voice") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "voice")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/audio/speech"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyInput != "" {
					body["input"] = bodyInput
				}
				if bodyInstructions != "" {
					body["instructions"] = bodyInstructions
				}
				if bodyModel != "" {
					body["model"] = bodyModel
				}
				if bodyResponseFormat != "" {
					body["response_format"] = bodyResponseFormat
				}
				if bodySpeed != 0.0 {
					body["speed"] = bodySpeed
				}
				if bodyStreamFormat != "" {
					body["stream_format"] = bodyStreamFormat
				}
				if bodyVoice != "" {
					body["voice"] = bodyVoice
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "audio",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyInput, "input", "", "The text to generate audio for. The maximum length is 4096 characters.")
	cmd.Flags().StringVar(&bodyInstructions, "instructions", "", "Control the voice of your generated audio with additional instructions. Does not work with `tts-1` or `tts-1-hd`.")
	cmd.Flags().StringVar(&bodyModel, "model", "", "One of the available [TTS models](/docs/models#tts): `tts-1`, `tts-1-hd`, `gpt-4o-mini-tts`, or...")
	cmd.Flags().StringVar(&bodyResponseFormat, "response-format", "mp3", "The format to audio in. Supported formats are `mp3`, `opus`, `aac`, `flac`, `wav`, and `pcm`.")
	cmd.Flags().Float64Var(&bodySpeed, "speed", 1.000000, "The speed of the generated audio. Select a value from `0.25` to `4.0`. `1.0` is the default.")
	cmd.Flags().StringVar(&bodyStreamFormat, "stream-format", "audio", "The format to stream the audio in. Supported formats are `sse` and `audio`. `sse` is not supported for `tts-1` or...")
	cmd.Flags().StringVar(&bodyVoice, "voice", "", "The voice to use when generating the audio. Supported built-in voices are `alloy`, `ash`, `ballad`, `coral`, `echo`,...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
