// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAudioCreateVoiceCmd(flags *rootFlags) *cobra.Command {
	var bodyAudioSample string
	var bodyConsent string
	var bodyName string

	cmd := &cobra.Command{
		Use:         "create-voice",
		Short:       "Create a custom voice you can use for audio output (for example, in Text-to-Speech and the Realtime API). This...",
		Example:     "  openai-pp-cli audio create-voice --audio-sample example-value",
		Annotations: map[string]string{"pp:endpoint": "audio.create-voice", "pp:method": "POST", "pp:path": "/audio/voices"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("audio-sample") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "audio-sample")
			}
			if !cmd.Flags().Changed("consent") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "consent")
			}
			if !cmd.Flags().Changed("name") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "name")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/audio/voices"
			fields := map[string]string{}
			fileFields := map[string]string{}
			if bodyAudioSample != "" {
				fileFields["audio_sample"] = bodyAudioSample
			}
			if bodyConsent != "" {
				fields["consent"] = bodyConsent
			}
			if bodyName != "" {
				fields["name"] = bodyName
			}

			data, statusCode, err := c.PostMultipart(path, fields, fileFields)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "audio",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAudioSample, "audio-sample", "", "The sample audio recording file. Maximum size is 10 MiB. Supported MIME types: `audio/mpeg`, `audio/wav`,...")
	cmd.Flags().StringVar(&bodyConsent, "consent", "", "The consent recording ID (for example, `cons_1234`).")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the new voice.")

	return cmd
}
