// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAudioCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "audio",
		Short:  "Turn audio into text or text into audio.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAudioCreateSpeechCmd(flags))
	cmd.AddCommand(newAudioCreateTranscriptionCmd(flags))
	cmd.AddCommand(newAudioCreateTranslationCmd(flags))
	cmd.AddCommand(newAudioCreateVoiceCmd(flags))
	cmd.AddCommand(newAudioCreateVoiceConsentCmd(flags))
	cmd.AddCommand(newAudioDeleteVoiceConsentCmd(flags))
	cmd.AddCommand(newAudioGetVoiceConsentCmd(flags))
	cmd.AddCommand(newAudioListVoiceConsentsCmd(flags))
	cmd.AddCommand(newAudioUpdateVoiceConsentCmd(flags))
	return cmd
}
