// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newBatchesCreateBatchCmd(flags *rootFlags) *cobra.Command {
	var bodyCompletionWindow string
	var bodyEndpoint string
	var bodyInputFileId string
	var bodyMetadata string
	var bodyOutputExpiresAfterAnchor string
	var bodyOutputExpiresAfterSeconds int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-batch",
		Aliases:     []string{"create"},
		Short:       "Creates and executes a batch from an uploaded file of requests",
		Example:     "  openai-pp-cli batches create-batch --completion-window example-value",
		Annotations: map[string]string{"pp:endpoint": "batches.create-batch", "pp:method": "POST", "pp:path": "/batches"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("completion-window") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "completion-window")
				}
				if !cmd.Flags().Changed("endpoint") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "endpoint")
				}
				if !cmd.Flags().Changed("input-file-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "input-file-id")
				}
				if !cmd.Flags().Changed("output-expires-after-anchor") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "output-expires-after-anchor")
				}
				if !cmd.Flags().Changed("output-expires-after-seconds") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "output-expires-after-seconds")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/batches"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyCompletionWindow != "" {
					body["completion_window"] = bodyCompletionWindow
				}
				if bodyEndpoint != "" {
					body["endpoint"] = bodyEndpoint
				}
				if bodyInputFileId != "" {
					body["input_file_id"] = bodyInputFileId
				}
				if bodyMetadata != "" {
					body["metadata"] = bodyMetadata
				}
				{
					nestedOutputExpiresAfter := map[string]any{}
					if bodyOutputExpiresAfterAnchor != "" {
						nestedOutputExpiresAfter["anchor"] = bodyOutputExpiresAfterAnchor
					}
					if bodyOutputExpiresAfterSeconds != 0 {
						nestedOutputExpiresAfter["seconds"] = bodyOutputExpiresAfterSeconds
					}
					if len(nestedOutputExpiresAfter) > 0 {
						body["output_expires_after"] = nestedOutputExpiresAfter
					}
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "batches",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyCompletionWindow, "completion-window", "", "The time frame within which the batch should be processed. Currently only `24h` is supported.")
	cmd.Flags().StringVar(&bodyEndpoint, "endpoint", "", "The endpoint to be used for all requests in the batch. Currently `/v1/responses`, `/v1/chat/completions`,...")
	cmd.Flags().StringVar(&bodyInputFileId, "input-file-id", "", "The ID of an uploaded file that contains requests for the new batch. See [upload...")
	cmd.Flags().StringVar(&bodyMetadata, "metadata", "", "Metadata")
	cmd.Flags().StringVar(&bodyOutputExpiresAfterAnchor, "output-expires-after-anchor", "", "Anchor timestamp after which the expiration policy applies. Supported anchors: `created_at`. Note that the anchor is...")
	cmd.Flags().IntVar(&bodyOutputExpiresAfterSeconds, "output-expires-after-seconds", 0, "The number of seconds after the anchor time that the file will expire. Must be between 3600 (1 hour) and 2592000 (30...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
