// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newChatkitListThreadsMethodCmd(flags *rootFlags) *cobra.Command {
	var flagLimit int
	var flagOrder string
	var flagAfter string
	var flagBefore string
	var flagUser string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list-threads-method",
		Aliases:     []string{"list"},
		Short:       "List ChatKit threads with optional pagination and user filters.",
		Example:     "  openai-pp-cli chatkit list-threads-method",
		Annotations: map[string]string{"pp:endpoint": "chatkit.list-threads-method", "pp:method": "GET", "pp:path": "/chatkit/threads", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("order") {
				allowedOrder := []string{"asc", "desc"}
				validOrder := false
				for _, v := range allowedOrder {
					if flagOrder == v {
						validOrder = true
						break
					}
				}
				if !validOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "order", flagOrder, allowedOrder)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/chatkit/threads"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "chatkit", path, map[string]string{
				"limit":  fmt.Sprintf("%v", flagLimit),
				"order":  fmt.Sprintf("%v", flagOrder),
				"after":  fmt.Sprintf("%v", flagAfter),
				"before": fmt.Sprintf("%v", flagBefore),
				"user":   fmt.Sprintf("%v", flagUser),
			}, nil, flagAll, "after", "", "has_more")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Maximum number of thread items to return. Defaults to 20.")
	cmd.Flags().StringVar(&flagOrder, "order", "", "Sort order for results by creation time. Defaults to `desc`. (one of: asc, desc)")
	cmd.Flags().StringVar(&flagAfter, "after", "", "List items created after this thread item ID. Defaults to null for the first page.")
	cmd.Flags().StringVar(&flagBefore, "before", "", "List items created before this thread item ID. Defaults to null for the newest results.")
	cmd.Flags().StringVar(&flagUser, "user", "", "Filter threads that belong to this user identifier. Defaults to null to return all users.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
