// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newChatCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "chat",
		Short:  "Given a list of messages comprising a conversation, the model will return a response.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newChatCreateCompletionCmd(flags))
	cmd.AddCommand(newChatDeleteCompletionCmd(flags))
	cmd.AddCommand(newChatGetCompletionCmd(flags))
	cmd.AddCommand(newChatGetCompletionMessagesCmd(flags))
	cmd.AddCommand(newChatListCompletionsCmd(flags))
	cmd.AddCommand(newChatUpdateCompletionCmd(flags))
	return cmd
}
