// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newChatkitCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "chatkit",
		Short:  "Manage chatkit",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newChatkitCancelChatSessionMethodCmd(flags))
	cmd.AddCommand(newChatkitCreateChatSessionMethodCmd(flags))
	cmd.AddCommand(newChatkitDeleteThreadMethodCmd(flags))
	cmd.AddCommand(newChatkitGetThreadMethodCmd(flags))
	cmd.AddCommand(newChatkitListThreadItemsMethodCmd(flags))
	cmd.AddCommand(newChatkitListThreadsMethodCmd(flags))
	return cmd
}
