// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newContainersCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyExpiresAfterAnchor string
	var bodyExpiresAfterMinutes int
	var bodyFileIds string
	var bodyMemoryLimit string
	var bodyName string
	var bodyNetworkPolicy string
	var bodySkills string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Creates a container.",
		Example:     "  openai-pp-cli containers create --name example-resource",
		Annotations: map[string]string{"pp:endpoint": "containers.create", "pp:method": "POST", "pp:path": "/containers"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("expires-after-anchor") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "expires-after-anchor")
				}
				if !cmd.Flags().Changed("expires-after-minutes") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "expires-after-minutes")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/containers"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedExpiresAfter := map[string]any{}
					if bodyExpiresAfterAnchor != "" {
						nestedExpiresAfter["anchor"] = bodyExpiresAfterAnchor
					}
					if bodyExpiresAfterMinutes != 0 {
						nestedExpiresAfter["minutes"] = bodyExpiresAfterMinutes
					}
					if len(nestedExpiresAfter) > 0 {
						body["expires_after"] = nestedExpiresAfter
					}
				}
				if bodyFileIds != "" {
					var parsedFileIds any
					if err := json.Unmarshal([]byte(bodyFileIds), &parsedFileIds); err != nil {
						return fmt.Errorf("parsing --file-ids JSON: %w", err)
					}
					body["file_ids"] = parsedFileIds
				}
				if bodyMemoryLimit != "" {
					body["memory_limit"] = bodyMemoryLimit
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyNetworkPolicy != "" {
					body["network_policy"] = bodyNetworkPolicy
				}
				if bodySkills != "" {
					var parsedSkills any
					if err := json.Unmarshal([]byte(bodySkills), &parsedSkills); err != nil {
						return fmt.Errorf("parsing --skills JSON: %w", err)
					}
					body["skills"] = parsedSkills
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "containers",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyExpiresAfterAnchor, "expires-after-anchor", "", "Time anchor for the expiration time. Currently only 'last_active_at' is supported.")
	cmd.Flags().IntVar(&bodyExpiresAfterMinutes, "expires-after-minutes", 0, "Minutes")
	cmd.Flags().StringVar(&bodyFileIds, "file-ids", "", "IDs of files to copy to the container.")
	cmd.Flags().StringVar(&bodyMemoryLimit, "memory-limit", "", "Optional memory limit for the container. Defaults to '1g'.")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name of the container to create.")
	cmd.Flags().StringVar(&bodyNetworkPolicy, "network-policy", "", "Network access policy for the container.")
	cmd.Flags().StringVar(&bodySkills, "skills", "", "An optional list of skills referenced by id or inline data.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
