// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newContainersFilesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "files",
		Short: "Files are used to upload documents that can be used with features like Assistants and Fine-tuning.",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newContainersFilesCreateContainerCmd(flags))
	cmd.AddCommand(newContainersFilesDeleteContainerCmd(flags))
	cmd.AddCommand(newContainersFilesListContainerCmd(flags))
	cmd.AddCommand(newContainersFilesRetrieveContainerCmd(flags))
	cmd.AddCommand(newContainersFilesRetrieveContainerContentCmd(flags))
	return cmd
}
