// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newConversationsItemsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "items",
		Short: "Manage items",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newConversationsItemsCreateConversationCmd(flags))
	cmd.AddCommand(newConversationsItemsDeleteConversationCmd(flags))
	cmd.AddCommand(newConversationsItemsGetConversationCmd(flags))
	cmd.AddCommand(newConversationsItemsListConversationCmd(flags))
	return cmd
}
