// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFineTuningCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "fine-tuning",
		Short:  "Manage fine-tuning jobs to tailor a model to your specific training data.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFineTuningCancelJobCmd(flags))
	cmd.AddCommand(newFineTuningCreateCheckpointPermissionCmd(flags))
	cmd.AddCommand(newFineTuningCreateJobCmd(flags))
	cmd.AddCommand(newFineTuningDeleteCheckpointPermissionCmd(flags))
	cmd.AddCommand(newFineTuningListCheckpointPermissionsCmd(flags))
	cmd.AddCommand(newFineTuningListEventsCmd(flags))
	cmd.AddCommand(newFineTuningListJobCheckpointsCmd(flags))
	cmd.AddCommand(newFineTuningListPaginatedJobsCmd(flags))
	cmd.AddCommand(newFineTuningPauseJobCmd(flags))
	cmd.AddCommand(newFineTuningResumeJobCmd(flags))
	cmd.AddCommand(newFineTuningRetrieveJobCmd(flags))
	cmd.AddCommand(newFineTuningRunGraderCmd(flags))
	cmd.AddCommand(newFineTuningValidateGraderCmd(flags))
	return cmd
}
