// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newFineTuningListPaginatedJobsCmd(flags *rootFlags) *cobra.Command {
	var flagAfter string
	var flagLimit int
	var flagMetadata string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list-paginated-jobs",
		Aliases:     []string{"list"},
		Short:       "List your organization's fine-tuning jobs",
		Example:     "  openai-pp-cli fine-tuning list-paginated-jobs",
		Annotations: map[string]string{"pp:endpoint": "fine-tuning.list-paginated-jobs", "pp:method": "GET", "pp:path": "/fine_tuning/jobs", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/fine_tuning/jobs"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "fine-tuning", path, map[string]string{
				"after":    fmt.Sprintf("%v", flagAfter),
				"limit":    fmt.Sprintf("%v", flagLimit),
				"metadata": fmt.Sprintf("%v", flagMetadata),
			}, nil, flagAll, "after", "", "has_more")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagAfter, "after", "", "Identifier for the last job from the previous pagination request.")
	cmd.Flags().IntVar(&flagLimit, "limit", 20, "Number of fine-tuning jobs to retrieve.")
	cmd.Flags().StringVar(&flagMetadata, "metadata", "", "Optional metadata filter. To filter, use the syntax `metadata[k]=v`. Alternatively, set `metadata=null` to indicate...")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
