// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newFineTuningRunGraderCmd(flags *rootFlags) *cobra.Command {
	var bodyGrader string
	var bodyItem string
	var bodyModelSample string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "run-grader",
		Short:       "Run a grader.",
		Example:     "  openai-pp-cli fine-tuning run-grader --model-sample example-value",
		Annotations: map[string]string{"pp:endpoint": "fine-tuning.run-grader", "pp:method": "POST", "pp:path": "/fine_tuning/alpha/graders/run"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("grader") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "grader")
				}
				if !cmd.Flags().Changed("model-sample") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "model-sample")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/fine_tuning/alpha/graders/run"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyGrader != "" {
					var parsedGrader any
					if err := json.Unmarshal([]byte(bodyGrader), &parsedGrader); err != nil {
						return fmt.Errorf("parsing --grader JSON: %w", err)
					}
					body["grader"] = parsedGrader
				}
				if bodyItem != "" {
					var parsedItem any
					if err := json.Unmarshal([]byte(bodyItem), &parsedItem); err != nil {
						return fmt.Errorf("parsing --item JSON: %w", err)
					}
					body["item"] = parsedItem
				}
				if bodyModelSample != "" {
					var parsedModelSample any
					if err := json.Unmarshal([]byte(bodyModelSample), &parsedModelSample); err != nil {
						return fmt.Errorf("parsing --model-sample JSON: %w", err)
					}
					body["model_sample"] = bodyModelSample
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "fine-tuning",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyGrader, "grader", "", "The grader used for the fine-tuning job.")
	cmd.Flags().StringVar(&bodyItem, "item", "", "The dataset item provided to the grader. This will be used to populate the `item` namespace. See [the...")
	cmd.Flags().StringVar(&bodyModelSample, "model-sample", "", "The model sample to be evaluated. This value will be used to populate the `sample` namespace. See [the...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
