// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newImagesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "images",
		Short:  "Given a prompt and/or an input image, the model will generate a new image.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newImagesCreateCmd(flags))
	cmd.AddCommand(newImagesCreateEditCmd(flags))
	cmd.AddCommand(newImagesCreateVariationCmd(flags))
	return cmd
}
