// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newImagesCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyBackground string
	var bodyModel string
	var bodyModeration string
	var bodyN int
	var bodyOutputCompression int
	var bodyOutputFormat string
	var bodyPartialImages string
	var bodyPrompt string
	var bodyQuality string
	var bodyResponseFormat string
	var bodySize string
	var bodyStream bool
	var bodyStyle string
	var bodyUser string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Creates an image given a prompt. [Learn more](/docs/guides/images).",
		Example:     "  openai-pp-cli images create --prompt example-value",
		Annotations: map[string]string{"pp:endpoint": "images.create", "pp:method": "POST", "pp:path": "/images/generations"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("prompt") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "prompt")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/images/generations"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyBackground != "" {
					body["background"] = bodyBackground
				}
				if bodyModel != "" {
					body["model"] = bodyModel
				}
				if bodyModeration != "" {
					body["moderation"] = bodyModeration
				}
				if bodyN != 0 {
					body["n"] = bodyN
				}
				if bodyOutputCompression != 0 {
					body["output_compression"] = bodyOutputCompression
				}
				if bodyOutputFormat != "" {
					body["output_format"] = bodyOutputFormat
				}
				if bodyPartialImages != "" {
					body["partial_images"] = bodyPartialImages
				}
				if bodyPrompt != "" {
					body["prompt"] = bodyPrompt
				}
				if bodyQuality != "" {
					body["quality"] = bodyQuality
				}
				if bodyResponseFormat != "" {
					body["response_format"] = bodyResponseFormat
				}
				if bodySize != "" {
					body["size"] = bodySize
				}
				if bodyStream != false {
					body["stream"] = bodyStream
				}
				if bodyStyle != "" {
					body["style"] = bodyStyle
				}
				if bodyUser != "" {
					body["user"] = bodyUser
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "images",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyBackground, "background", "auto", "Allows to set transparency for the background of the generated image(s). This parameter is only supported for the...")
	cmd.Flags().StringVar(&bodyModel, "model", "dall-e-2", "The model to use for image generation. One of `dall-e-2`, `dall-e-3`, or a GPT image model (`gpt-image-1`,...")
	cmd.Flags().StringVar(&bodyModeration, "moderation", "auto", "Control the content-moderation level for images generated by the GPT image models. Must be either `low` for less...")
	cmd.Flags().IntVar(&bodyN, "n", 1, "The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only `n=1` is supported.")
	cmd.Flags().IntVar(&bodyOutputCompression, "output-compression", 100, "The compression level (0-100%) for the generated images. This parameter is only supported for the GPT image models...")
	cmd.Flags().StringVar(&bodyOutputFormat, "output-format", "png", "The format in which the generated images are returned. This parameter is only supported for the GPT image models....")
	cmd.Flags().StringVar(&bodyPartialImages, "partial-images", "", "Partial images")
	cmd.Flags().StringVar(&bodyPrompt, "prompt", "", "A text description of the desired image(s). The maximum length is 32000 characters for the GPT image models, 1000...")
	cmd.Flags().StringVar(&bodyQuality, "quality", "auto", "The quality of the image that will be generated. - `auto` (default value) will automatically select the best quality...")
	cmd.Flags().StringVar(&bodyResponseFormat, "response-format", "url", "The format in which generated images with `dall-e-2` and `dall-e-3` are returned. Must be one of `url` or...")
	cmd.Flags().StringVar(&bodySize, "size", "auto", "The size of the generated images. For `gpt-image-2` and `gpt-image-2-2026-04-21`, arbitrary resolutions are...")
	cmd.Flags().BoolVar(&bodyStream, "stream", false, "Generate the image in streaming mode. Defaults to `false`. See the [Image generation...")
	cmd.Flags().StringVar(&bodyStyle, "style", "vivid", "The style of the generated images. This parameter is only supported for `dall-e-3`. Must be one of `vivid` or...")
	cmd.Flags().StringVar(&bodyUser, "user", "", "A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
