// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newImagesCreateEditCmd(flags *rootFlags) *cobra.Command {
	var bodyBackground string
	var bodyImages string
	var bodyInputFidelity string
	var bodyMaskFileId string
	var bodyMaskImageUrl string
	var bodyModel string
	var bodyModeration string
	var bodyN string
	var bodyOutputCompression string
	var bodyOutputFormat string
	var bodyPartialImages string
	var bodyPrompt string
	var bodyQuality string
	var bodySize string
	var bodyStream string
	var bodyUser string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-edit",
		Short:       "You can call this endpoint with either: - `multipart/form-data`: use binary uploads via `image` (and optional...",
		Example:     "  openai-pp-cli images create-edit --prompt example-value",
		Annotations: map[string]string{"pp:endpoint": "images.create-edit", "pp:method": "POST", "pp:path": "/images/edits"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("images") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "images")
				}
				if !cmd.Flags().Changed("prompt") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "prompt")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/images/edits"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyBackground != "" {
					body["background"] = bodyBackground
				}
				if bodyImages != "" {
					var parsedImages any
					if err := json.Unmarshal([]byte(bodyImages), &parsedImages); err != nil {
						return fmt.Errorf("parsing --images JSON: %w", err)
					}
					body["images"] = parsedImages
				}
				if bodyInputFidelity != "" {
					body["input_fidelity"] = bodyInputFidelity
				}
				{
					nestedMask := map[string]any{}
					if bodyMaskFileId != "" {
						nestedMask["file_id"] = bodyMaskFileId
					}
					if bodyMaskImageUrl != "" {
						nestedMask["image_url"] = bodyMaskImageUrl
					}
					if len(nestedMask) > 0 {
						body["mask"] = nestedMask
					}
				}
				if bodyModel != "" {
					body["model"] = bodyModel
				}
				if bodyModeration != "" {
					body["moderation"] = bodyModeration
				}
				if bodyN != "" {
					body["n"] = bodyN
				}
				if bodyOutputCompression != "" {
					body["output_compression"] = bodyOutputCompression
				}
				if bodyOutputFormat != "" {
					body["output_format"] = bodyOutputFormat
				}
				if bodyPartialImages != "" {
					body["partial_images"] = bodyPartialImages
				}
				if bodyPrompt != "" {
					body["prompt"] = bodyPrompt
				}
				if bodyQuality != "" {
					body["quality"] = bodyQuality
				}
				if bodySize != "" {
					body["size"] = bodySize
				}
				if bodyStream != "" {
					body["stream"] = bodyStream
				}
				if bodyUser != "" {
					body["user"] = bodyUser
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "images",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyBackground, "background", "auto", "Background behavior for generated image output.")
	cmd.Flags().StringVar(&bodyImages, "images", "", "Input image references to edit. For GPT image models, you can provide up to 16 images.")
	cmd.Flags().StringVar(&bodyInputFidelity, "input-fidelity", "", "Controls fidelity to the original input image(s).")
	cmd.Flags().StringVar(&bodyMaskFileId, "mask-file-id", "", "The File API ID of an uploaded image to use as input.")
	cmd.Flags().StringVar(&bodyMaskImageUrl, "mask-image-url", "", "A fully qualified URL or base64-encoded data URL.")
	cmd.Flags().StringVar(&bodyModel, "model", "gpt-image-1.5", "The model to use for image editing.")
	cmd.Flags().StringVar(&bodyModeration, "moderation", "auto", "Moderation level for GPT image models.")
	cmd.Flags().StringVar(&bodyN, "n", "1", "The number of edited images to generate.")
	cmd.Flags().StringVar(&bodyOutputCompression, "output-compression", "", "Compression level for `jpeg` or `webp` output.")
	cmd.Flags().StringVar(&bodyOutputFormat, "output-format", "png", "Output image format. Supported for GPT image models.")
	cmd.Flags().StringVar(&bodyPartialImages, "partial-images", "", "Partial images")
	cmd.Flags().StringVar(&bodyPrompt, "prompt", "", "A text description of the desired image edit.")
	cmd.Flags().StringVar(&bodyQuality, "quality", "auto", "Output quality for GPT image models.")
	cmd.Flags().StringVar(&bodySize, "size", "auto", "Requested output image size.")
	cmd.Flags().StringVar(&bodyStream, "stream", "false", "Stream partial image results as events.")
	cmd.Flags().StringVar(&bodyUser, "user", "", "A unique identifier representing your end-user, which can help OpenAI monitor and detect abuse.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
