// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newImagesCreateVariationCmd(flags *rootFlags) *cobra.Command {
	var bodyImage string
	var bodyModel string
	var bodyN int
	var bodyResponseFormat string
	var bodySize string
	var bodyUser string

	cmd := &cobra.Command{
		Use:         "create-variation",
		Short:       "Creates a variation of a given image. This endpoint only supports `dall-e-2`.",
		Example:     "  openai-pp-cli images create-variation --image example-value",
		Annotations: map[string]string{"pp:endpoint": "images.create-variation", "pp:method": "POST", "pp:path": "/images/variations"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("image") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "image")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/images/variations"
			fields := map[string]string{}
			fileFields := map[string]string{}
			if bodyImage != "" {
				fileFields["image"] = bodyImage
			}
			if bodyModel != "" {
				fields["model"] = bodyModel
			}
			if bodyN != 0 {
				fields["n"] = fmt.Sprintf("%v", bodyN)
			}
			if bodyResponseFormat != "" {
				fields["response_format"] = bodyResponseFormat
			}
			if bodySize != "" {
				fields["size"] = bodySize
			}
			if bodyUser != "" {
				fields["user"] = bodyUser
			}

			data, statusCode, err := c.PostMultipart(path, fields, fileFields)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "images",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyImage, "image", "", "The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square.")
	cmd.Flags().StringVar(&bodyModel, "model", "dall-e-2", "The model to use for image generation. Only `dall-e-2` is supported at this time.")
	cmd.Flags().IntVar(&bodyN, "n", 1, "The number of images to generate. Must be between 1 and 10.")
	cmd.Flags().StringVar(&bodyResponseFormat, "response-format", "url", "The format in which the generated images are returned. Must be one of `url` or `b64_json`. URLs are only valid for...")
	cmd.Flags().StringVar(&bodySize, "size", "1024x1024", "The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.")
	cmd.Flags().StringVar(&bodyUser, "user", "", "A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn...")

	return cmd
}
