// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newModelsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "models",
		Short:  "List and describe the various models available in the API.",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newModelsDeleteCmd(flags))
	cmd.AddCommand(newModelsListCmd(flags))
	cmd.AddCommand(newModelsRetrieveCmd(flags))
	return cmd
}
