// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newOrganizationListProjectsCmd(flags *rootFlags) *cobra.Command {
	var flagLimit int
	var flagAfter string
	var flagIncludeArchived bool
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list-projects",
		Short:       "Returns a list of projects.",
		Example:     "  openai-pp-cli organization list-projects",
		Annotations: map[string]string{"pp:endpoint": "organization.list-projects", "pp:method": "GET", "pp:path": "/organization/projects", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organization/projects"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "organization", path, map[string]string{
				"limit":            fmt.Sprintf("%v", flagLimit),
				"after":            fmt.Sprintf("%v", flagAfter),
				"include_archived": fmt.Sprintf("%v", flagIncludeArchived),
			}, nil, flagAll, "after", "", "has_more")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagLimit, "limit", 20, "A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.")
	cmd.Flags().StringVar(&flagAfter, "after", "", "A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you...")
	cmd.Flags().BoolVar(&flagIncludeArchived, "include-archived", false, "If `true` returns all projects including those that have been `archived`. Archived projects are not included by default.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
