// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newOrganizationUpdateProjectRateLimitsCmd(flags *rootFlags) *cobra.Command {
	var bodyBatch1DayMaxInputTokens int
	var bodyMaxAudioMegabytesPer1Minute int
	var bodyMaxImagesPer1Minute int
	var bodyMaxRequestsPer1Day int
	var bodyMaxRequestsPer1Minute int
	var bodyMaxTokensPer1Minute int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update-project-rate-limits <project_id> <rate_limit_id>",
		Short:       "Updates a project rate limit.",
		Example:     "  openai-pp-cli organization update-project-rate-limits 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "organization.update-project-rate-limits", "pp:method": "POST", "pp:path": "/organization/projects/{project_id}/rate_limits/{rate_limit_id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organization/projects/{project_id}/rate_limits/{rate_limit_id}"
			path = replacePathParam(path, "project_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("rate_limit_id is required\nUsage: %s <%s>", cmd.CommandPath(), "rate_limit_id"))
			}
			path = replacePathParam(path, "rate_limit_id", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyBatch1DayMaxInputTokens != 0 {
					body["batch_1_day_max_input_tokens"] = bodyBatch1DayMaxInputTokens
				}
				if bodyMaxAudioMegabytesPer1Minute != 0 {
					body["max_audio_megabytes_per_1_minute"] = bodyMaxAudioMegabytesPer1Minute
				}
				if bodyMaxImagesPer1Minute != 0 {
					body["max_images_per_1_minute"] = bodyMaxImagesPer1Minute
				}
				if bodyMaxRequestsPer1Day != 0 {
					body["max_requests_per_1_day"] = bodyMaxRequestsPer1Day
				}
				if bodyMaxRequestsPer1Minute != 0 {
					body["max_requests_per_1_minute"] = bodyMaxRequestsPer1Minute
				}
				if bodyMaxTokensPer1Minute != 0 {
					body["max_tokens_per_1_minute"] = bodyMaxTokensPer1Minute
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "organization",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&bodyBatch1DayMaxInputTokens, "batch-1-day-max-input-tokens", 0, "The maximum batch input tokens per day. Only relevant for certain models.")
	cmd.Flags().IntVar(&bodyMaxAudioMegabytesPer1Minute, "max-audio-megabytes-per-1-minute", 0, "The maximum audio megabytes per minute. Only relevant for certain models.")
	cmd.Flags().IntVar(&bodyMaxImagesPer1Minute, "max-images-per-1-minute", 0, "The maximum images per minute. Only relevant for certain models.")
	cmd.Flags().IntVar(&bodyMaxRequestsPer1Day, "max-requests-per-1-day", 0, "The maximum requests per day. Only relevant for certain models.")
	cmd.Flags().IntVar(&bodyMaxRequestsPer1Minute, "max-requests-per-1-minute", 0, "The maximum requests per minute.")
	cmd.Flags().IntVar(&bodyMaxTokensPer1Minute, "max-tokens-per-1-minute", 0, "The maximum tokens per minute.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
