// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrganizationCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "organization",
		Short:  "Manage organization",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOrganizationActivateCertificatesCmd(flags))
	cmd.AddCommand(newOrganizationActivateProjectCertificatesCmd(flags))
	cmd.AddCommand(newOrganizationAddGroupUserCmd(flags))
	cmd.AddCommand(newOrganizationAddProjectGroupCmd(flags))
	cmd.AddCommand(newOrganizationAdminApiKeysCreateCmd(flags))
	cmd.AddCommand(newOrganizationAdminApiKeysDeleteCmd(flags))
	cmd.AddCommand(newOrganizationAdminApiKeysGetCmd(flags))
	cmd.AddCommand(newOrganizationAdminApiKeysListCmd(flags))
	cmd.AddCommand(newOrganizationArchiveProjectCmd(flags))
	cmd.AddCommand(newOrganizationAssignGroupRoleCmd(flags))
	cmd.AddCommand(newOrganizationAssignUserRoleCmd(flags))
	cmd.AddCommand(newOrganizationCreateGroupCmd(flags))
	cmd.AddCommand(newOrganizationCreateProjectCmd(flags))
	cmd.AddCommand(newOrganizationCreateProjectServiceAccountCmd(flags))
	cmd.AddCommand(newOrganizationCreateProjectUserCmd(flags))
	cmd.AddCommand(newOrganizationCreateRoleCmd(flags))
	cmd.AddCommand(newOrganizationDeactivateCertificatesCmd(flags))
	cmd.AddCommand(newOrganizationDeactivateProjectCertificatesCmd(flags))
	cmd.AddCommand(newOrganizationDeleteCertificateCmd(flags))
	cmd.AddCommand(newOrganizationDeleteGroupCmd(flags))
	cmd.AddCommand(newOrganizationDeleteInviteCmd(flags))
	cmd.AddCommand(newOrganizationDeleteProjectApiKeyCmd(flags))
	cmd.AddCommand(newOrganizationDeleteProjectServiceAccountCmd(flags))
	cmd.AddCommand(newOrganizationDeleteProjectUserCmd(flags))
	cmd.AddCommand(newOrganizationDeleteRoleCmd(flags))
	cmd.AddCommand(newOrganizationDeleteUserCmd(flags))
	cmd.AddCommand(newOrganizationGetCertificateCmd(flags))
	cmd.AddCommand(newOrganizationInviteUserCmd(flags))
	cmd.AddCommand(newOrganizationListAuditLogsCmd(flags))
	cmd.AddCommand(newOrganizationListCertificatesCmd(flags))
	cmd.AddCommand(newOrganizationListGroupRoleAssignmentsCmd(flags))
	cmd.AddCommand(newOrganizationListGroupUsersCmd(flags))
	cmd.AddCommand(newOrganizationListGroupsCmd(flags))
	cmd.AddCommand(newOrganizationListInvitesCmd(flags))
	cmd.AddCommand(newOrganizationListProjectApiKeysCmd(flags))
	cmd.AddCommand(newOrganizationListProjectCertificatesCmd(flags))
	cmd.AddCommand(newOrganizationListProjectGroupsCmd(flags))
	cmd.AddCommand(newOrganizationListProjectRateLimitsCmd(flags))
	cmd.AddCommand(newOrganizationListProjectServiceAccountsCmd(flags))
	cmd.AddCommand(newOrganizationListProjectUsersCmd(flags))
	cmd.AddCommand(newOrganizationListProjectsCmd(flags))
	cmd.AddCommand(newOrganizationListRolesCmd(flags))
	cmd.AddCommand(newOrganizationListUserRoleAssignmentsCmd(flags))
	cmd.AddCommand(newOrganizationListUsersCmd(flags))
	cmd.AddCommand(newOrganizationModifyCertificateCmd(flags))
	cmd.AddCommand(newOrganizationModifyProjectCmd(flags))
	cmd.AddCommand(newOrganizationModifyProjectUserCmd(flags))
	cmd.AddCommand(newOrganizationModifyUserCmd(flags))
	cmd.AddCommand(newOrganizationRemoveGroupUserCmd(flags))
	cmd.AddCommand(newOrganizationRemoveProjectGroupCmd(flags))
	cmd.AddCommand(newOrganizationRetrieveInviteCmd(flags))
	cmd.AddCommand(newOrganizationRetrieveProjectCmd(flags))
	cmd.AddCommand(newOrganizationRetrieveProjectApiKeyCmd(flags))
	cmd.AddCommand(newOrganizationRetrieveProjectServiceAccountCmd(flags))
	cmd.AddCommand(newOrganizationRetrieveProjectUserCmd(flags))
	cmd.AddCommand(newOrganizationRetrieveUserCmd(flags))
	cmd.AddCommand(newOrganizationUnassignGroupRoleCmd(flags))
	cmd.AddCommand(newOrganizationUnassignUserRoleCmd(flags))
	cmd.AddCommand(newOrganizationUpdateGroupCmd(flags))
	cmd.AddCommand(newOrganizationUpdateProjectRateLimitsCmd(flags))
	cmd.AddCommand(newOrganizationUpdateRoleCmd(flags))
	cmd.AddCommand(newOrganizationUploadCertificateCmd(flags))
	cmd.AddCommand(newOrganizationUsageAudioSpeechesCmd(flags))
	cmd.AddCommand(newOrganizationUsageAudioTranscriptionsCmd(flags))
	cmd.AddCommand(newOrganizationUsageCodeInterpreterSessionsCmd(flags))
	cmd.AddCommand(newOrganizationUsageCompletionsCmd(flags))
	cmd.AddCommand(newOrganizationUsageCostsCmd(flags))
	cmd.AddCommand(newOrganizationUsageEmbeddingsCmd(flags))
	cmd.AddCommand(newOrganizationUsageImagesCmd(flags))
	cmd.AddCommand(newOrganizationUsageModerationsCmd(flags))
	cmd.AddCommand(newOrganizationUsageVectorStoresCmd(flags))
	return cmd
}
