// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "projects",
		Short:  "Manage projects",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectsGroupsCmd(flags))
	cmd.AddCommand(newProjectsRolesCmd(flags))
	cmd.AddCommand(newProjectsUsersCmd(flags))
	return cmd
}
