// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectsGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "groups",
		Short: "Manage groups",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectsGroupsAssignProjectRoleCmd(flags))
	cmd.AddCommand(newProjectsGroupsListProjectRoleAssignmentsCmd(flags))
	cmd.AddCommand(newProjectsGroupsUnassignProjectRoleCmd(flags))
	return cmd
}
