// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectsUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "users",
		Short: "Manage users",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectsUsersAssignProjectRoleCmd(flags))
	cmd.AddCommand(newProjectsUsersListProjectRoleAssignmentsCmd(flags))
	cmd.AddCommand(newProjectsUsersUnassignProjectRoleCmd(flags))
	return cmd
}
