// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newUploadsPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyBytes int
	var bodyExpiresAfterAnchor string
	var bodyExpiresAfterSeconds int
	var bodyFilename string
	var bodyMimeType string
	var bodyPurpose string

	cmd := &cobra.Command{
		Use:         "uploads",
		Short:       "Creates an intermediate [Upload](/docs/api-reference/uploads/object) object that you can add...",
		Long:        "Shortcut for 'uploads create'. Creates an intermediate [Upload](/docs/api-reference/uploads/object) object that you can add...",
		Example:     "  openai-pp-cli uploads --filename example-resource",
		Annotations: map[string]string{"pp:endpoint": "uploads.create", "pp:method": "POST", "pp:path": "/uploads"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("bytes") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "bytes")
			}
			if !cmd.Flags().Changed("expires-after-anchor") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "expires-after-anchor")
			}
			if !cmd.Flags().Changed("expires-after-seconds") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "expires-after-seconds")
			}
			if !cmd.Flags().Changed("filename") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "filename")
			}
			if !cmd.Flags().Changed("mime-type") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "mime-type")
			}
			if !cmd.Flags().Changed("purpose") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "purpose")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/uploads"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyBytes != 0 {
				body["bytes"] = bodyBytes
			}
			{
				nestedExpiresAfter := map[string]any{}
				if bodyExpiresAfterAnchor != "" {
					nestedExpiresAfter["anchor"] = bodyExpiresAfterAnchor
				}
				if bodyExpiresAfterSeconds != 0 {
					nestedExpiresAfter["seconds"] = bodyExpiresAfterSeconds
				}
				if len(nestedExpiresAfter) > 0 {
					body["expires_after"] = nestedExpiresAfter
				}
			}
			if bodyFilename != "" {
				body["filename"] = bodyFilename
			}
			if bodyMimeType != "" {
				body["mime_type"] = bodyMimeType
			}
			if bodyPurpose != "" {
				body["purpose"] = bodyPurpose
			}
			data, _, err := c.Post(path, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&bodyBytes, "bytes", 0, "The number of bytes in the file you are uploading.")
	cmd.Flags().StringVar(&bodyExpiresAfterAnchor, "expires-after-anchor", "", "Anchor timestamp after which the expiration policy applies. Supported anchors: `created_at`.")
	cmd.Flags().IntVar(&bodyExpiresAfterSeconds, "expires-after-seconds", 0, "The number of seconds after the anchor time that the file will expire. Must be between 3600 (1 hour) and 2592000 (30...")
	cmd.Flags().StringVar(&bodyFilename, "filename", "", "The name of the file to upload.")
	cmd.Flags().StringVar(&bodyMimeType, "mime-type", "", "The MIME type of the file. This must fall within the supported MIME types for your file purpose. See the supported...")
	cmd.Flags().StringVar(&bodyPurpose, "purpose", "", "The intended purpose of the uploaded file. See the [documentation on File...")

	// Wire sibling endpoints and sub-resources as subcommands
	{
		sub := newUploadsCancelCmd(flags)
		sub.Hidden = false // unhide: the raw parent is hidden but these are useful under the promoted command
		cmd.AddCommand(sub)
	}
	{
		sub := newUploadsCompleteCmd(flags)
		sub.Hidden = false // unhide: the raw parent is hidden but these are useful under the promoted command
		cmd.AddCommand(sub)
	}
	{
		sub := newUploadsPartsCmd(flags)
		sub.Hidden = false // unhide: the raw parent is hidden but these are useful under the promoted command
		cmd.AddCommand(sub)
	}

	return cmd
}
