// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCompletionsPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyBestOf int
	var bodyEcho bool
	var bodyFrequencyPenalty float64
	var bodyLogitBias string
	var bodyLogprobs int
	var bodyMaxTokens int
	var bodyModel string
	var bodyN int
	var bodyPresencePenalty float64
	var bodyPrompt string
	var bodySeed int
	var bodyStop string
	var bodyStream bool
	var bodyStreamOptions string
	var bodySuffix string
	var bodyTemperature float64
	var bodyTopP float64
	var bodyUser string

	cmd := &cobra.Command{
		Use:         "completions",
		Short:       "Creates a completion for the provided prompt and parameters. Returns a completion object, or a sequence of...",
		Long:        "Shortcut for 'completions create'. Creates a completion for the provided prompt and parameters. Returns a completion object, or a sequence of...",
		Example:     "  openai-pp-cli completions --model example-value",
		Annotations: map[string]string{"pp:endpoint": "completions.create", "pp:method": "POST", "pp:path": "/completions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("model") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "model")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/completions"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyBestOf != 0 {
				body["best_of"] = bodyBestOf
			}
			if bodyEcho != false {
				body["echo"] = bodyEcho
			}
			if bodyFrequencyPenalty != 0.0 {
				body["frequency_penalty"] = bodyFrequencyPenalty
			}
			if bodyLogitBias != "" {
				var parsedLogitBias any
				if err := json.Unmarshal([]byte(bodyLogitBias), &parsedLogitBias); err != nil {
					return fmt.Errorf("parsing --logit-bias JSON: %w", err)
				}
				body["logit_bias"] = parsedLogitBias
			}
			if bodyLogprobs != 0 {
				body["logprobs"] = bodyLogprobs
			}
			if bodyMaxTokens != 0 {
				body["max_tokens"] = bodyMaxTokens
			}
			if bodyModel != "" {
				body["model"] = bodyModel
			}
			if bodyN != 0 {
				body["n"] = bodyN
			}
			if bodyPresencePenalty != 0.0 {
				body["presence_penalty"] = bodyPresencePenalty
			}
			if bodyPrompt != "" {
				body["prompt"] = bodyPrompt
			}
			if bodySeed != 0 {
				body["seed"] = bodySeed
			}
			if bodyStop != "" {
				body["stop"] = bodyStop
			}
			if bodyStream != false {
				body["stream"] = bodyStream
			}
			if bodyStreamOptions != "" {
				body["stream_options"] = bodyStreamOptions
			}
			if bodySuffix != "" {
				body["suffix"] = bodySuffix
			}
			if bodyTemperature != 0.0 {
				body["temperature"] = bodyTemperature
			}
			if bodyTopP != 0.0 {
				body["top_p"] = bodyTopP
			}
			if bodyUser != "" {
				body["user"] = bodyUser
			}
			data, _, err := c.Post(path, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&bodyBestOf, "best-of", 1, "Generates `best_of` completions server-side and returns the 'best' (the one with the highest log probability per...")
	cmd.Flags().BoolVar(&bodyEcho, "echo", false, "Echo back the prompt in addition to the completion")
	cmd.Flags().Float64Var(&bodyFrequencyPenalty, "frequency-penalty", 0.000000, "Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so...")
	cmd.Flags().StringVar(&bodyLogitBias, "logit-bias", "", "Modify the likelihood of specified tokens appearing in the completion. Accepts a JSON object that maps tokens...")
	cmd.Flags().IntVar(&bodyLogprobs, "logprobs", 0, "Include the log probabilities on the `logprobs` most likely output tokens, as well the chosen tokens. For example,...")
	cmd.Flags().IntVar(&bodyMaxTokens, "max-tokens", 16, "The maximum number of [tokens](/tokenizer) that can be generated in the completion. The token count of your prompt...")
	cmd.Flags().StringVar(&bodyModel, "model", "", "ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your...")
	cmd.Flags().IntVar(&bodyN, "n", 1, "How many completions to generate for each prompt. **Note:** Because this parameter generates many completions, it...")
	cmd.Flags().Float64Var(&bodyPresencePenalty, "presence-penalty", 0.000000, "Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far,...")
	cmd.Flags().StringVar(&bodyPrompt, "prompt", "<|endoftext|>", "The prompt(s) to generate completions for, encoded as a string, array of strings, array of tokens, or array of token...")
	cmd.Flags().IntVar(&bodySeed, "seed", 0, "If specified, our system will make a best effort to sample deterministically, such that repeated requests with the...")
	cmd.Flags().StringVar(&bodyStop, "stop", "", "Not supported with latest reasoning models `o3` and `o4-mini`. Up to 4 sequences where the API will stop generating...")
	cmd.Flags().BoolVar(&bodyStream, "stream", false, "Whether to stream back partial progress. If set, tokens will be sent as data-only [server-sent...")
	cmd.Flags().StringVar(&bodyStreamOptions, "stream-options", "", "Stream options")
	cmd.Flags().StringVar(&bodySuffix, "suffix", "", "The suffix that comes after a completion of inserted text. This parameter is only supported for...")
	cmd.Flags().Float64Var(&bodyTemperature, "temperature", 1.000000, "What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while...")
	cmd.Flags().Float64Var(&bodyTopP, "top-p", 1.000000, "An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the...")
	cmd.Flags().StringVar(&bodyUser, "user", "", "A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn...")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
