// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newEmbeddingsPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyDimensions int
	var bodyEncodingFormat string
	var bodyInput string
	var bodyModel string
	var bodyUser string

	cmd := &cobra.Command{
		Use:         "embeddings",
		Short:       "Creates an embedding vector representing the input text.",
		Long:        "Shortcut for 'embeddings create'. Creates an embedding vector representing the input text.",
		Example:     "  openai-pp-cli embeddings --input example-value",
		Annotations: map[string]string{"pp:endpoint": "embeddings.create", "pp:method": "POST", "pp:path": "/embeddings"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("input") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "input")
			}
			if !cmd.Flags().Changed("model") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "model")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/embeddings"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyDimensions != 0 {
				body["dimensions"] = bodyDimensions
			}
			if bodyEncodingFormat != "" {
				body["encoding_format"] = bodyEncodingFormat
			}
			if bodyInput != "" {
				body["input"] = bodyInput
			}
			if bodyModel != "" {
				body["model"] = bodyModel
			}
			if bodyUser != "" {
				body["user"] = bodyUser
			}
			data, _, err := c.Post(path, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&bodyDimensions, "dimensions", 0, "The number of dimensions the resulting output embeddings should have. Only supported in `text-embedding-3` and later...")
	cmd.Flags().StringVar(&bodyEncodingFormat, "encoding-format", "float", "The format to return the embeddings in. Can be either `float` or [`base64`](https://pypi.org/project/pybase64/).")
	cmd.Flags().StringVar(&bodyInput, "input", "", "Input text to embed, encoded as a string or array of tokens. To embed multiple inputs in a single request, pass an...")
	cmd.Flags().StringVar(&bodyModel, "model", "", "ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your...")
	cmd.Flags().StringVar(&bodyUser, "user", "", "A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn...")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
