// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRealtimeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "realtime",
		Short:  "Manage realtime",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRealtimeAcceptCallCmd(flags))
	cmd.AddCommand(newRealtimeCreateCallCmd(flags))
	cmd.AddCommand(newRealtimeCreateClientSecretCmd(flags))
	cmd.AddCommand(newRealtimeCreateSessionCmd(flags))
	cmd.AddCommand(newRealtimeCreateTranscriptionSessionCmd(flags))
	cmd.AddCommand(newRealtimeCreateTranslationClientSecretCmd(flags))
	cmd.AddCommand(newRealtimeHangupCallCmd(flags))
	cmd.AddCommand(newRealtimeReferCallCmd(flags))
	cmd.AddCommand(newRealtimeRejectCallCmd(flags))
	return cmd
}
