// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newRealtimeCreateSessionCmd(flags *rootFlags) *cobra.Command {
	var bodyClientSecretExpiresAt int
	var bodyClientSecretValue string
	var bodyInputAudioFormat string
	var bodyInputAudioTranscriptionModel string
	var bodyInstructions string
	var bodyMaxResponseOutputTokens string
	var bodyModalities string
	var bodyOutputAudioFormat string
	var bodyPrompt string
	var bodySpeed float64
	var bodyTemperature float64
	var bodyToolChoice string
	var bodyTools string
	var bodyTracing string
	var bodyTruncation string
	var bodyTurnDetectionPrefixPaddingMs int
	var bodyTurnDetectionSilenceDurationMs int
	var bodyTurnDetectionThreshold float64
	var bodyTurnDetectionType string
	var bodyVoice string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-session",
		Short:       "Create an ephemeral API token for use in client-side applications with the Realtime API. Can be configured with the...",
		Example:     "  openai-pp-cli realtime create-session",
		Annotations: map[string]string{"pp:endpoint": "realtime.create-session", "pp:method": "POST", "pp:path": "/realtime/sessions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("client-secret-expires-at") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "client-secret-expires-at")
				}
				if !cmd.Flags().Changed("client-secret-value") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "client-secret-value")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/realtime/sessions"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedClientSecret := map[string]any{}
					if bodyClientSecretExpiresAt != 0 {
						nestedClientSecret["expires_at"] = bodyClientSecretExpiresAt
					}
					if bodyClientSecretValue != "" {
						nestedClientSecret["value"] = bodyClientSecretValue
					}
					if len(nestedClientSecret) > 0 {
						body["client_secret"] = nestedClientSecret
					}
				}
				if bodyInputAudioFormat != "" {
					body["input_audio_format"] = bodyInputAudioFormat
				}
				{
					nestedInputAudioTranscription := map[string]any{}
					if bodyInputAudioTranscriptionModel != "" {
						nestedInputAudioTranscription["model"] = bodyInputAudioTranscriptionModel
					}
					if len(nestedInputAudioTranscription) > 0 {
						body["input_audio_transcription"] = nestedInputAudioTranscription
					}
				}
				if bodyInstructions != "" {
					body["instructions"] = bodyInstructions
				}
				if bodyMaxResponseOutputTokens != "" {
					body["max_response_output_tokens"] = bodyMaxResponseOutputTokens
				}
				if bodyModalities != "" {
					body["modalities"] = bodyModalities
				}
				if bodyOutputAudioFormat != "" {
					body["output_audio_format"] = bodyOutputAudioFormat
				}
				if bodyPrompt != "" {
					body["prompt"] = bodyPrompt
				}
				if bodySpeed != 0.0 {
					body["speed"] = bodySpeed
				}
				if bodyTemperature != 0.0 {
					body["temperature"] = bodyTemperature
				}
				if bodyToolChoice != "" {
					body["tool_choice"] = bodyToolChoice
				}
				if bodyTools != "" {
					var parsedTools any
					if err := json.Unmarshal([]byte(bodyTools), &parsedTools); err != nil {
						return fmt.Errorf("parsing --tools JSON: %w", err)
					}
					body["tools"] = parsedTools
				}
				if bodyTracing != "" {
					body["tracing"] = bodyTracing
				}
				if bodyTruncation != "" {
					body["truncation"] = bodyTruncation
				}
				{
					nestedTurnDetection := map[string]any{}
					if bodyTurnDetectionPrefixPaddingMs != 0 {
						nestedTurnDetection["prefix_padding_ms"] = bodyTurnDetectionPrefixPaddingMs
					}
					if bodyTurnDetectionSilenceDurationMs != 0 {
						nestedTurnDetection["silence_duration_ms"] = bodyTurnDetectionSilenceDurationMs
					}
					if bodyTurnDetectionThreshold != 0.0 {
						nestedTurnDetection["threshold"] = bodyTurnDetectionThreshold
					}
					if bodyTurnDetectionType != "" {
						nestedTurnDetection["type"] = bodyTurnDetectionType
					}
					if len(nestedTurnDetection) > 0 {
						body["turn_detection"] = nestedTurnDetection
					}
				}
				if bodyVoice != "" {
					body["voice"] = bodyVoice
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "realtime",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&bodyClientSecretExpiresAt, "client-secret-expires-at", 0, "Timestamp for when the token expires. Currently, all tokens expire after one minute.")
	cmd.Flags().StringVar(&bodyClientSecretValue, "client-secret-value", "", "Ephemeral key usable in client environments to authenticate connections to the Realtime API. Use this in client-side...")
	cmd.Flags().StringVar(&bodyInputAudioFormat, "input-audio-format", "", "The format of input audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`.")
	cmd.Flags().StringVar(&bodyInputAudioTranscriptionModel, "input-audio-transcription-model", "", "The model to use for transcription.")
	cmd.Flags().StringVar(&bodyInstructions, "instructions", "", "The default system instructions (i.e. system message) prepended to model calls. This field allows the client to...")
	cmd.Flags().StringVar(&bodyMaxResponseOutputTokens, "max-response-output-tokens", "", "Maximum number of output tokens for a single assistant response, inclusive of tool calls. Provide an integer between...")
	cmd.Flags().StringVar(&bodyModalities, "modalities", "", "The set of modalities the model can respond with. To disable audio, set this to ['text'].")
	cmd.Flags().StringVar(&bodyOutputAudioFormat, "output-audio-format", "", "The format of output audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`.")
	cmd.Flags().StringVar(&bodyPrompt, "prompt", "", "Prompt")
	cmd.Flags().Float64Var(&bodySpeed, "speed", 1.000000, "The speed of the model's spoken response. 1.0 is the default speed. 0.25 is the minimum speed. 1.5 is the maximum...")
	cmd.Flags().Float64Var(&bodyTemperature, "temperature", 0.0, "Sampling temperature for the model, limited to [0.6, 1.2]. Defaults to 0.8.")
	cmd.Flags().StringVar(&bodyToolChoice, "tool-choice", "", "How the model chooses tools. Options are `auto`, `none`, `required`, or specify a function.")
	cmd.Flags().StringVar(&bodyTools, "tools", "", "Tools (functions) available to the model.")
	cmd.Flags().StringVar(&bodyTracing, "tracing", "", "Configuration options for tracing. Set to null to disable tracing. Once tracing is enabled for a session, the...")
	cmd.Flags().StringVar(&bodyTruncation, "truncation", "", "When the number of tokens in a conversation exceeds the model's input token limit, the conversation be truncated,...")
	cmd.Flags().IntVar(&bodyTurnDetectionPrefixPaddingMs, "turn-detection-prefix-padding-ms", 0, "Amount of audio to include before the VAD detected speech (in milliseconds). Defaults to 300ms.")
	cmd.Flags().IntVar(&bodyTurnDetectionSilenceDurationMs, "turn-detection-silence-duration-ms", 0, "Duration of silence to detect speech stop (in milliseconds). Defaults to 500ms. With shorter values the model will...")
	cmd.Flags().Float64Var(&bodyTurnDetectionThreshold, "turn-detection-threshold", 0.0, "Activation threshold for VAD (0.0 to 1.0), this defaults to 0.5. A higher threshold will require louder audio to...")
	cmd.Flags().StringVar(&bodyTurnDetectionType, "turn-detection-type", "", "Type of turn detection, only `server_vad` is currently supported.")
	cmd.Flags().StringVar(&bodyVoice, "voice", "", "The voice the model uses to respond. Supported built-in voices are `alloy`, `ash`, `ballad`, `coral`, `echo`,...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
