// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newResponsesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "responses",
		Short:  "Manage responses",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newResponsesCompactconversationCmd(flags))
	cmd.AddCommand(newResponsesCreateCmd(flags))
	cmd.AddCommand(newResponsesDeleteCmd(flags))
	cmd.AddCommand(newResponsesGetCmd(flags))
	cmd.AddCommand(newResponsesGetinputtokencountsCmd(flags))
	cmd.AddCommand(newResponsesCancelCmd(flags))
	cmd.AddCommand(newResponsesInputItemsCmd(flags))
	return cmd
}
