// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newResponsesGetinputtokencountsCmd(flags *rootFlags) *cobra.Command {
	var bodyConversation string
	var bodyInput string
	var bodyInstructions string
	var bodyModel string
	var bodyParallelToolCalls string
	var bodyPreviousResponseId string
	var bodyReasoning string
	var bodyText string
	var bodyToolChoice string
	var bodyTools string
	var bodyTruncation string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "getinputtokencounts",
		Short:       "Returns input token counts of the request. Returns an object with `object` set to `response.input_tokens` and an...",
		Example:     "  openai-pp-cli responses getinputtokencounts",
		Annotations: map[string]string{"pp:endpoint": "responses.getinputtokencounts", "pp:method": "POST", "pp:path": "/responses/input_tokens"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/responses/input_tokens"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyConversation != "" {
					body["conversation"] = bodyConversation
				}
				if bodyInput != "" {
					body["input"] = bodyInput
				}
				if bodyInstructions != "" {
					body["instructions"] = bodyInstructions
				}
				if bodyModel != "" {
					body["model"] = bodyModel
				}
				if bodyParallelToolCalls != "" {
					body["parallel_tool_calls"] = bodyParallelToolCalls
				}
				if bodyPreviousResponseId != "" {
					body["previous_response_id"] = bodyPreviousResponseId
				}
				if bodyReasoning != "" {
					body["reasoning"] = bodyReasoning
				}
				if bodyText != "" {
					body["text"] = bodyText
				}
				if bodyToolChoice != "" {
					body["tool_choice"] = bodyToolChoice
				}
				if bodyTools != "" {
					body["tools"] = bodyTools
				}
				if bodyTruncation != "" {
					body["truncation"] = bodyTruncation
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "responses",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyConversation, "conversation", "", "Conversation")
	cmd.Flags().StringVar(&bodyInput, "input", "", "Input")
	cmd.Flags().StringVar(&bodyInstructions, "instructions", "", "Instructions")
	cmd.Flags().StringVar(&bodyModel, "model", "", "Model")
	cmd.Flags().StringVar(&bodyParallelToolCalls, "parallel-tool-calls", "", "Parallel tool calls")
	cmd.Flags().StringVar(&bodyPreviousResponseId, "previous-response-id", "", "Previous response id")
	cmd.Flags().StringVar(&bodyReasoning, "reasoning", "", "Reasoning")
	cmd.Flags().StringVar(&bodyText, "text", "", "Text")
	cmd.Flags().StringVar(&bodyToolChoice, "tool-choice", "", "Tool choice")
	cmd.Flags().StringVar(&bodyTools, "tools", "", "Tools")
	cmd.Flags().StringVar(&bodyTruncation, "truncation", "", "The truncation strategy to use for the model response. - `auto`: If the input to this Response exceeds the model's...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
