// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newResponsesGetCmd(flags *rootFlags) *cobra.Command {
	var flagInclude string
	var flagStream bool
	var flagStartingAfter int
	var flagIncludeObfuscation bool

	cmd := &cobra.Command{
		Use:         "get <response_id>",
		Short:       "Retrieves a model response with the given ID.",
		Example:     "  openai-pp-cli responses get 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "responses.get", "pp:method": "GET", "pp:path": "/responses/{response_id}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/responses/{response_id}"
			path = replacePathParam(path, "response_id", args[0])
			params := map[string]string{}
			if flagInclude != "" {
				params["include"] = fmt.Sprintf("%v", flagInclude)
			}
			if flagStream != false {
				params["stream"] = fmt.Sprintf("%v", flagStream)
			}
			if flagStartingAfter != 0 {
				params["starting_after"] = fmt.Sprintf("%v", flagStartingAfter)
			}
			if flagIncludeObfuscation != false {
				params["include_obfuscation"] = fmt.Sprintf("%v", flagIncludeObfuscation)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "responses", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagInclude, "include", "", "Additional fields to include in the response. See the `include` parameter for Response creation above for more...")
	cmd.Flags().BoolVar(&flagStream, "stream", false, "If set to true, the model response data will be streamed to the client as it is generated using [server-sent...")
	cmd.Flags().IntVar(&flagStartingAfter, "starting-after", 0, "The sequence number of the event after which to start streaming.")
	cmd.Flags().BoolVar(&flagIncludeObfuscation, "include-obfuscation", false, "When true, stream obfuscation will be enabled. Stream obfuscation adds random characters to an `obfuscation` field...")

	return cmd
}
