// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newResponsesCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyBackground string
	var bodyContextManagement string
	var bodyConversation string
	var bodyInclude string
	var bodyInput string
	var bodyInstructions string
	var bodyMaxOutputTokens string
	var bodyMaxToolCalls string
	var bodyMetadata string
	var bodyModel string
	var bodyParallelToolCalls string
	var bodyPreviousResponseId string
	var bodyPrompt string
	var bodyPromptCacheKey string
	var bodyPromptCacheRetention string
	var bodyReasoning string
	var bodySafetyIdentifier string
	var bodyServiceTier string
	var bodyStore string
	var bodyStream string
	var bodyStreamOptions string
	var bodyTemperature string
	var bodyTextFormat string
	var bodyTextVerbosity string
	var bodyToolChoice string
	var bodyTools string
	var bodyTopLogprobs int
	var bodyTopP string
	var bodyTruncation string
	var bodyUser string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Creates a model response. Provide [text](/docs/guides/text) or [image](/docs/guides/images) inputs to generate...",
		Example:     "  openai-pp-cli responses create",
		Annotations: map[string]string{"pp:endpoint": "responses.create", "pp:method": "POST", "pp:path": "/responses"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/responses"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyBackground != "" {
					body["background"] = bodyBackground
				}
				if bodyContextManagement != "" {
					body["context_management"] = bodyContextManagement
				}
				if bodyConversation != "" {
					body["conversation"] = bodyConversation
				}
				if bodyInclude != "" {
					body["include"] = bodyInclude
				}
				if bodyInput != "" {
					body["input"] = bodyInput
				}
				if bodyInstructions != "" {
					body["instructions"] = bodyInstructions
				}
				if bodyMaxOutputTokens != "" {
					body["max_output_tokens"] = bodyMaxOutputTokens
				}
				if bodyMaxToolCalls != "" {
					body["max_tool_calls"] = bodyMaxToolCalls
				}
				if bodyMetadata != "" {
					body["metadata"] = bodyMetadata
				}
				if bodyModel != "" {
					body["model"] = bodyModel
				}
				if bodyParallelToolCalls != "" {
					body["parallel_tool_calls"] = bodyParallelToolCalls
				}
				if bodyPreviousResponseId != "" {
					body["previous_response_id"] = bodyPreviousResponseId
				}
				if bodyPrompt != "" {
					body["prompt"] = bodyPrompt
				}
				if bodyPromptCacheKey != "" {
					body["prompt_cache_key"] = bodyPromptCacheKey
				}
				if bodyPromptCacheRetention != "" {
					body["prompt_cache_retention"] = bodyPromptCacheRetention
				}
				if bodyReasoning != "" {
					body["reasoning"] = bodyReasoning
				}
				if bodySafetyIdentifier != "" {
					body["safety_identifier"] = bodySafetyIdentifier
				}
				if bodyServiceTier != "" {
					body["service_tier"] = bodyServiceTier
				}
				if bodyStore != "" {
					body["store"] = bodyStore
				}
				if bodyStream != "" {
					body["stream"] = bodyStream
				}
				if bodyStreamOptions != "" {
					body["stream_options"] = bodyStreamOptions
				}
				if bodyTemperature != "" {
					body["temperature"] = bodyTemperature
				}
				{
					nestedText := map[string]any{}
					if bodyTextFormat != "" {
						var parsedTextFormat any
						if err := json.Unmarshal([]byte(bodyTextFormat), &parsedTextFormat); err != nil {
							return fmt.Errorf("parsing --text-format JSON: %w", err)
						}
						nestedText["format"] = bodyTextFormat
					}
					if bodyTextVerbosity != "" {
						nestedText["verbosity"] = bodyTextVerbosity
					}
					if len(nestedText) > 0 {
						body["text"] = nestedText
					}
				}
				if bodyToolChoice != "" {
					body["tool_choice"] = bodyToolChoice
				}
				if bodyTools != "" {
					var parsedTools any
					if err := json.Unmarshal([]byte(bodyTools), &parsedTools); err != nil {
						return fmt.Errorf("parsing --tools JSON: %w", err)
					}
					body["tools"] = parsedTools
				}
				if bodyTopLogprobs != 0 {
					body["top_logprobs"] = bodyTopLogprobs
				}
				if bodyTopP != "" {
					body["top_p"] = bodyTopP
				}
				if bodyTruncation != "" {
					body["truncation"] = bodyTruncation
				}
				if bodyUser != "" {
					body["user"] = bodyUser
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "responses",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyBackground, "background", "", "Background")
	cmd.Flags().StringVar(&bodyContextManagement, "context-management", "", "Context management")
	cmd.Flags().StringVar(&bodyConversation, "conversation", "", "Conversation")
	cmd.Flags().StringVar(&bodyInclude, "include", "", "Include")
	cmd.Flags().StringVar(&bodyInput, "input", "", "Text, image, or file inputs to the model, used to generate a response. Learn more: - [Text inputs and...")
	cmd.Flags().StringVar(&bodyInstructions, "instructions", "", "Instructions")
	cmd.Flags().StringVar(&bodyMaxOutputTokens, "max-output-tokens", "", "Max output tokens")
	cmd.Flags().StringVar(&bodyMaxToolCalls, "max-tool-calls", "", "Max tool calls")
	cmd.Flags().StringVar(&bodyMetadata, "metadata", "", "Metadata")
	cmd.Flags().StringVar(&bodyModel, "model", "", "Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI offers a wide range of models with different...")
	cmd.Flags().StringVar(&bodyParallelToolCalls, "parallel-tool-calls", "", "Parallel tool calls")
	cmd.Flags().StringVar(&bodyPreviousResponseId, "previous-response-id", "", "Previous response id")
	cmd.Flags().StringVar(&bodyPrompt, "prompt", "", "Prompt")
	cmd.Flags().StringVar(&bodyPromptCacheKey, "prompt-cache-key", "", "Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the `user` field....")
	cmd.Flags().StringVar(&bodyPromptCacheRetention, "prompt-cache-retention", "", "Prompt cache retention")
	cmd.Flags().StringVar(&bodyReasoning, "reasoning", "", "Reasoning")
	cmd.Flags().StringVar(&bodySafetyIdentifier, "safety-identifier", "", "A stable identifier used to help detect users of your application that may be violating OpenAI's usage policies. The...")
	cmd.Flags().StringVar(&bodyServiceTier, "service-tier", "", "Service tier")
	cmd.Flags().StringVar(&bodyStore, "store", "", "Store")
	cmd.Flags().StringVar(&bodyStream, "stream", "", "Stream")
	cmd.Flags().StringVar(&bodyStreamOptions, "stream-options", "", "Stream options")
	cmd.Flags().StringVar(&bodyTemperature, "temperature", "", "Temperature")
	cmd.Flags().StringVar(&bodyTextFormat, "text-format", "", "An object specifying the format that the model must output. Configuring `{ 'type': 'json_schema' }` enables...")
	cmd.Flags().StringVar(&bodyTextVerbosity, "text-verbosity", "", "Verbosity")
	cmd.Flags().StringVar(&bodyToolChoice, "tool-choice", "", "How the model should select which tool (or tools) to use when generating a response. See the `tools` parameter to...")
	cmd.Flags().StringVar(&bodyTools, "tools", "", "An array of tools the model may call while generating a response. You can specify which tool to use by setting the...")
	cmd.Flags().IntVar(&bodyTopLogprobs, "top-logprobs", 0, "An integer between 0 and 20 specifying the maximum number of most likely tokens to return at each token position,...")
	cmd.Flags().StringVar(&bodyTopP, "top-p", "", "Top p")
	cmd.Flags().StringVar(&bodyTruncation, "truncation", "", "Truncation")
	cmd.Flags().StringVar(&bodyUser, "user", "", "This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use `prompt_cache_key` instead to...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
