// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSkillsVersionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "versions",
		Short: "Manage versions",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSkillsVersionsCreateSkillCmd(flags))
	cmd.AddCommand(newSkillsVersionsDeleteSkillCmd(flags))
	cmd.AddCommand(newSkillsVersionsGetSkillCmd(flags))
	cmd.AddCommand(newSkillsVersionsGetSkillContentCmd(flags))
	cmd.AddCommand(newSkillsVersionsListSkillCmd(flags))
	return cmd
}
