// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newThreadsMessagesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "messages",
		Short: "Manage messages",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newThreadsMessagesCreateCmd(flags))
	cmd.AddCommand(newThreadsMessagesDeleteCmd(flags))
	cmd.AddCommand(newThreadsMessagesGetCmd(flags))
	cmd.AddCommand(newThreadsMessagesListCmd(flags))
	cmd.AddCommand(newThreadsMessagesModifyCmd(flags))
	return cmd
}
