// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newThreadsCreateAndRunCmd(flags *rootFlags) *cobra.Command {
	var bodyAssistantId string
	var bodyInstructions string
	var bodyMaxCompletionTokens int
	var bodyMaxPromptTokens int
	var bodyMetadata string
	var bodyModel string
	var bodyParallelToolCalls bool
	var bodyResponseFormat string
	var bodyStream bool
	var bodyTemperature float64
	var bodyThreadMessages string
	var bodyThreadMetadata string
	var bodyThreadToolResources string
	var bodyToolChoice string
	var bodyToolResourcesCodeInterpreterFileIds string
	var bodyToolResourcesFileSearchVectorStoreIds string
	var bodyTools string
	var bodyTopP float64
	var bodyTruncationStrategyLastMessages string
	var bodyTruncationStrategyType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-and-run",
		Short:       "Create a thread and run it in one request.",
		Example:     "  openai-pp-cli threads create-and-run --assistant-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "threads.create-and-run", "pp:method": "POST", "pp:path": "/threads/runs"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("assistant-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "assistant-id")
				}
				if !cmd.Flags().Changed("truncation-strategy-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "truncation-strategy-type")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/threads/runs"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAssistantId != "" {
					body["assistant_id"] = bodyAssistantId
				}
				if bodyInstructions != "" {
					body["instructions"] = bodyInstructions
				}
				if bodyMaxCompletionTokens != 0 {
					body["max_completion_tokens"] = bodyMaxCompletionTokens
				}
				if bodyMaxPromptTokens != 0 {
					body["max_prompt_tokens"] = bodyMaxPromptTokens
				}
				if bodyMetadata != "" {
					body["metadata"] = bodyMetadata
				}
				if bodyModel != "" {
					body["model"] = bodyModel
				}
				if bodyParallelToolCalls != false {
					body["parallel_tool_calls"] = bodyParallelToolCalls
				}
				if bodyResponseFormat != "" {
					var parsedResponseFormat any
					if err := json.Unmarshal([]byte(bodyResponseFormat), &parsedResponseFormat); err != nil {
						return fmt.Errorf("parsing --response-format JSON: %w", err)
					}
					body["response_format"] = bodyResponseFormat
				}
				if bodyStream != false {
					body["stream"] = bodyStream
				}
				if bodyTemperature != 0.0 {
					body["temperature"] = bodyTemperature
				}
				{
					nestedThread := map[string]any{}
					if bodyThreadMessages != "" {
						var parsedThreadMessages any
						if err := json.Unmarshal([]byte(bodyThreadMessages), &parsedThreadMessages); err != nil {
							return fmt.Errorf("parsing --thread-messages JSON: %w", err)
						}
						nestedThread["messages"] = parsedThreadMessages
					}
					if bodyThreadMetadata != "" {
						nestedThread["metadata"] = bodyThreadMetadata
					}
					if bodyThreadToolResources != "" {
						nestedThread["tool_resources"] = bodyThreadToolResources
					}
					if len(nestedThread) > 0 {
						body["thread"] = nestedThread
					}
				}
				if bodyToolChoice != "" {
					body["tool_choice"] = bodyToolChoice
				}
				{
					nestedToolResources := map[string]any{}
					{
						nestedToolResourcesCodeInterpreter := map[string]any{}
						if bodyToolResourcesCodeInterpreterFileIds != "" {
							var parsedToolResourcesCodeInterpreterFileIds any
							if err := json.Unmarshal([]byte(bodyToolResourcesCodeInterpreterFileIds), &parsedToolResourcesCodeInterpreterFileIds); err != nil {
								return fmt.Errorf("parsing --tool-resources-code-interpreter-file-ids JSON: %w", err)
							}
							nestedToolResourcesCodeInterpreter["file_ids"] = parsedToolResourcesCodeInterpreterFileIds
						}
						if len(nestedToolResourcesCodeInterpreter) > 0 {
							nestedToolResources["code_interpreter"] = nestedToolResourcesCodeInterpreter
						}
					}
					{
						nestedToolResourcesFileSearch := map[string]any{}
						if bodyToolResourcesFileSearchVectorStoreIds != "" {
							var parsedToolResourcesFileSearchVectorStoreIds any
							if err := json.Unmarshal([]byte(bodyToolResourcesFileSearchVectorStoreIds), &parsedToolResourcesFileSearchVectorStoreIds); err != nil {
								return fmt.Errorf("parsing --tool-resources-file-search-vector-store-ids JSON: %w", err)
							}
							nestedToolResourcesFileSearch["vector_store_ids"] = parsedToolResourcesFileSearchVectorStoreIds
						}
						if len(nestedToolResourcesFileSearch) > 0 {
							nestedToolResources["file_search"] = nestedToolResourcesFileSearch
						}
					}
					if len(nestedToolResources) > 0 {
						body["tool_resources"] = nestedToolResources
					}
				}
				if bodyTools != "" {
					var parsedTools any
					if err := json.Unmarshal([]byte(bodyTools), &parsedTools); err != nil {
						return fmt.Errorf("parsing --tools JSON: %w", err)
					}
					body["tools"] = parsedTools
				}
				if bodyTopP != 0.0 {
					body["top_p"] = bodyTopP
				}
				{
					nestedTruncationStrategy := map[string]any{}
					if bodyTruncationStrategyLastMessages != "" {
						nestedTruncationStrategy["last_messages"] = bodyTruncationStrategyLastMessages
					}
					if bodyTruncationStrategyType != "" {
						nestedTruncationStrategy["type"] = bodyTruncationStrategyType
					}
					if len(nestedTruncationStrategy) > 0 {
						body["truncation_strategy"] = nestedTruncationStrategy
					}
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "threads",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAssistantId, "assistant-id", "", "The ID of the [assistant](/docs/api-reference/assistants) to use to execute this run.")
	cmd.Flags().StringVar(&bodyInstructions, "instructions", "", "Override the default system message of the assistant. This is useful for modifying the behavior on a per-run basis.")
	cmd.Flags().IntVar(&bodyMaxCompletionTokens, "max-completion-tokens", 0, "The maximum number of completion tokens that may be used over the course of the run. The run will make a best effort...")
	cmd.Flags().IntVar(&bodyMaxPromptTokens, "max-prompt-tokens", 0, "The maximum number of prompt tokens that may be used over the course of the run. The run will make a best effort to...")
	cmd.Flags().StringVar(&bodyMetadata, "metadata", "", "Metadata")
	cmd.Flags().StringVar(&bodyModel, "model", "", "The ID of the [Model](/docs/api-reference/models) to be used to execute this run. If a value is provided here, it...")
	cmd.Flags().BoolVar(&bodyParallelToolCalls, "parallel-tool-calls", true, "Whether to enable [parallel function calling](/docs/guides/function-calling#configuring-parallel-function-calling)...")
	cmd.Flags().StringVar(&bodyResponseFormat, "response-format", "", "Specifies the format that the model must output. Compatible with [GPT-4o](/docs/models#gpt-4o), [GPT-4...")
	cmd.Flags().BoolVar(&bodyStream, "stream", false, "If `true`, returns a stream of events that happen during the Run as server-sent events, terminating when the Run...")
	cmd.Flags().Float64Var(&bodyTemperature, "temperature", 1.000000, "What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while...")
	cmd.Flags().StringVar(&bodyThreadMessages, "thread-messages", "", "A list of [messages](/docs/api-reference/messages) to start the thread with.")
	cmd.Flags().StringVar(&bodyThreadMetadata, "thread-metadata", "", "Metadata")
	cmd.Flags().StringVar(&bodyThreadToolResources, "thread-tool-resources", "", "Tool resources")
	cmd.Flags().StringVar(&bodyToolChoice, "tool-choice", "", "Tool choice")
	cmd.Flags().StringVar(&bodyToolResourcesCodeInterpreterFileIds, "tool-resources-code-interpreter-file-ids", "", "A list of [file](/docs/api-reference/files) IDs made available to the `code_interpreter` tool. There can be a...")
	cmd.Flags().StringVar(&bodyToolResourcesFileSearchVectorStoreIds, "tool-resources-file-search-vector-store-ids", "", "The ID of the [vector store](/docs/api-reference/vector-stores/object) attached to this assistant. There can be a...")
	cmd.Flags().StringVar(&bodyTools, "tools", "", "Override the tools the assistant can use for this run. This is useful for modifying the behavior on a per-run basis.")
	cmd.Flags().Float64Var(&bodyTopP, "top-p", 1.000000, "An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the...")
	cmd.Flags().StringVar(&bodyTruncationStrategyLastMessages, "truncation-strategy-last-messages", "", "Last messages")
	cmd.Flags().StringVar(&bodyTruncationStrategyType, "truncation-strategy-type", "", "The truncation strategy to use for the thread. The default is `auto`. If set to `last_messages`, the thread will be...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
