// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newVectorStoresCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyChunkingStrategy string
	var bodyDescription string
	var bodyExpiresAfterAnchor string
	var bodyExpiresAfterDays int
	var bodyFileIds string
	var bodyMetadata string
	var bodyName string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Create a vector store.",
		Example:     "  openai-pp-cli vector-stores create",
		Annotations: map[string]string{"pp:endpoint": "vector-stores.create", "pp:method": "POST", "pp:path": "/vector_stores"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("expires-after-anchor") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "expires-after-anchor")
				}
				if !cmd.Flags().Changed("expires-after-days") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "expires-after-days")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/vector_stores"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyChunkingStrategy != "" {
					var parsedChunkingStrategy any
					if err := json.Unmarshal([]byte(bodyChunkingStrategy), &parsedChunkingStrategy); err != nil {
						return fmt.Errorf("parsing --chunking-strategy JSON: %w", err)
					}
					body["chunking_strategy"] = parsedChunkingStrategy
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				{
					nestedExpiresAfter := map[string]any{}
					if bodyExpiresAfterAnchor != "" {
						nestedExpiresAfter["anchor"] = bodyExpiresAfterAnchor
					}
					if bodyExpiresAfterDays != 0 {
						nestedExpiresAfter["days"] = bodyExpiresAfterDays
					}
					if len(nestedExpiresAfter) > 0 {
						body["expires_after"] = nestedExpiresAfter
					}
				}
				if bodyFileIds != "" {
					var parsedFileIds any
					if err := json.Unmarshal([]byte(bodyFileIds), &parsedFileIds); err != nil {
						return fmt.Errorf("parsing --file-ids JSON: %w", err)
					}
					body["file_ids"] = parsedFileIds
				}
				if bodyMetadata != "" {
					body["metadata"] = bodyMetadata
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "vector-stores",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyChunkingStrategy, "chunking-strategy", "", "The chunking strategy used to chunk the file(s). If not set, will use the `auto` strategy. Only applicable if...")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "A description for the vector store. Can be used to describe the vector store's purpose.")
	cmd.Flags().StringVar(&bodyExpiresAfterAnchor, "expires-after-anchor", "", "Anchor timestamp after which the expiration policy applies. Supported anchors: `last_active_at`.")
	cmd.Flags().IntVar(&bodyExpiresAfterDays, "expires-after-days", 0, "The number of days after the anchor time that the vector store will expire.")
	cmd.Flags().StringVar(&bodyFileIds, "file-ids", "", "A list of [File](/docs/api-reference/files) IDs that the vector store should use. Useful for tools like...")
	cmd.Flags().StringVar(&bodyMetadata, "metadata", "", "Metadata")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the vector store.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
