// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newVectorStoresCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "vector-stores",
		Short:  "Manage vector stores",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newVectorStoresCreateCmd(flags))
	cmd.AddCommand(newVectorStoresDeleteCmd(flags))
	cmd.AddCommand(newVectorStoresGetCmd(flags))
	cmd.AddCommand(newVectorStoresListCmd(flags))
	cmd.AddCommand(newVectorStoresModifyCmd(flags))
	cmd.AddCommand(newVectorStoresFileBatchesCmd(flags))
	cmd.AddCommand(newVectorStoresFilesCmd(flags))
	cmd.AddCommand(newVectorStoresSearchCmd(flags))
	return cmd
}
