// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newVectorStoresFilesCreateVectorStoreCmd(flags *rootFlags) *cobra.Command {
	var bodyAttributes string
	var bodyChunkingStrategy string
	var bodyFileId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-vector-store <vector_store_id>",
		Aliases:     []string{"create"},
		Short:       "This endpoint is subject to a per-vector-store write rate limit of 300 requests per minute, shared with...",
		Example:     "  openai-pp-cli vector-stores files create-vector-store 550e8400-e29b-41d4-a716-446655440000 --file-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "files.create-vector-store", "pp:method": "POST", "pp:path": "/vector_stores/{vector_store_id}/files"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("file-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "file-id")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/vector_stores/{vector_store_id}/files"
			path = replacePathParam(path, "vector_store_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAttributes != "" {
					body["attributes"] = bodyAttributes
				}
				if bodyChunkingStrategy != "" {
					var parsedChunkingStrategy any
					if err := json.Unmarshal([]byte(bodyChunkingStrategy), &parsedChunkingStrategy); err != nil {
						return fmt.Errorf("parsing --chunking-strategy JSON: %w", err)
					}
					body["chunking_strategy"] = parsedChunkingStrategy
				}
				if bodyFileId != "" {
					body["file_id"] = bodyFileId
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "files",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAttributes, "attributes", "", "Attributes")
	cmd.Flags().StringVar(&bodyChunkingStrategy, "chunking-strategy", "", "The chunking strategy used to chunk the file(s). If not set, will use the `auto` strategy.")
	cmd.Flags().StringVar(&bodyFileId, "file-id", "", "A [File](/docs/api-reference/files) ID that the vector store should use. Useful for tools like `file_search` that...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
