// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newVideosCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "videos",
		Short:  "Manage videos",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newVideosCreateCmd(flags))
	cmd.AddCommand(newVideosCreateCharacterCmd(flags))
	cmd.AddCommand(newVideosCreateEditCmd(flags))
	cmd.AddCommand(newVideosCreateExtendCmd(flags))
	cmd.AddCommand(newVideosDeleteCmd(flags))
	cmd.AddCommand(newVideosGetCmd(flags))
	cmd.AddCommand(newVideosGetCharacterCmd(flags))
	cmd.AddCommand(newVideosListCmd(flags))
	cmd.AddCommand(newVideosContentCmd(flags))
	cmd.AddCommand(newVideosRemixCmd(flags))
	return cmd
}
