// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newVideosCreateExtendCmd(flags *rootFlags) *cobra.Command {
	var bodyPrompt string
	var bodySeconds string
	var bodyVideoId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-extend",
		Short:       "Create an extension of a completed video.",
		Example:     "  openai-pp-cli videos create-extend --prompt example-value",
		Annotations: map[string]string{"pp:endpoint": "videos.create-extend", "pp:method": "POST", "pp:path": "/videos/extensions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("prompt") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "prompt")
				}
				if !cmd.Flags().Changed("seconds") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "seconds")
				}
				if !cmd.Flags().Changed("video-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "video-id")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/videos/extensions"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyPrompt != "" {
					body["prompt"] = bodyPrompt
				}
				if bodySeconds != "" {
					body["seconds"] = bodySeconds
				}
				{
					nestedVideo := map[string]any{}
					if bodyVideoId != "" {
						nestedVideo["id"] = bodyVideoId
					}
					if len(nestedVideo) > 0 {
						body["video"] = nestedVideo
					}
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "videos",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyPrompt, "prompt", "", "Updated text prompt that directs the extension generation.")
	cmd.Flags().StringVar(&bodySeconds, "seconds", "", "Length of the newly generated extension segment in seconds (allowed values: 4, 8, 12, 16, 20).")
	cmd.Flags().StringVar(&bodyVideoId, "video-id", "", "The identifier of the completed video.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
