// Copyright 2026 garik-v. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newVideosContentRetrieveVideoCmd(flags *rootFlags) *cobra.Command {
	var flagVariant string

	cmd := &cobra.Command{
		Use:         "retrieve-video <video_id>",
		Aliases:     []string{"get"},
		Short:       "Download the generated video bytes or a derived preview asset. Streams the rendered video content for the specified...",
		Example:     "  openai-pp-cli videos content retrieve-video 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "content.retrieve-video", "pp:method": "GET", "pp:path": "/videos/{video_id}/content", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("variant") {
				allowedVariant := []string{"video", "thumbnail", "spritesheet"}
				validVariant := false
				for _, v := range allowedVariant {
					if flagVariant == v {
						validVariant = true
						break
					}
				}
				if !validVariant {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "variant", flagVariant, allowedVariant)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/videos/{video_id}/content"
			path = replacePathParam(path, "video_id", args[0])
			params := map[string]string{}
			if flagVariant != "" {
				params["variant"] = fmt.Sprintf("%v", flagVariant)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "content", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagVariant, "variant", "", "Which downloadable asset to return. Defaults to the MP4 video. (one of: video, thumbnail, spritesheet)")

	return cmd
}
