import type { FeatureManifest } from "../types";

export const objectivesFeatureManifest: FeatureManifest = {
  id: "objectives",
  name: "Obiettivi",
  owner: "full-stack",
  status: "protocol",
  webRoutes: [
    {
      path: "/dashboard",
      auth: "authenticated",
      title: "Dashboard obiettivi",
      smoke: true,
    },
  ],
  apiRoutes: [
    {
      method: "GET",
      path: "/api/objectives",
      auth: "authenticated",
      schema: "ListObjectivesQuerySchema",
      smoke: true,
    },
    {
      method: "POST",
      path: "/api/objectives",
      auth: "authenticated",
      schema: "CreateObjectiveSchema",
      smoke: true,
    },
    {
      method: "POST",
      path: "/api/objectives/seed",
      auth: "authenticated",
      schema: "SeedObjectivesSchema",
      smoke: true,
    },
    {
      method: "PATCH",
      path: "/api/objectives/:id",
      auth: "authenticated",
      schema: "UpdateObjectiveSchema",
      smoke: true,
    },
    {
      method: "DELETE",
      path: "/api/objectives/:id",
      auth: "authenticated",
      schema: "DeleteObjectiveParamsSchema",
      smoke: true,
    },
  ],
  wendyTools: [
    {
      name: "get_user_objectives",
      description: "Legge gli obiettivi attivi e il progresso dell'utente corrente.",
      policy: "read",
      risk: "low",
      requiresConfirmation: false,
      inputSchema: "GetUserObjectivesInput",
      outputSchema: "GetUserObjectivesOutput",
      telemetry: "wendy.objectives.list",
    },
    {
      name: "save_objective",
      description: "Prepara un nuovo obiettivo professionale da salvare dopo conferma utente.",
      policy: "write",
      risk: "medium",
      requiresConfirmation: true,
      inputSchema: "SaveObjectiveInput",
      outputSchema: "WendyAction<CreateObjectivePayload>",
      telemetry: "wendy.objectives.create",
    },
    {
      name: "update_objective_progress",
      description: "Prepara l'aggiornamento del progresso di un obiettivo esistente dopo conferma utente.",
      policy: "write",
      risk: "medium",
      requiresConfirmation: true,
      inputSchema: "UpdateObjectiveProgressInput",
      outputSchema: "WendyAction<UpdateObjectiveProgressPayload>",
      telemetry: "wendy.objectives.update_progress",
    },
  ],
  telemetry: [
    "objectives.list",
    "objectives.create",
    "objectives.seed",
    "objectives.update",
    "objectives.delete",
    "wendy.objectives.list",
    "wendy.objectives.create",
    "wendy.objectives.update_progress",
  ],
  smoke: [
    "objectives:list",
    "objectives:create-preview",
    "objectives:update-progress-preview",
    "wendy:create-objective-preview",
  ],
  migrations: ["user_objectives_table"],
  tests: [
    "apps/server/src/routes/objectives.test.ts",
    "apps/web/src/hooks/useWendyActionExecutor.test.ts",
    "packages/ai-server/src/__tests__/wendy-actions.test.ts",
  ],
};
