import type { FeatureManifest } from "../types";

export const profileFeatureManifest: FeatureManifest = {
  id: "profile",
  name: "Profilo",
  owner: "full-stack",
  status: "protocol",
  webRoutes: [
    {
      path: "/profilo",
      auth: "authenticated",
      title: "Profilo",
      smoke: true,
    },
    {
      path: "/memoria-wendy",
      auth: "authenticated",
      title: "Memorie Wendy",
      smoke: true,
    },
  ],
  apiRoutes: [
    {
      method: "GET",
      path: "/api/profile/:userId",
      auth: "authenticated",
      schema: "GetProfileParamsSchema",
      smoke: true,
    },
    {
      method: "PATCH",
      path: "/api/profile/:userId/avatar",
      auth: "authenticated",
      schema: "ProfileAvatarUpdateSchema",
      smoke: true,
    },
    {
      method: "PATCH",
      path: "/api/profile/:userId/banner",
      auth: "authenticated",
      schema: "ProfileBannerUpdateSchema",
      smoke: true,
    },
    {
      method: "PATCH",
      path: "/api/profile/:userId/mode",
      auth: "authenticated",
      schema: "ProfileModeUpdateSchema",
      smoke: true,
    },
    {
      method: "GET",
      path: "/api/profile/me/backgrounds",
      auth: "authenticated",
      schema: "ProfileBackgroundReadSchema",
      smoke: true,
    },
    {
      method: "PATCH",
      path: "/api/profile/me/backgrounds/appearance",
      auth: "authenticated",
      schema: "ProfileBackgroundAppearanceSchema",
      smoke: true,
    },
  ],
  wendyTools: [
    {
      name: "get_user_context",
      description: "Legge il contesto compatto dell'utente per personalizzare spiegazioni e suggerimenti.",
      policy: "read",
      risk: "low",
      requiresConfirmation: false,
      inputSchema: "GetUserContextInput",
      outputSchema: "GetUserContextOutput",
      telemetry: "wendy.profile.context",
    },
    {
      name: "open_view:profilo",
      description: "Apre il profilo o le impostazioni quando Wendy deve mostrare preferenze, privacy o memoria.",
      policy: "navigate",
      risk: "low",
      requiresConfirmation: false,
      inputSchema: "OpenViewInput",
      outputSchema: "WendyAction<NavigatePayload>",
      telemetry: "wendy.profile.navigate",
    },
    {
      name: "update_profile_preferences",
      description: "Prepara modifiche alle preferenze utente, come modalita percorso o aspetto, tramite preview confermata.",
      policy: "write",
      risk: "medium",
      requiresConfirmation: true,
      inputSchema: "UpdateProfilePreferencesInput",
      outputSchema: "WendyAction<UpdateProfilePreferencesPayload>",
      telemetry: "wendy.profile.update_preferences",
    },
  ],
  telemetry: [
    "profile.view",
    "profile.avatar.update",
    "profile.banner.update",
    "profile.mode.update",
    "profile.background.appearance",
    "wendy.profile.context",
    "wendy.profile.update_preferences",
  ],
  smoke: [
    "profile:view",
    "profile:settings",
    "profile:backgrounds-read",
    "wendy:profile-context",
    "wendy:profile-preferences-preview",
  ],
  migrations: ["user_profile_settings_table", "user_background_columns", "user_background_appearance"],
  tests: [
    "apps/server/src/routes/profile-background.test.ts",
    "apps/web/src/hooks/useUserBackground.test.tsx",
    "packages/ai-server/src/__tests__/wendy-actions.test.ts",
  ],
};
