import type { FeatureManifest } from "../types";

export const sectorsFeatureManifest: FeatureManifest = {
  id: "sectors",
  name: "Settori",
  owner: "full-stack",
  status: "protocol",
  webRoutes: [
    {
      path: "/settori",
      auth: "public",
      title: "Settori",
      smoke: true,
    },
    {
      path: "/settore/:id",
      auth: "public",
      title: "Dettaglio settore",
      smoke: true,
    },
  ],
  apiRoutes: [
    {
      method: "GET",
      path: "/api/sectors",
      auth: "public",
      schema: "ListSectorsQuerySchema",
      smoke: true,
    },
    {
      method: "GET",
      path: "/api/sectors/:id",
      auth: "public",
      schema: "GetSectorParamsSchema",
      smoke: true,
    },
    {
      method: "GET",
      path: "/api/sectors/:id/stats",
      auth: "public",
      schema: "GetSectorStatsParamsSchema",
      smoke: true,
    },
    {
      method: "GET",
      path: "/api/sectors/:id/roles",
      auth: "public",
      schema: "GetSectorRolesParamsSchema",
      smoke: true,
    },
  ],
  wendyTools: [
    {
      name: "list_sectors",
      description: "Elenca settori filtrabili per trend quando Wendy deve orientare o proporre alternative.",
      policy: "read",
      risk: "low",
      requiresConfirmation: false,
      inputSchema: "ListSectorsInput",
      outputSchema: "ListSectorsOutput",
      telemetry: "wendy.sectors.list",
    },
    {
      name: "get_sector_detail",
      description: "Recupera dati strutturati di un settore per spiegazioni, confronto e suggerimenti.",
      policy: "read",
      risk: "low",
      requiresConfirmation: false,
      inputSchema: "GetSectorDetailInput",
      outputSchema: "GetSectorDetailOutput",
      telemetry: "wendy.sectors.detail",
    },
    {
      name: "compare_sectors",
      description: "Confronta settori su salario, crescita, automazione e autonomia.",
      policy: "read",
      risk: "low",
      requiresConfirmation: false,
      inputSchema: "CompareSectorsInput",
      outputSchema: "CompareSectorsOutput",
      telemetry: "wendy.sectors.compare",
    },
    {
      name: "open_view:settore",
      description: "Apre la pagina settore quando Wendy deve accompagnare l'utente al dettaglio corretto.",
      policy: "navigate",
      risk: "low",
      requiresConfirmation: false,
      inputSchema: "OpenViewInput",
      outputSchema: "WendyAction<NavigatePayload>",
      telemetry: "wendy.sectors.navigate",
    },
  ],
  telemetry: [
    "sectors.list",
    "sectors.detail",
    "sectors.stats",
    "sectors.roles",
    "wendy.sectors.list",
    "wendy.sectors.detail",
    "wendy.sectors.navigate",
  ],
  smoke: ["sectors:list", "sectors:detail", "wendy:sector-explain", "wendy:sector-navigate"],
  migrations: ["sectors_table", "professions_table"],
  tests: [
    "apps/server/src/routes/sectors.test.ts",
    "packages/ai-server/src/__tests__/router.test.ts",
    "packages/ai-server/src/__tests__/wendy-tool-registry.test.ts",
  ],
};
